### ISSUE TITLE
messages not getting transfered to kafka

### ISSUE THREAD

**Issue by iam404** [fluent/fluent-plugin-kafka#111]
Getting below logs on fluentd instance. Also there is drop in events getting transferred to kafka.

```2017-02-08 12:16:33 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-02-08 12:20:59 +0000 error_class="Kafka::DeliveryFailed" error="Failed to assign partitions to 1 messages" plugin_id="object:2b01ced0dc70"
  2017-02-08 12:16:33 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.3.16.beta2/lib/kafka/producer.rb:325:in `deliver_messages_with_retries'
  2017-02-08 12:16:33 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.3.16.beta2/lib/kafka/producer.rb:243:in `block in deliver_messages'
  2017-02-08 12:16:33 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.3.16.beta2/lib/kafka/instrumenter.rb:21:in `instrument'
  2017-02-08 12:16:33 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.3.16.beta2/lib/kafka/producer.rb:236:in `deliver_messages'
  2017-02-08 12:16:33 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-kafka-0.5.1/lib/fluent/plugin/out_kafka_buffered.rb:266:in `write'
  2017-02-08 12:16:33 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/buffer.rb:354:in `write_chunk'
  2017-02-08 12:16:33 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/buffer.rb:333:in `pop'
  2017-02-08 12:16:33 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/output.rb:342:in `try_flush'
  2017-02-08 12:16:33 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/output.rb:149:in `run'
2017-02-08 12:16:33 +0000 fluent.warn: {"message":"Send exception occurred: Failed to assign partitions to 1 messages"}
2017-02-08 12:16:33 +0000 fluent.warn: {"message":"Exception Backtrace : /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.3.16.beta2/lib/kafka/producer.rb:325:in `deliver_messages_with_retries'\n/usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.3.16.beta2/lib/kafka/producer.rb:243:in `block in deliver_messages'\n/usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.3.16.beta2/lib/kafka/instrumenter.rb:21:in `instrument'\n/usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.3.16.beta2/lib/kafka/producer.rb:236:in `deliver_messages'\n/usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-kafka-0.5.1/lib/fluent/plugin/out_kafka_buffered.rb:266:in `write'\n/usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/buffer.rb:354:in `write_chunk'\n/usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/buffer.rb:333:in `pop'\n/usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/output.rb:342:in `try_flush'\n/usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/output.rb:149:in `run'"}
2017-02-08 12:16:33 +0000 fluent.info: {"message":"brokers has been refreshed via Zookeeper: [\"kafka.example.com:9092\", \"kafka.example.com:9092\", \"kafka.example.com:9092\"]"}
2017-02-08 12:16:33 +0000 fluent.info: {"message":"initialized kafka producer: kafka"}
2017-02-08 12:16:33 +0000 fluent.warn: {"next_retry":"2017-02-08 12:20:59 +0000","error_class":"Kafka::DeliveryFailed","error":"Failed to assign partitions to 1 messages","plugin_id":"object:2b01ced0dc70","message":"temporarily failed to flush the buffer. next_retry=2017-02-08 12:20:59 +0000 error_class=\"Kafka::DeliveryFailed\" error=\"Failed to assign partitions to 1 messages\" plugin_id=\"object:2b01ced0dc70\""}
2017-02-08 12:20:59 +0000 [warn]: retry succeeded. plugin_id="object:2b01ced0dc70"
2017-02-08 12:20:59 +0000 fluent.warn: {"plugin_id":"object:2b01ced0dc70","message":"retry succeeded. plugin_id=\"object:2b01ced0dc70\""}
```

Retry does not succeed on all the time `[warn]: retry succeeded.`

**Comment by repeatedly** [comment]
That's weird.

> [warn]: retry succeeded.

This means plugin doesn't raise an error to buffer. From your logs, fluent-plugin-kafka refreshes broker list and re-creates kafka client.
After that, there is no error between plugin and kafka cluster.

I'm not sure what is the wrong but you also need to check kafka side log and network transferred volume.

**Comment by kanupriya15025** [comment]
@iam404 Did you get it solved?

**Comment by kenhys** [comment]
https://github.com/fluent/fluent-plugin-kafka/issues/111#issue-206431443
It seems that it is similar to https://github.com/zendesk/ruby-kafka/issues/293, but it uses ruby-kafka 0.3.16.beta2.
It should contain the fix for it https://github.com/zendesk/ruby-kafka/pull/294. :thinking:
