### ISSUE TITLE
Plugin stops sending after MessageSizeTooLarge

### ISSUE THREAD

**Issue by chris060986** [fluent/fluent-plugin-kafka#117]
Hi,
when i get some messages which are too large for my kafka instance the plugin doesn't send any more messages after the error occurs.
My expection is, that the error is in the log, but fluent proceeds sedning further logs..

```2017-03-07 16:06:47 +0100 [info]: initialized kafka producer: kafka
2017-03-07 16:06:47 +0100 [warn]: temporarily failed to flush the buffer. next_retry=2017-03-07 16:06:53 +0100 error_class="Kafka::MessageSizeTooLarge" error="Kafka::MessageSizeTooLarge" plugin_id="object:d11fcc"
  2017-03-07 16:06:47 +0100 [warn]: suppressed same stacktrace
2017-03-07 16:06:55 +0100 [warn]: Send exception occurred: Kafka::MessageSizeTooLarge
2017-03-07 16:06:55 +0100 [warn]: Exception Backtrace : /var/lib/gems/2.1.0/gems/ruby-kafka-0.3.16/lib/kafka/protocol.rb:50:in `handle_error'
/var/lib/gems/2.1.0/gems/ruby-kafka-0.3.16/lib/kafka/produce_operation.rb:120:in `block in handle_response'
/var/lib/gems/2.1.0/gems/ruby-kafka-0.3.16/lib/kafka/protocol/produce_response.rb:32:in `block (2 levels) in each_partition'
/var/lib/gems/2.1.0/gems/ruby-kafka-0.3.16/lib/kafka/protocol/produce_response.rb:31:in `each'
/var/lib/gems/2.1.0/gems/ruby-kafka-0.3.16/lib/kafka/protocol/produce_response.rb:31:in `block in each_partition'
/var/lib/gems/2.1.0/gems/ruby-kafka-0.3.16/lib/kafka/protocol/produce_response.rb:30:in `each'
/var/lib/gems/2.1.0/gems/ruby-kafka-0.3.16/lib/kafka/protocol/produce_response.rb:30:in `each_partition'
/var/lib/gems/2.1.0/gems/ruby-kafka-0.3.16/lib/kafka/produce_operation.rb:112:in `handle_response'
/var/lib/gems/2.1.0/gems/ruby-kafka-0.3.16/lib/kafka/produce_operation.rb:101:in `block in send_buffered_messages'
/var/lib/gems/2.1.0/gems/ruby-kafka-0.3.16/lib/kafka/produce_operation.rb:81:in `each'
/var/lib/gems/2.1.0/gems/ruby-kafka-0.3.16/lib/kafka/produce_operation.rb:81:in `send_buffered_messages'
/var/lib/gems/2.1.0/gems/ruby-kafka-0.3.16/lib/kafka/produce_operation.rb:47:in `block in execute'
/var/lib/gems/2.1.0/gems/ruby-kafka-0.3.16/lib/kafka/instrumenter.rb:21:in `call'
/var/lib/gems/2.1.0/gems/ruby-kafka-0.3.16/lib/kafka/instrumenter.rb:21:in `instrument'
/var/lib/gems/2.1.0/gems/ruby-kafka-0.3.16/lib/kafka/produce_operation.rb:41:in `execute'
/var/lib/gems/2.1.0/gems/ruby-kafka-0.3.16/lib/kafka/producer.rb:301:in `block in deliver_messages_with_retries'
/var/lib/gems/2.1.0/gems/ruby-kafka-0.3.16/lib/kafka/producer.rb:293:in `loop'
/var/lib/gems/2.1.0/gems/ruby-kafka-0.3.16/lib/kafka/producer.rb:293:in `deliver_messages_with_retries'
/var/lib/gems/2.1.0/gems/ruby-kafka-0.3.16/lib/kafka/producer.rb:243:in `block in deliver_messages'
/var/lib/gems/2.1.0/gems/ruby-kafka-0.3.16/lib/kafka/instrumenter.rb:21:in `call'
/var/lib/gems/2.1.0/gems/ruby-kafka-0.3.16/lib/kafka/instrumenter.rb:21:in `instrument'
/var/lib/gems/2.1.0/gems/ruby-kafka-0.3.16/lib/kafka/producer.rb:236:in `deliver_messages'
/var/lib/gems/2.1.0/gems/fluent-plugin-kafka-0.5.3/lib/fluent/plugin/out_kafka_buffered.rb:252:in `block in write'
/var/lib/gems/2.1.0/gems/fluentd-0.12.32/lib/fluent/buffer.rb:123:in `each'
/var/lib/gems/2.1.0/gems/fluentd-0.12.32/lib/fluent/buffer.rb:123:in `block in msgpack_each'
/var/lib/gems/2.1.0/gems/fluentd-0.12.32/lib/fluent/plugin/buf_file.rb:71:in `open'
/var/lib/gems/2.1.0/gems/fluentd-0.12.32/lib/fluent/buffer.rb:120:in `msgpack_each'
/var/lib/gems/2.1.0/gems/fluent-plugin-kafka-0.5.3/lib/fluent/plugin/out_kafka_buffered.rb:224:in `write'
/var/lib/gems/2.1.0/gems/fluentd-0.12.32/lib/fluent/buffer.rb:354:in `write_chunk'
/var/lib/gems/2.1.0/gems/fluentd-0.12.32/lib/fluent/buffer.rb:333:in `pop'
/var/lib/gems/2.1.0/gems/fluentd-0.12.32/lib/fluent/output.rb:342:in `try_flush'
/var/lib/gems/2.1.0/gems/fluentd-0.12.32/lib/fluent/output.rb:149:in `run'```

**Comment by chris060986** [comment]
Another problem is, that the buffered output saves the message in buffer and try to send again when fluent is restarted. Is their any way to discard this messages?

**Comment by repeatedly** [comment]
Sorry for the delay.

> the plugin doesn't send any more messages after the error occurs.

It means error still happens until reached retry_limit or no error logs?

> Is their any way to discard this messages?

If you are using file buffer, removing files is enough.

**Comment by chris060986** [comment]
Yeah, removing file is enough, but not a solution for me because the system should be able to preceed without any action from my side.
Fluentd stops sending messages, after max retries... 
My expection was to drop the message and proceed with fthe next message.

**Comment by wyukawa** [comment]
Today, It happened to me.

If fluent-plugin-kafka has the following option like max_send_limit_bytes, it would be safe and nice.

If message size is too large(for example, more than 1MB), fluent-plugin-kafka drop the record and write to log file.
