### ISSUE TITLE
fluent-plugin-kafka 0.5.3 to kafka 2.11-0.10.2.0 failed

### ISSUE THREAD

**Issue by whaon** [fluent/fluent-plugin-kafka#123]
the version of fluent-plugin-kafka  is 0.5.3
the version of kafka is 2.11-0.10.2.0
but it's failed,it consfused me,pls give a hand,my config file is:
```
<match test.waf>
  @type kafka
  brokers 172.16.154.242:9092
  default_topic test2
</match>
```
and the error in log is:
```
2017-04-12 18:29:42 +0800 [warn]: Send exception occurred: Failed to send messages to test2/0
2017-04-12 18:29:42 +0800 [info]: initialized kafka producer: kafka
2017-04-12 18:29:42 +0800 [warn]: emit transaction failed: error_class=Kafka::DeliveryFailed error="Failed to send messages to test2/0" tag="test.waf"
  2017-04-12 18:29:42 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.17/lib/kafka/producer.rb:331:in `deliver_messages_with_retries'
  2017-04-12 18:29:42 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.17/lib/kafka/producer.rb:243:in `block in deliver_messages'
  2017-04-12 18:29:42 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.17/lib/kafka/instrumenter.rb:21:in `call'
  2017-04-12 18:29:42 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.17/lib/kafka/instrumenter.rb:21:in `instrument'
  2017-04-12 18:29:42 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.17/lib/kafka/producer.rb:236:in `deliver_messages'
  2017-04-12 18:29:42 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kafka-0.5.3/lib/fluent/plugin/out_kafka.rb:190:in `emit'
  2017-04-12 18:29:42 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/event_router.rb:90:in `emit_stream'
  2017-04-12 18:29:42 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_tail.rb:291:in `receive_lines'
  2017-04-12 18:29:42 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_tail.rb:401:in `call'
  2017-04-12 18:29:42 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_tail.rb:401:in `wrap_receive_lines'
  2017-04-12 18:29:42 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_tail.rb:596:in `call'
  2017-04-12 18:29:42 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_tail.rb:596:in `on_notify'
  2017-04-12 18:29:42 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_tail.rb:427:in `on_notify'
  2017-04-12 18:29:42 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_tail.rb:528:in `call'
  2017-04-12 18:29:42 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_tail.rb:528:in `on_change'
  2017-04-12 18:29:42 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.5/lib/cool.io/loop.rb:88:in `run_once'
  2017-04-12 18:29:42 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.5/lib/cool.io/loop.rb:88:in `run'
  2017-04-12 18:29:42 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_tail.rb:275:in `run'
```

**Comment by repeatedly** [comment]
I tested with fluent-plugin-kafka v0.5.3 and kafka_2.11-0.10.2.0 on my environment and there is no problem.
So the problem is your network or something.

**Comment by whaon** [comment]
It's ok now.
the config of kafka should be:
```
listeners=PLAINTEXT://172.16.154.242:9092
advertised.listeners=PLAINTEXT://172.16.154.242:9092
```
