### ISSUE TITLE
Receiving error_class="NoMethodError"

### ISSUE THREAD

**Issue by bhavikchitroda** [fluent/fluent-plugin-kafka#130]
Hi,
I am getting following error and unsure of whats wrong:

2017-05-24 16:53:31 +0000 [info]: initialized kafka producer: kafka
2017-05-24 16:53:31 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-05-24 16:53:31 +0000 error_class="NoMethodError" error="undefined method `producer' for nil:NilClass" plugin_id="object:3fb5a36faf98"
  2017-05-24 16:53:31 +0000 [warn]: /opt/td-agent-enterprise/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kafka-0.5.5/lib/fluent/plugin/out_kafka_buffered.rb:185:in `block in get_producer'
  2017-05-24 16:53:31 +0000 [warn]: /opt/td-agent-enterprise/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kafka-0.5.5/lib/fluent/plugin/out_kafka_buffered.rb:182:in `synchronize'
  2017-05-24 16:53:31 +0000 [warn]: /opt/td-agent-enterprise/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kafka-0.5.5/lib/fluent/plugin/out_kafka_buffered.rb:182:in `get_producer'
  2017-05-24 16:53:31 +0000 [warn]: /opt/td-agent-enterprise/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kafka-0.5.5/lib/fluent/plugin/out_kafka_buffered.rb:234:in `write'
  2017-05-24 16:53:31 +0000 [warn]: /opt/td-agent-enterprise/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.12.33/lib/fluent/buffer.rb:354:in `write_chunk'
  2017-05-24 16:53:31 +0000 [warn]: /opt/td-agent-enterprise/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.12.33/lib/fluent/buffer.rb:333:in `pop'
  2017-05-24 16:53:31 +0000 [warn]: /opt/td-agent-enterprise/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.12.33/lib/fluent/output.rb:342:in `try_flush'
  2017-05-24 16:53:31 +0000 [warn]: /opt/td-agent-enterprise/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.12.33/lib/fluent/output.rb:149:in `run'

Plugin and fluentd are both updated. Please help

**Comment by repeatedly** [comment]
Could you show me entire log?

**Comment by bhavikchitroda** [comment]
[2017-05-24 15:48:21 logs.txt](https://github.com/fluent/fluent-plugin-kafka/files/1029232/2017-05-24.15.48.21.logs.txt)

I have attached a part the log file, as the complete file is massive in size. It also contains the configuration. Thanks

**Comment by repeatedly** [comment]
Thanks.
I assume you have previous buffer files and plugin resumes it during startup phase.
I will check the race condition between kafka client initialization and buffer flush.
