### ISSUE TITLE
Plugin stop consuming after losing connection with Kafka

### ISSUE THREAD

**Issue by summer0nguyen** [fluent/fluent-plugin-kafka#138]
Hello,
I'm using fluentd-0.14.17 with fluent-plugin-kafka-0.5.5 . 
I have only single Kafka instance, and Here is my configuration : 

```
 <source>
    @type kafka
    topics "LWRaw.LOG_INSERT_MONEY"
    brokers "kafka:9092"
    offset_zookeeper "zookeeper:2181"
    offset_zk_root_node "/LWRaw"
  </source>
```

Everything works smoothly until kafka service has problem ( varies - but I tested by just stopping kafka )  , and we have to restart the process . 

But Fluent plugin never reconnected to Kafka , but raised the same error.

```
2017-07-11 03:19:49 +0000 [error]: #0 Connection error: EOFError
  2017-07-11 03:19:49 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.3.17/lib/kafka/connection.rb:99:in `rescue in send_request'
  2017-07-11 03:19:49 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.3.17/lib/kafka/connection.rb:79:in `send_request'
  2017-07-11 03:19:49 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.3.17/lib/kafka/broker.rb:40:in `fetch_messages'
  2017-07-11 03:19:49 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.3.17/lib/kafka/fetch_operation.rb:68:in `block in execute'
  2017-07-11 03:19:49 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.3.17/lib/kafka/fetch_operation.rb:59:in `each'
  2017-07-11 03:19:49 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.3.17/lib/kafka/fetch_operation.rb:59:in `flat_map'
  2017-07-11 03:19:49 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.3.17/lib/kafka/fetch_operation.rb:59:in `execute'
  2017-07-11 03:19:49 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.3.17/lib/kafka/client.rb:336:in `fetch_messages'
  2017-07-11 03:19:49 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.5.5/lib/fluent/plugin/in_kafka.rb:234:in `consume'
  2017-07-11 03:19:49 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.5.5/lib/fluent/plugin/in_kafka.rb:224:in `call'
  2017-07-11 03:19:49 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.5.5/lib/fluent/plugin/in_kafka.rb:224:in `on_timer'
  2017-07-11 03:19:49 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run_once'
  2017-07-11 03:19:49 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run'
  2017-07-11 03:19:49 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.5.5/lib/fluent/plugin/in_kafka.rb:193:in `run'
2017-07-11 03:19:49 +0000 [error]: #0 Could not connect to any of the seed brokers: kafka://kafka:9092
  2017-07-11 03:19:49 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.3.17/lib/kafka/cluster.rb:212:in `fetch_cluster_info'
  2017-07-11 03:19:49 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.3.17/lib/kafka/cluster.rb:181:in `cluster_info'
  2017-07-11 03:19:49 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.3.17/lib/kafka/cluster.rb:67:in `refresh_metadata!'
  2017-07-11 03:19:49 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.3.17/lib/kafka/cluster.rb:71:in `refresh_metadata_if_necessary!'
  2017-07-11 03:19:49 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.3.17/lib/kafka/fetch_operation.rb:45:in `execute'
  2017-07-11 03:19:49 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.3.17/lib/kafka/client.rb:336:in `fetch_messages'
  2017-07-11 03:19:49 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.5.5/lib/fluent/plugin/in_kafka.rb:234:in `consume'
  2017-07-11 03:19:49 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.5.5/lib/fluent/plugin/in_kafka.rb:224:in `call'
  2017-07-11 03:19:49 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.5.5/lib/fluent/plugin/in_kafka.rb:224:in `on_timer'
  2017-07-11 03:19:49 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run_once'
  2017-07-11 03:19:49 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run'
  2017-07-11 03:19:49 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.5.5/lib/fluent/plugin/in_kafka.rb:193:in `run'
2017-07-11 03:19:49 +0000 [error]: #0 Could not connect to any of the seed brokers: kafka://kafka:9092
  2017-07-11 03:19:49 +0000 [error]: #0 suppressed same stacktrace
2017-07-11 03:19:50 +0000 [error]: #0 Could not connect to any of the seed brokers: kafka://kafka:9092
  2017-07-11 03:19:50 +0000 [error]: #0 suppressed same stacktrace

```

I expect that the plugin would reconnect to kafka after kafka started . 
Do you have any idea ? 
Thank you

**Comment by summer0nguyen** [comment]
Hello,
Do you guys have any solutions ? Thank you

**Comment by repeatedly** [comment]
I tested your configuration and it works.
So the problem seems to not fluent-plugin-kafka.

- log

```
2017-07-19 06:09:10 +0900 [info]: #0 fluentd worker is now running worker=0
2017-07-19 06:09:16.227658000 +0900 kafka..test138: {"message":"bar"}
2017-07-19 06:09:26 +0900 [error]: #0 Connection error: EOFError
  2017-07-19 06:09:26 +0900 [error]: #0 /Users/repeatedly/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.3.17/lib/kafka/connection.rb:99:in `rescue in send_request'
  2017-07-19 06:09:26 +0900 [error]: #0 /Users/repeatedly/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.3.17/lib/kafka/connection.rb:79:in `send_request'
  2017-07-19 06:09:26 +0900 [error]: #0 /Users/repeatedly/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.3.17/lib/kafka/broker.rb:40:in `fetch_messages'
  2017-07-19 06:09:26 +0900 [error]: #0 /Users/repeatedly/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.3.17/lib/kafka/fetch_operation.rb:68:in `block in execute'
  2017-07-19 06:09:26 +0900 [error]: #0 /Users/repeatedly/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.3.17/lib/kafka/fetch_operation.rb:59:in `each'
  2017-07-19 06:09:26 +0900 [error]: #0 /Users/repeatedly/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.3.17/lib/kafka/fetch_operation.rb:59:in `flat_map'
  2017-07-19 06:09:26 +0900 [error]: #0 /Users/repeatedly/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.3.17/lib/kafka/fetch_operation.rb:59:in `execute'
  2017-07-19 06:09:26 +0900 [error]: #0 /Users/repeatedly/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.3.17/lib/kafka/client.rb:336:in `fetch_messages'
  2017-07-19 06:09:26 +0900 [error]: #0 /Users/repeatedly/dev/fluentd/fluent-plugin-kafka/lib/fluent/plugin/in_kafka.rb:234:in `consume'
  2017-07-19 06:09:26 +0900 [error]: #0 /Users/repeatedly/dev/fluentd/fluent-plugin-kafka/lib/fluent/plugin/in_kafka.rb:224:in `call'
  2017-07-19 06:09:26 +0900 [error]: #0 /Users/repeatedly/dev/fluentd/fluent-plugin-kafka/lib/fluent/plugin/in_kafka.rb:224:in `on_timer'
  2017-07-19 06:09:26 +0900 [error]: #0 /Users/repeatedly/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run_once'
  2017-07-19 06:09:26 +0900 [error]: #0 /Users/repeatedly/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run'
  2017-07-19 06:09:26 +0900 [error]: #0 /Users/repeatedly/dev/fluentd/fluent-plugin-kafka/lib/fluent/plugin/in_kafka.rb:193:in `run'
2017-07-19 06:09:27 +0900 [error]: #0 Could not connect to any of the seed brokers: kafka://localhost:9092
  2017-07-19 06:09:27 +0900 [error]: #0 /Users/repeatedly/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.3.17/lib/kafka/cluster.rb:212:in `fetch_cluster_info'
  2017-07-19 06:09:27 +0900 [error]: #0 /Users/repeatedly/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.3.17/lib/kafka/cluster.rb:181:in `cluster_info'
  2017-07-19 06:09:27 +0900 [error]: #0 /Users/repeatedly/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.3.17/lib/kafka/cluster.rb:67:in `refresh_metadata!'
  2017-07-19 06:09:27 +0900 [error]: #0 /Users/repeatedly/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.3.17/lib/kafka/cluster.rb:71:in `refresh_metadata_if_necessary!'
  2017-07-19 06:09:27 +0900 [error]: #0 /Users/repeatedly/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.3.17/lib/kafka/fetch_operation.rb:45:in `execute'
  2017-07-19 06:09:27 +0900 [error]: #0 /Users/repeatedly/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.3.17/lib/kafka/client.rb:336:in `fetch_messages'
  2017-07-19 06:09:27 +0900 [error]: #0 /Users/repeatedly/dev/fluentd/fluent-plugin-kafka/lib/fluent/plugin/in_kafka.rb:234:in `consume'
  2017-07-19 06:09:27 +0900 [error]: #0 /Users/repeatedly/dev/fluentd/fluent-plugin-kafka/lib/fluent/plugin/in_kafka.rb:224:in `call'
  2017-07-19 06:09:27 +0900 [error]: #0 /Users/repeatedly/dev/fluentd/fluent-plugin-kafka/lib/fluent/plugin/in_kafka.rb:224:in `on_timer'
  2017-07-19 06:09:27 +0900 [error]: #0 /Users/repeatedly/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run_once'
  2017-07-19 06:09:27 +0900 [error]: #0 /Users/repeatedly/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run'
  2017-07-19 06:09:27 +0900 [error]: #0 /Users/repeatedly/dev/fluentd/fluent-plugin-kafka/lib/fluent/plugin/in_kafka.rb:193:in `run'
2017-07-19 06:09:28 +0900 [error]: #0 Could not connect to any of the seed brokers: kafka://localhost:9092
  2017-07-19 06:09:28 +0900 [error]: #0 suppressed same stacktrace
2017-07-19 06:09:29 +0900 [error]: #0 Could not connect to any of the seed brokers: kafka://localhost:9092
  2017-07-19 06:09:29 +0900 [error]: #0 suppressed same stacktrace
2017-07-19 06:09:30 +0900 [error]: #0 Could not connect to any of the seed brokers: kafka://localhost:9092
  2017-07-19 06:09:30 +0900 [error]: #0 suppressed same stacktrace
2017-07-19 06:09:31 +0900 [error]: #0 Could not connect to any of the seed brokers: kafka://localhost:9092
  2017-07-19 06:09:31 +0900 [error]: #0 suppressed same stacktrace
2017-07-19 06:09:32 +0900 [error]: #0 Could not connect to any of the seed brokers: kafka://localhost:9092
  2017-07-19 06:09:32 +0900 [error]: #0 suppressed same stacktrace
2017-07-19 06:09:33 +0900 [error]: #0 Could not connect to any of the seed brokers: kafka://localhost:9092
  2017-07-19 06:09:33 +0900 [error]: #0 suppressed same stacktrace
2017-07-19 06:09:47.241968000 +0900 kafka..test138: {"message":"baz"}
```

- command

```
% bin/kafka-console-producer.sh --broker-list localhost:9092 --topic test138
bar
# shutdown kafka
% bin/kafka-console-producer.sh --broker-list localhost:9092 --topic test138
baz
```

**Comment by summer0nguyen** [comment]
Thank you for your response . 
Let me recheck and let you know about it.

**Comment by summer0nguyen** [comment]
Hi @repeatedly ,
it turns out that Kafka was running in a Docker Container under supervisord with the port exposed. 
When I kill the process in the Docker Container , the service stop running , but Docker Proxy Port is still open . That's why fluent kafka can not recognize the down service. 
I stop using Docker Container for this Kafka  right now.

**Comment by repeatedly** [comment]
if the problem happens without docker proxy port, please reopen the issue.

**Comment by davidwtf** [comment]
I meet the same problem:  fluentd will not auto reconnect kafka when kafka is temporarily offline and recovered.

I'm using kafka group input plugin.
The configs are here:
```
 <source>
      @type kafka_group
      brokers kafka1.local:9092
      topics "#{ENV['KAFKA_TOPICS']}"
      consumer_group "#{ENV['KAFKA_CONSUMER_GROUP']}"
      start_from_beginning false
      format json
      ssl_ca_cert /fluentd/etc/ca.crt
      ssl_client_cert /fluentd/etc/client.crt
      ssl_client_cert_key /fluentd/etc/client.key
      add_prefix kafka
      max_wait_time 5
 </source>
```
The logs are here:
```
2018-04-18 23:29:22 +0000 [error]: #0 unexpected error during consuming events from kafka. Re-fetch events. error="Failed to find group coordinator"
  2018-04-18 23:29:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/cluster.rb:136:in `get_group_coordinator'
  2018-04-18 23:29:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/consumer_group.rb:179:in `coordinator'
  2018-04-18 23:29:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/consumer_group.rb:120:in `block in join_group'
  2018-04-18 23:29:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/instrumenter.rb:21:in `instrument'
  2018-04-18 23:29:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/instrumenter.rb:33:in `instrument'
  2018-04-18 23:29:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/consumer_group.rb:119:in `join_group'
  2018-04-18 23:29:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/consumer_group.rb:41:in `join'
  2018-04-18 23:29:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/consumer.rb:420:in `join_group'
  2018-04-18 23:29:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/consumer.rb:376:in `rescue in consumer_loop'
  2018-04-18 23:29:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/consumer.rb:373:in `consumer_loop'
  2018-04-18 23:29:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/consumer.rb:284:in `each_batch'
  2018-04-18 23:29:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-kafka-0.6.6/lib/fluent/plugin/in_kafka_group.rb:187:in `run'
2018-04-18 23:29:22 +0000 [warn]: #0 Stopping Consumer
2018-04-18 23:29:22 +0000 [warn]: #0 Could not connect to broker. Next retry will be in 30 seconds
2018-04-18 23:30:02 +0000 [error]: #0 unexpected error during re-starting consumer object access error="Could not connect to any of the seed brokers:\n- kafka://kafka1.local:9092: Operation timed out"
  2018-04-18 23:30:02 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/cluster.rb:292:in `fetch_cluster_info'
  2018-04-18 23:30:02 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/cluster.rb:252:in `cluster_info'
  2018-04-18 23:30:02 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/cluster.rb:82:in `refresh_metadata!'
  2018-04-18 23:30:02 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/cluster.rb:48:in `add_target_topics'
  2018-04-18 23:30:02 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/consumer_group.rb:25:in `subscribe'
  2018-04-18 23:30:02 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/consumer.rb:94:in `subscribe'
  2018-04-18 23:30:02 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-kafka-0.6.6/lib/fluent/plugin/in_kafka_group.rb:165:in `block in setup_consumer'
  2018-04-18 23:30:02 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-kafka-0.6.6/lib/fluent/plugin/in_kafka_group.rb:164:in `each'
  2018-04-18 23:30:02 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-kafka-0.6.6/lib/fluent/plugin/in_kafka_group.rb:164:in `setup_consumer'
  2018-04-18 23:30:02 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-kafka-0.6.6/lib/fluent/plugin/in_kafka_group.rb:177:in `reconnect_consumer'
  2018-04-18 23:30:02 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-kafka-0.6.6/lib/fluent/plugin/in_kafka_group.rb:223:in `rescue in run'
  2018-04-18 23:30:02 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-kafka-0.6.6/lib/fluent/plugin/in_kafka_group.rb:186:in `run'
```


After reading the source code, I found there may be a bug about reconnecting.
The **run** method need **`@consumer`** must not nil，or it will exit the loop. But in method **reconnect_consumer** if there's error when calling **setup_consumer**，the **`@consumer`** will be nil and  the **run** method will exit. This produces the logs above.
