### ISSUE TITLE
The latest code is not compatible with ruby-kafka 0.4.1

### ISSUE THREAD

**Issue by shafreeck** [fluent/fluent-plugin-kafka#149]
The ruby-kafka v0.4.1 PendingMessage class need 6 arguments now which we pass 7

https://github.com/zendesk/ruby-kafka/blob/v0.4.1/lib/kafka/pending_message.rb

This may cause error:
```
2017-08-29 06:13:51 +0000 [warn]: Exception Backtrace : /var/lib/gems/2.3.0/gems/ruby-kafka-0.4.1/lib/kafka/pending_message.rb:5:in `initialize'
/var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.6.0/lib/fluent/plugin/kafka_producer_ext.rb:16:in `new'
/var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.6.0/lib/fluent/plugin/kafka_producer_ext.rb:16:in `produce2'
/var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.6.0/lib/fluent/plugin/out_kafka_buffered.rb:301:in `block in write'
/var/lib/gems/2.3.0/gems/fluentd-0.12.33/lib/fluent/buffer.rb:123:in `each'
/var/lib/gems/2.3.0/gems/fluentd-0.12.33/lib/fluent/buffer.rb:123:in `block in msgpack_each'
/var/lib/gems/2.3.0/gems/fluentd-0.12.33/lib/fluent/plugin/buf_file.rb:71:in `open'
/var/lib/gems/2.3.0/gems/fluentd-0.12.33/lib/fluent/buffer.rb:120:in `msgpack_each'
/var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.6.0/lib/fluent/plugin/out_kafka_buffered.rb:263:in `write'
/var/lib/gems/2.3.0/gems/fluentd-0.12.33/lib/fluent/buffer.rb:354:in `write_chunk'
/var/lib/gems/2.3.0/gems/fluentd-0.12.33/lib/fluent/buffer.rb:333:in `pop'
/var/lib/gems/2.3.0/gems/fluentd-0.12.33/lib/fluent/output.rb:342:in `try_flush'
/var/lib/gems/2.3.0/gems/fluentd-0.12.33/lib/fluent/output.rb:149:in `run'
2017-08-29 06:13:51 +0000 [info]: initialized kafka producer: kafka
```

**Comment by repeatedly** [comment]
Release v0.6.1 with this fix. Thanks for the report!
