### ISSUE TITLE
Use ltsv format content topics, and use_record_time=true occured parse exception.

### ISSUE THREAD

**Issue by kimutansk** [fluent/fluent-plugin-kafka#159]
Hi,

I am seeing following exception in case we use consumer ltsv format.

> 2017-11-01 09:30:11 +0900 [warn]: parser error in target_topics01/1 error="value must be string: " value="method:GET\turi:/ranking?pageSize=10\tprotocol:HTTP/1.1\tstatus:200\tsize:22573\treqtime:0.116\tlanguage:-\tsession:-\tscheme:http\thostname:test-api-dev\ttime:2017-11-01T09:19:28+09:00" offset=637339
>   2017-11-01 09:30:11 +0900 [debug]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/parser.rb:82:in `parse'
>   2017-11-01 09:30:11 +0900 [debug]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kafka-0.5.5/lib/fluent/plugin/in_kafka_group.rb:168:in `block (2 levels) in run'
>   2017-11-01 09:30:11 +0900 [debug]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kafka-0.5.5/lib/fluent/plugin/in_kafka_group.rb:163:in `each'
>   2017-11-01 09:30:11 +0900 [debug]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kafka-0.5.5/lib/fluent/plugin/in_kafka_group.rb:163:in `block in run'
>   2017-11-01 09:30:11 +0900 [debug]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.17/lib/kafka/consumer.rb:251:in `block (3 levels) in each_batch'
>   2017-11-01 09:30:11 +0900 [debug]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.17/lib/kafka/instrumenter.rb:21:in `call'
>   2017-11-01 09:30:11 +0900 [debug]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.17/lib/kafka/instrumenter.rb:21:in `instrument'
>   2017-11-01 09:30:11 +0900 [debug]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.17/lib/kafka/instrumenter.rb:33:in `instrument'
>   2017-11-01 09:30:11 +0900 [debug]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.17/lib/kafka/consumer.rb:241:in `block (2 levels) in each_batch'
>   2017-11-01 09:30:11 +0900 [debug]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.17/lib/kafka/consumer.rb:239:in `each'
>   2017-11-01 09:30:11 +0900 [debug]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.17/lib/kafka/consumer.rb:239:in `block in each_batch'
>   2017-11-01 09:30:11 +0900 [debug]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.17/lib/kafka/consumer.rb:282:in `consumer_loop'
>   2017-11-01 09:30:11 +0900 [debug]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.17/lib/kafka/consumer.rb:236:in `each_batch'
>   2017-11-01 09:30:11 +0900 [debug]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kafka-0.5.5/lib/fluent/plugin/in_kafka_group.rb:157:in `run'

It seems LTSV parsed result record's keys are symbol, not string.
My understanding, fluentd record's keys format are string, not symbol.

Here is PR https://github.com/fluent/fluent-plugin-kafka/pull/158

**Comment by kimutansk** [comment]
Thanks for quick response!
