### ISSUE TITLE
secondary support

### ISSUE THREAD

**Issue by jacoelho** [fluent/fluent-plugin-kafka#174]
agent: td-agent-2.3.6-0.el7.x86_64
os: centos7

trying to use secondary with kafka output: 

```
<match **>
  @type kafka_buffered
  brokers <redacted>
  topic <redacted>
  retry_limit 2
  
  <secondary>
    @type file
    path /var/log/td-agent/failure
  </secondary>
</match>
```

dry-run complains about: 

```
2018-01-11 14:21:41 +0000 [warn]: secondary type should be same with primary one primary="Fluent::KafkaOutputBuffered" secondary="Fluent::Plugin::FileOutput"
```

Expected:
After retry_limit is reached a new file is created

Actual Behaviour:
Dropped chunks.

**Comment by gabfl** [comment]
I believe this is not an issue related to `fluent-plugin-kafka`, you should consider filing it in the main project https://github.com/fluent/fluentd instead

**Comment by repeatedly** [comment]
I can't reproduce this problem. With above config, secondary works.

```
2018-01-17 04:03:15 +0900 [info]: initialized kafka producer: kafka
2018-01-17 04:03:15 +0900 [warn]: failed to flush the buffer. error_class="Kafka::ConnectionError" error="Could not connect to any of the seed brokers:\n- kafka://localhost:9092: Connection refused - connect(2) for [::1]:9092" plugin_id="object:3fd83d12fb9c"
2018-01-17 04:03:15 +0900 [warn]: retry count exceededs limit. falling back to secondary output.
  2018-01-17 04:03:15 +0900 [warn]: /Users/repeatedly/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.1/lib/kafka/cluster.rb:286:in `fetch_cluster_info'
  2018-01-17 04:03:15 +0900 [warn]: /Users/repeatedly/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.1/lib/kafka/cluster.rb:246:in `cluster_info'
  2018-01-17 04:03:15 +0900 [warn]: /Users/repeatedly/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.1/lib/kafka/cluster.rb:82:in `refresh_metadata!'
  2018-01-17 04:03:15 +0900 [warn]: /Users/repeatedly/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.1/lib/kafka/cluster.rb:48:in `add_target_topics'
  2018-01-17 04:03:15 +0900 [warn]: /Users/repeatedly/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.1/lib/kafka/producer.rb:279:in `deliver_messages_with_retries'
  2018-01-17 04:03:15 +0900 [warn]: /Users/repeatedly/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.1/lib/kafka/producer.rb:241:in `block in deliver_messages'
  2018-01-17 04:03:15 +0900 [warn]: /Users/repeatedly/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.1/lib/kafka/instrumenter.rb:21:in `instrument'
  2018-01-17 04:03:15 +0900 [warn]: /Users/repeatedly/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.1/lib/kafka/producer.rb:234:in `deliver_messages'
  2018-01-17 04:03:15 +0900 [warn]: /Users/repeatedly/dev/fluentd/fluent-plugin-kafka/lib/fluent/plugin/out_kafka_buffered.rb:267:in `deliver_messages'
  2018-01-17 04:03:15 +0900 [warn]: /Users/repeatedly/dev/fluentd/fluent-plugin-kafka/lib/fluent/plugin/out_kafka_buffered.rb:330:in `write'
  2018-01-17 04:03:15 +0900 [warn]: /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/buffer.rb:354:in `write_chunk'
  2018-01-17 04:03:15 +0900 [warn]: /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/buffer.rb:333:in `pop'
  2018-01-17 04:03:15 +0900 [warn]: /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/output.rb:342:in `try_flush'
  2018-01-17 04:03:15 +0900 [warn]: /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/output.rb:149:in `run'
2018-01-17 04:03:17 +0900 [warn]: retry succeeded. plugin_id="object:3fd83d12fb9c"
```

**Comment by jacoelho** [comment]
full log:
https://gist.github.com/jacoelho/b220922fa74fb776b3a969770e36a8cc

directory is writable:
```
ls -la /var/log/td-agent/failed/
total 8
drwxr-xr-x 2 td-agent td-agent 4096 Jan 15 09:48 .
drwxr-xr-x 4 td-agent td-agent 4096 Jan 17 10:11 ..
```
