### ISSUE TITLE
td-agent has been sending messages to localhost:9092

### ISSUE THREAD

**Issue by zhaominmail** [fluent/fluent-plugin-kafka#188]
hi:
fluentd version:              1.0.2
kafka version:                kafka_2.10-0.10.2.0
fluent-plugin-kafka version:  0.7.2
ruby-kafka version:           0.5.3

td-agent node:  192.168.8.241
kafka node:     192.168.8.153

td-agent.conf
    <source>
      @type tail
      @id nbdec_log
      @label @tdtest
      path /usr/local/nginx/logs/host.access.log
      pos_file /usr/local/nginx/logs/host.access.log.posg
      tag nbdec.log
      <parse>
        @type json
      </parse>
    </source>
    
    
    <label @tdtest>
      <match nbdec.log>
            @type kafka_buffered
            brokers 192.168.8.153:9092
            flush_interval 3s
            default_topic test
            get_kafka_client_log true
      </match>
    </label>

error log : 
2018-03-14 17:30:22 +0800 [info]: #0 New topics added to target list: test
2018-03-14 17:30:22 +0800 [info]: #0 Fetching cluster metadata from kafka://192.168.8.153:9092
2018-03-14 17:30:22 +0800 [info]: #0 Discovered cluster metadata; nodes: localhost:9092 (node_id=0)
2018-03-14 17:30:22 +0800 [info]: #0 Sending 1 messages to localhost:9092 (node_id=0)
2018-03-14 17:30:22 +0800 [error]: #0 Failed to connect to localhost:9092: Connection refused - connect(2) for [::1]:9092
2018-03-14 17:30:22 +0800 [error]: #0 Could not connect to broker localhost:9092 (node_id=0): Connection refused - connect(2) for [::1]:9092
2018-03-14 17:30:22 +0800 [warn]: #0 Failed to send all messages; attempting retry 1 of 2 after 1s
2018-03-14 17:30:23 +0800 [info]: #0 Fetching cluster metadata from kafka://192.168.8.153:9092
2018-03-14 17:30:23 +0800 [info]: #0 Discovered cluster metadata; nodes: localhost:9092 (node_id=0)
2018-03-14 17:30:23 +0800 [info]: #0 Sending 1 messages to localhost:9092 (node_id=0)
2018-03-14 17:30:23 +0800 [error]: #0 Failed to connect to localhost:9092: Connection refused - connect(2) for [::1]:9092
2018-03-14 17:30:23 +0800 [error]: #0 Could not connect to broker localhost:9092 (node_id=0): Connection refused - connect(2) for [::1]:9092
2018-03-14 17:30:23 +0800 [warn]: #0 Failed to send all messages; attempting retry 2 of 2 after 1s
2018-03-14 17:30:24 +0800 [info]: #0 Fetching cluster metadata from kafka://192.168.8.153:9092
2018-03-14 17:30:24 +0800 [info]: #0 Discovered cluster metadata; nodes: localhost:9092 (node_id=0)
2018-03-14 17:30:24 +0800 [info]: #0 Sending 1 messages to localhost:9092 (node_id=0)
2018-03-14 17:30:24 +0800 [error]: #0 Failed to connect to localhost:9092: Connection refused - connect(2) for [::1]:9092
2018-03-14 17:30:24 +0800 [error]: #0 Could not connect to broker localhost:9092 (node_id=0): Connection refused - connect(2) for [::1]:9092
2018-03-14 17:30:24 +0800 [error]: #0 Failed to send all messages; keeping remaining messages in buffer
2018-03-14 17:30:24 +0800 [warn]: #0 Send exception occurred: Failed to send messages to test/0
2018-03-14 17:30:24 +0800 [warn]: #0 Exception Backtrace : /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.3/lib/kafka/producer.rb:328:in `deliver_messages_with_retries'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.3/lib/kafka/producer.rb:236:in `block in deliver_messages'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.3/lib/kafka/instrumenter.rb:21:in `instrument'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.3/lib/kafka/producer.rb:229:in `deliver_messages'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kafka-0.7.2/lib/fluent/plugin/out_kafka_buffered.rb:277:in `deliver_messages'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kafka-0.7.2/lib/fluent/plugin/out_kafka_buffered.rb:340:in `write'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/compat/output.rb:131:in `write'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:1093:in `try_flush'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:1318:in `flush_thread_run'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:439:in `block (2 levels) in start'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-03-14 17:30:24 +0800 [info]: #0 Disconnecting broker 0
2018-03-14 17:30:24 +0800 [info]: #0 initialized kafka producer: kafka
2018-03-14 17:30:24 +0800 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-03-14 17:30:25 +0800 chunk="5675c05fa53412652de8c52a03780298" error_class=Kafka::DeliveryFailed error="Failed to send messages to test/0"
  2018-03-14 17:30:24 +0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.3/lib/kafka/producer.rb:328:in `deliver_messages_with_retries'
  2018-03-14 17:30:24 +0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.3/lib/kafka/producer.rb:236:in `block in deliver_messages'
  2018-03-14 17:30:24 +0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.3/lib/kafka/instrumenter.rb:21:in `instrument'
  2018-03-14 17:30:24 +0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.3/lib/kafka/producer.rb:229:in `deliver_messages'
  2018-03-14 17:30:24 +0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kafka-0.7.2/lib/fluent/plugin/out_kafka_buffered.rb:277:in `deliver_messages'
  2018-03-14 17:30:24 +0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kafka-0.7.2/lib/fluent/plugin/out_kafka_buffered.rb:340:in `write'
  2018-03-14 17:30:24 +0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/compat/output.rb:131:in `write'
  2018-03-14 17:30:24 +0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:1093:in `try_flush'
  2018-03-14 17:30:24 +0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:1318:in `flush_thread_run'
  2018-03-14 17:30:24 +0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:439:in `block (2 levels) in start'
  2018-03-14 17:30:24 +0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'

Somehow, the brokers of the td-agent configuration is 192.168.8.153:9092, but when the send disappears is the localhost:9092?
I have tested, starting Kafka locally, can send success, no problem.

**Comment by repeatedly** [comment]
> Somehow, the brokers of the td-agent configuration is 192.168.8.153:9092, but when the send disappears is the localhost:9092?

I'm not sure becuase it depends on your cluster setup.
`brokers` parameter is used for getting cluster metadata and your cluster returns `localhost:9092` for topics to ruby-kafka.
So fluent-plugin-kafka(ruby-kafka) tries to insert logs to `localhost:9092`.

> [::1]:9092

If your insertion in the local environment is succeeded with same configuration, IPv6/IPv4 mismatch is one possible cause.

**Comment by zhaominmail** [comment]
tks，kafka is local model， one node。 kafka server.properties config is default。 It has been solved.
