### ISSUE TITLE
Cannot auto reconnect kafka

### ISSUE THREAD

**Issue by davidwtf** [fluent/fluent-plugin-kafka#192]
I meet a problem: fluentd will not auto reconnect kafka when kafka is temporarily offline and recovered.

I'm using kafka group input plugin.

The configs are here:
```
 <source>
      @type kafka_group
      brokers kafka1.local:9092
      topics "#{ENV['KAFKA_TOPICS']}"
      consumer_group "#{ENV['KAFKA_CONSUMER_GROUP']}"
      start_from_beginning false
      format json
      ssl_ca_cert /fluentd/etc/ca.crt
      ssl_client_cert /fluentd/etc/client.crt
      ssl_client_cert_key /fluentd/etc/client.key
      add_prefix kafka
      max_wait_time 5
 </source>
```
The logs are here:
```
2018-04-18 23:29:22 +0000 [error]: #0 unexpected error during consuming events from kafka. Re-fetch events. error="Failed to find group coordinator"
  2018-04-18 23:29:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/cluster.rb:136:in `get_group_coordinator'
  2018-04-18 23:29:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/consumer_group.rb:179:in `coordinator'
  2018-04-18 23:29:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/consumer_group.rb:120:in `block in join_group'
  2018-04-18 23:29:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/instrumenter.rb:21:in `instrument'
  2018-04-18 23:29:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/instrumenter.rb:33:in `instrument'
  2018-04-18 23:29:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/consumer_group.rb:119:in `join_group'
  2018-04-18 23:29:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/consumer_group.rb:41:in `join'
  2018-04-18 23:29:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/consumer.rb:420:in `join_group'
  2018-04-18 23:29:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/consumer.rb:376:in `rescue in consumer_loop'
  2018-04-18 23:29:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/consumer.rb:373:in `consumer_loop'
  2018-04-18 23:29:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/consumer.rb:284:in `each_batch'
  2018-04-18 23:29:22 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-kafka-0.6.6/lib/fluent/plugin/in_kafka_group.rb:187:in `run'
2018-04-18 23:29:22 +0000 [warn]: #0 Stopping Consumer
2018-04-18 23:29:22 +0000 [warn]: #0 Could not connect to broker. Next retry will be in 30 seconds
2018-04-18 23:30:02 +0000 [error]: #0 unexpected error during re-starting consumer object access error="Could not connect to any of the seed brokers:\n- kafka://kafka1.local:9092: Operation timed out"
  2018-04-18 23:30:02 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/cluster.rb:292:in `fetch_cluster_info'
  2018-04-18 23:30:02 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/cluster.rb:252:in `cluster_info'
  2018-04-18 23:30:02 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/cluster.rb:82:in `refresh_metadata!'
  2018-04-18 23:30:02 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/cluster.rb:48:in `add_target_topics'
  2018-04-18 23:30:02 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/consumer_group.rb:25:in `subscribe'
  2018-04-18 23:30:02 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/consumer.rb:94:in `subscribe'
  2018-04-18 23:30:02 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-kafka-0.6.6/lib/fluent/plugin/in_kafka_group.rb:165:in `block in setup_consumer'
  2018-04-18 23:30:02 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-kafka-0.6.6/lib/fluent/plugin/in_kafka_group.rb:164:in `each'
  2018-04-18 23:30:02 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-kafka-0.6.6/lib/fluent/plugin/in_kafka_group.rb:164:in `setup_consumer'
  2018-04-18 23:30:02 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-kafka-0.6.6/lib/fluent/plugin/in_kafka_group.rb:177:in `reconnect_consumer'
  2018-04-18 23:30:02 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-kafka-0.6.6/lib/fluent/plugin/in_kafka_group.rb:223:in `rescue in run'
  2018-04-18 23:30:02 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-kafka-0.6.6/lib/fluent/plugin/in_kafka_group.rb:186:in `run'
```

After reading the source code, I found there may be a bug about reconnecting.
The **run** method need **`@consumer`** must not nil，or it will exit the loop. But in method **reconnect_consumer**, if there's an error when calling **setup_consumer**，the **`@consumer`** will be nil and the run method will exit. This produces the logs above.

**Comment by cosmo0920** [comment]
https://github.com/fluent/fluent-plugin-kafka/pull/204 is merged.
I'm closing this for now.
Please reopen or add comment here if you encounter same problem.
