### ISSUE TITLE
Getting "Skip broken event" errors with record=nil

### ISSUE THREAD

**Issue by jonmoter** [fluent/fluent-plugin-kafka#193]
* Fluentd version: 1.2.0
* Plugin version: 0.7.2
* Environment: Kubernetes cluster

I'm seeing a whole bunch of errors like this on one of my hosts (JSON formatted for readability):

```
{  
   "time":"2018-05-01 15:09:48 +0000",
   "level":"warn",
   "message":"[out_kafka] unexpected error during format record. Skip broken event: error=\"undefined method `[]=' for nil:NilClass\" error_class=\"NoMethodError\" time=34 record=nil",
   "worker_id":0
}
```

I know the warning is coming from this chunk of code:

https://github.com/fluent/fluent-plugin-kafka/blob/7931b45df2c37aa892fb8d192ff32d3ddbb6224b/lib/fluent/plugin/out_kafka_buffered.rb#L319-L322

And apparently `record=nil` in that block. But for the life of me, I can't figure out why `chunk.msgpack_each` would get called with `nil` records.  And I don't have much of an intuition on how to debug this.

This is not happening across the board.  Most logs are getting processed fine.  But one of the hosts is spitting out tens of thousands of those errors.

The relevant parts of my config look like this.  (The total config is larger, like the label sending metrics to datadog, but I don't think it's relevant to this issue):

```
<source>
  @type tail
  path /var/log/containers/*.log
  pos_file /var/log/pod.position
  tag kubernetes.pod.*
  format json
  time_key time
  time_format %Y-%m-%dT%H:%M:%S.%NZ
  read_from_head true
  keep_time_key true
</source>

<filter kubernetes.pod.**.log>
  @type kubernetes_metadata
</filter>

<match kubernetes.pod.**.log>
  @type copy

  # Send the events to Kafka
  <store>
    @type relabel
    @label @kafka_output
  </store>

  # Re-emit each event to be processed in datadog_metrics.conf
  <store>
    @type relabel
    @label @datadog_metrics
  </store>
</match>

<label @kafka_output>
  <match **>
    @type kafka_buffered
    @id out_kafka

    brokers "#{ENV['FLUENT_KAFKA_BROKERS']}"

    topic_key kafka_topic
    default_topic fluent.k8s.pods
    output_include_time true
    get_kafka_client_log "#{ENV['ENABLE_KAFKA_CLIENT_LOGS'] ? 'true' : 'false'}"

    # ruby-kafka producer options
    max_send_retries 10
    required_acks 1
    ack_timeout 10
    compression_codec lz4

    # Copied from embeddables, at the suggestion of Tim Schroeder
    # https://docs.fluentd.org/v1.0/articles/buffer-section#parameters
    <buffer>
      @type memory
      chunk_limit_size 64m
      chunk_limit_records 128
      flush_interval 5s
      flush_thread_count 4
    </buffer>
  </match>
</label>
```

I saw this [this comment on another issue](https://github.com/fluent/fluentd/issues/1248#issuecomment-300206256) implied they saw similar errors when they were using disk buffers, and their disk filled up. But since I'm using memory buffers, that doesn't seem relevant.

**Comment by repeatedly** [comment]
Do you use only tail plugin for input or use other input plugins?

**Comment by bathizte** [comment]
Hello,

I also get these errors using a "forward" source and outputing to "kafka_buffered". 
Fluent version 0.14.25
fluent-plugin-kafka-0.6.4

**Comment by cmachgodaddy** [comment]
Anybody has any idea to solve this problem? We're running into the same issue

**Comment by damobrisbane** [comment]
Can this be re-opened? When it happens get 1000's of info level messages put into the fluentd log file, impacting more things than it should and it's hard to replicate as there is no information in the log as to the source of the error - where the message has come from. In my case occurring inside the rescue block in out_kafka2.rb? 

This is the rescue block

```
  begin
    record = inject_values_to_record(tag, time, record)
    record.delete(@topic_key) if @exclude_topic_key
    partition_key = (@exclude_partition_key ? record.delete(@partition_key_key) : record[@partition_key_key]) || @default_partition_key
    partition = (@exclude_partition ? record.delete(@partition_key) : record[@partition_key]) || @default_partition
    message_key = (@exclude_message_key ? record.delete(@message_key_key) : record[@message_key_key]) || @default_message_key

    if mutate_headers
      ...
    end

    unless @exclude_fields.empty?
      ...
    end

    record_buf = @formatter_proc.call(tag, time, record)
    record_buf_bytes = record_buf.bytesize
    if @max_send_limit_bytes && record_buf_bytes > @max_send_limit_bytes
      ...
    end
  rescue StandardError => e
    log.warn "unexpected error during format record. Skip broken event:", :error => e.to_s, :error_class => e.class.to_s, :time => time, :record => record
    next
  end

```

Stacktrace (fails on first method, _inject_values_to_record_):


```
2022-01-11 06:32:41 +1100 [warn]: got unrecoverable error in primary and no secondary error_class=NoMethodError error="undefined method `[]=' for nil:NilClass"
```
```
  2022-01-11 06:32:41 +1100 [warn]: /usr/lib64/ruby/gems/2.6.0/gems/fluentd-1.14.2/lib/fluent/plugin_helper/inject.rb:39:in `inject_values_to_record'
  2022-01-11 06:32:41 +1100 [warn]: /usr/local/lib64/ruby/gems/2.6.0/gems/fluent-plugin-kafka-0.17.3/lib/fluent/plugin/out_kafka2.rb:247:in `block in write'
  2022-01-11 06:32:41 +1100 [warn]: /usr/lib64/ruby/gems/2.6.0/gems/fluentd-1.14.2/lib/fluent/event.rb:315:in `each'
  2022-01-11 06:32:41 +1100 [warn]: /usr/lib64/ruby/gems/2.6.0/gems/fluentd-1.14.2/lib/fluent/event.rb:315:in `block in each'
  2022-01-11 06:32:41 +1100 [warn]: /usr/local/lib64/ruby/gems/2.6.0/gems/fluentd-1.14.3/lib/fluent/plugin/buffer/file_chunk.rb:171:in `open'
  2022-01-11 06:32:41 +1100 [warn]: /usr/lib64/ruby/gems/2.6.0/gems/fluentd-1.14.2/lib/fluent/event.rb:314:in `each'
  2022-01-11 06:32:41 +1100 [warn]: /usr/local/lib64/ruby/gems/2.6.0/gems/fluent-plugin-kafka-0.17.3/lib/fluent/plugin/out_kafka2.rb:245:in `write'
  2022-01-11 06:32:41 +1100 [warn]: /usr/lib64/ruby/gems/2.6.0/gems/fluentd-1.14.2/lib/fluent/plugin/output.rb:1179:in `try_flush'
  2022-01-11 06:32:41 +1100 [warn]: /usr/lib64/ruby/gems/2.6.0/gems/fluentd-1.14.2/lib/fluent/plugin/output.rb:1491:in `flush_thread_run'
  2022-01-11 06:32:41 +1100 [warn]: /usr/lib64/ruby/gems/2.6.0/gems/fluentd-1.14.2/lib/fluent/plugin/output.rb:499:in `block (2 levels) in start'
  2022-01-11 06:32:41 +1100 [warn]: /usr/lib64/ruby/gems/2.6.0/gems/fluentd-1.14.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2022-01-11 06:32:41 +1100 [warn]: bad chunk is moved to /tmp/fluent/backup/worker0/object_2ab553470a94/5d53ec4c498b358ba3cac6cd9bb0e57b.log
```

**Comment by hbbdgyb** [comment]
我也遇到了，用的docker image fluent/fluentd-kubernetes-daemonset:v1.16.1-debian-kafka2-1.2
