### ISSUE TITLE
Kafka::DeilveryFailed signature changed in latest ruby-kafka 

### ISSUE THREAD

**Issue by aschofie** [fluent/fluent-plugin-kafka#200]
https://github.com/zendesk/ruby-kafka/commit/b582f841e0fa128c6e8fd27b3d604fb6d950d88e#diff-9f541ff7c4b2ad26b10d56d95035c5b8

When I use ruby-kafka v0.4.2 the specific error in bold goes away, but I still get the Corrupt message errors.  I am using Kafka 1.1.1, my config is below, any ideas would be appreciated.

2018-06-18 19:42:12 +0000 [warn]: #0 suppressed same stacktrace
2018-06-18 19:42:21 +0000 [info]: #0 New topics added to target list: docker_logs
2018-06-18 19:42:21 +0000 [info]: #0 Fetching cluster metadata from kafka://nomad-agent-data-b.node.consul:9092
2018-06-18 19:42:21 +0000 [info]: #0 Discovered cluster metadata; nodes: 172.25.2.56:9092 (node_id=2), 172.25.1.91:9092 (node_id=1), 172.25.3.19:9092 (node_id=3)
2018-06-18 19:42:21 +0000 [info]: #0 Sending 1 messages to 172.25.1.91:9092 (node_id=1)
2018-06-18 19:42:21 +0000 [error]: #0 Corrupt message when writing to docker_logs/1 on 172.25.1.91:9092 (node_id=1)
2018-06-18 19:42:21 +0000 [warn]: #0 Failed to send all messages; attempting retry 1 of 3 after 1s
2018-06-18 19:42:22 +0000 [info]: #0 Sending 1 messages to 172.25.1.91:9092 (node_id=1)
2018-06-18 19:42:22 +0000 [error]: #0 Corrupt message when writing to docker_logs/1 on 172.25.1.91:9092 (node_id=1)
2018-06-18 19:42:22 +0000 [warn]: #0 Failed to send all messages; attempting retry 2 of 3 after 1s
2018-06-18 19:42:23 +0000 [info]: #0 Sending 1 messages to 172.25.1.91:9092 (node_id=1)
2018-06-18 19:42:23 +0000 [error]: #0 Corrupt message when writing to docker_logs/1 on 172.25.1.91:9092 (node_id=1)
2018-06-18 19:42:23 +0000 [warn]: #0 Failed to send all messages; attempting retry 3 of 3 after 1s
2018-06-18 19:42:24 +0000 [info]: #0 Sending 1 messages to 172.25.1.91:9092 (node_id=1)
2018-06-18 19:42:24 +0000 [error]: #0 Corrupt message when writing to docker_logs/1 on 172.25.1.91:9092 (node_id=1)
2018-06-18 19:42:24 +0000 [error]: #0 Failed to send all messages; keeping remaining messages in buffer
**2018-06-18 19:42:24 +0000 [warn]: #0 Send exception occurred: wrong number of arguments (given 1, expected 2)**
2018-06-18 19:42:24 +0000 [warn]: #0 Exception Backtrace : /var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka.rb:223:in `initialize'
/var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.7.3/lib/fluent/plugin/kafka_producer_ext.rb:184:in `exception'
/var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.7.3/lib/fluent/plugin/kafka_producer_ext.rb:184:in `raise'
/var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.7.3/lib/fluent/plugin/kafka_producer_ext.rb:184:in `deliver_messages_with_retries'
/var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.7.3/lib/fluent/plugin/kafka_producer_ext.rb:102:in `deliver_messages'
/var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.7.3/lib/fluent/plugin/out_kafka2.rb:217:in `write'
/var/lib/gems/2.3.0/gems/fluentd-1.1.3/lib/fluent/plugin/output.rb:1096:in `try_flush'
/var/lib/gems/2.3.0/gems/fluentd-1.1.3/lib/fluent/plugin/output.rb:1329:in `flush_thread_run'
/var/lib/gems/2.3.0/gems/fluentd-1.1.3/lib/fluent/plugin/output.rb:439:in `block (2 levels) in start'
/var/lib/gems/2.3.0/gems/fluentd-1.1.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-06-18 19:42:24 +0000 [info]: #0 initialized kafka producer: fluentd
2018-06-18 19:42:24 +0000 [info]: #0 Disconnecting broker 1

```
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>
<match *.**>
  @type copy
  <store>
    @type kafka2
    brokers nomad-agent-data-a.node.consul:9092,nomad-agent-data-b.node.consul:9092,nomad-agent-data-c.node.consul:9092
    default_topic docker_logs
    output_data_type    json
    output_include_tag  true
    output_include_time true
    max_send_retries    3
    required_acks       1
    get_kafka_client_log  true
    <format>
      @type json
    </format>
    <buffer topic>
      flush_interval 1s
    </buffer>
  </store>
  <store>
    @type elasticsearch
    host elasticsearch.service.consul
    port 9200
    logstash_format true
    logstash_prefix fluentd
    logstash_dateformat %Y%m%d
    include_tag_key true
    type_name access_log
    tag_key @log_name
    flush_interval 1s
  </store>
</match>

```

**Comment by repeatedly** [comment]
Thanks for the report. Will check.
