### ISSUE TITLE
Issue With Kafka and GZIP Compression

### ISSUE THREAD

**Issue by johne9087** [fluent/fluent-plugin-kafka#202]
Hello All. 

I have enabled GZIP Compression on Fluentd and since I am getting the below error. 

Has anyone had this before? 

Thanks

```log
2018-07-31 14:37:59 +0000 [warn]: #0 Send exception occurred: data error
2018-07-31 14:37:59 +0000 [warn]: #0 Exception Backtrace : /var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/gzip_codec.rb:19:in `close'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/gzip_codec.rb:19:in `compress'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/compressor.rb:56:in `block in compress_data'
/var/lib/gems/2.3.0/gems/activesupport-5.2.0/lib/active_support/notifications.rb:170:in `instrument'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/instrumenter.rb:21:in `instrument'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/compressor.rb:55:in `compress_data'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/compressor.rb:39:in `compress'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/produce_operation.rb:91:in `block (2 levels) in send_buffered_messages'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/message_buffer.rb:46:in `block (2 levels) in each'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/message_buffer.rb:45:in `each'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/message_buffer.rb:45:in `block in each'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/message_buffer.rb:44:in `each'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/message_buffer.rb:44:in `each'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/produce_operation.rb:89:in `block in send_buffered_messages'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/produce_operation.rb:83:in `each'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/produce_operation.rb:83:in `send_buffered_messages'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/produce_operation.rb:49:in `block in execute'
/var/lib/gems/2.3.0/gems/activesupport-5.2.0/lib/active_support/notifications.rb:170:in `instrument'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/instrumenter.rb:21:in `instrument'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/produce_operation.rb:43:in `execute'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/producer.rb:300:in `block in deliver_messages_with_retries'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/producer.rb:288:in `loop'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/producer.rb:288:in `deliver_messages_with_retries'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/producer.rb:238:in `block in deliver_messages'
/var/lib/gems/2.3.0/gems/activesupport-5.2.0/lib/active_support/notifications.rb:170:in `instrument'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/instrumenter.rb:21:in `instrument'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/producer.rb:231:in `deliver_messages'
/var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.7.3/lib/fluent/plugin/out_kafka_buffered.rb:281:in `deliver_messages'
/var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.7.3/lib/fluent/plugin/out_kafka_buffered.rb:330:in `block in write'
/var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/event.rb:323:in `each'
/var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/event.rb:323:in `block in each'
/var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/plugin/buffer/memory_chunk.rb:80:in `open'
/var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/plugin/buffer/memory_chunk.rb:80:in `open'
/var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/event.rb:322:in `each'
/var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.7.3/lib/fluent/plugin/out_kafka_buffered.rb:298:in `write'
/var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/compat/output.rb:131:in `write'
/var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/plugin/output.rb:1099:in `try_flush'
/var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/plugin/output.rb:1378:in `flush_thread_run'
/var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/plugin/output.rb:440:in `block (2 levels) in start'
/var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-07-31 14:37:59 +0000 [info]: #0 initialized kafka producer: kafka
2018-07-31 14:37:59 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-07-31 14:38:00 +0000 chunk="5724c86327e0b65039edf77b980a685d" error_class=Zlib::DataError error="data error"
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/gzip_codec.rb:19:in `close'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/gzip_codec.rb:19:in `compress'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/compressor.rb:56:in `block in compress_data'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/activesupport-5.2.0/lib/active_support/notifications.rb:170:in `instrument'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/instrumenter.rb:21:in `instrument'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/compressor.rb:55:in `compress_data'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/compressor.rb:39:in `compress'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/produce_operation.rb:91:in `block (2 levels) in send_buffered_messages'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/message_buffer.rb:46:in `block (2 levels) in each'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/message_buffer.rb:45:in `each'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/message_buffer.rb:45:in `block in each'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/message_buffer.rb:44:in `each'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/message_buffer.rb:44:in `each'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/produce_operation.rb:89:in `block in send_buffered_messages'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/produce_operation.rb:83:in `each'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/produce_operation.rb:83:in `send_buffered_messages'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/produce_operation.rb:49:in `block in execute'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/activesupport-5.2.0/lib/active_support/notifications.rb:170:in `instrument'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/instrumenter.rb:21:in `instrument'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/produce_operation.rb:43:in `execute'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/producer.rb:300:in `block in deliver_messages_with_retries'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/producer.rb:288:in `loop'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/producer.rb:288:in `deliver_messages_with_retries'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/producer.rb:238:in `block in deliver_messages'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/activesupport-5.2.0/lib/active_support/notifications.rb:170:in `instrument'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/instrumenter.rb:21:in `instrument'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/producer.rb:231:in `deliver_messages'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.7.3/lib/fluent/plugin/out_kafka_buffered.rb:281:in `deliver_messages'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.7.3/lib/fluent/plugin/out_kafka_buffered.rb:330:in `block in write'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/event.rb:323:in `each'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/event.rb:323:in `block in each'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/plugin/buffer/memory_chunk.rb:80:in `open'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/plugin/buffer/memory_chunk.rb:80:in `open'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/event.rb:322:in `each'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.7.3/lib/fluent/plugin/out_kafka_buffered.rb:298:in `write'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/compat/output.rb:131:in `write'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/plugin/output.rb:1099:in `try_flush'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/plugin/output.rb:1378:in `flush_thread_run'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/plugin/output.rb:440:in `block (2 levels) in start'
  2018-07-31 14:37:59 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
zlib(finalizer): Zlib::GzipWriter object must be closed explicitly.
zlib(finalizer): the stream state was inconsistent.
```

**Comment by cosmo0920** [comment]
It seems that this issue had been occurred in ruby-kafka:
https://github.com/zendesk/ruby-kafka/blob/a7a1ab4e7e4dbb57151b08322f79aa4070b44bef/lib/kafka/gzip_codec.rb#L19

Could you report this issue on [ruby-kafka](https://github.com/zendesk/ruby-kafka)?

**Comment by johne9087** [comment]
Thank You. I shall wait until v1.3.

**Comment by repeatedly** [comment]
BTW, if you see "retry succeeded" in the log, the writing logs has no problem.
