### ISSUE TITLE
 facing challange to connect fluentd with kafka over TLS :

### ISSUE THREAD

**Issue by himmatb** [fluent/fluent-plugin-kafka#222]
Hi Fluent-plugin-kafka,

I am facing challange to connect fluentd with kafka over TLS :

fluentd - fluentd 1.1.1

Below is fluentd configuration which i am using send logs to kafka over TLS/HTTPS : 

```
<source>
   @type tail
   path /opt/test-logs/finbroker.log
   pos_file /var/fluentd/file2
   tag tibcologs-finbroker
   read_from_head true
   format none
</source>

<match **>
  @type kafka
  brokers "kafka-amq-cluster-kafka-bootstrap-logging.xxx.xxx.com:443"
  ssl_ca_cert "/etc/fluent/keys/cluster-ca.crt"
  default_topic topic-finbroker
  output_data_type json
  flush_interval 1s
</match>
```
I am trying to connect Fluentd agent with Kafka over TLS encryption as mentioned in above configuration but I am getting below error while connecting. Please help me to resolve and identify issue.

Below is error log :

2018-10-24 11:17:01 +0400 [info]: #0 initialized kafka producer: kafka
2018-10-24 11:17:01 +0400 [warn]: #0 emit transaction failed: error_class=Kafka::ConnectionError error="Could not connect to any of the seed brokers:\n- kafka://kafka-amq-cluster-kafka-bootstrap-logging.xxxx.xxxx.com:443: Connection error EOFError: end of file reached" location="/usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.6.7/lib/kafka/cluster.rb:407:in fetch_cluster_info'" tag="fluent.info" 2018-10-24 11:17:01 +0400 [warn]: #0 /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.6.7/lib/kafka/cluster.rb:407:in fetch_cluster_info'
2018-10-24 11:17:01 +0400 [warn]: #0 /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.6.7/lib/kafka/cluster.rb:367:in cluster_info' 2018-10-24 11:17:01 +0400 [warn]: #0 /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.6.7/lib/kafka/cluster.rb:95:in refresh_metadata!'
2018-10-24 11:17:01 +0400 [warn]: #0 /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.6.7/lib/kafka/cluster.rb:50:in add_target_topics' 2018-10-24 11:17:01 +0400 [warn]: #0 /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.6.7/lib/kafka/producer.rb:276:in deliver_messages_with_retries'
2018-10-24 11:17:01 +0400 [warn]: #0 /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.6.7/lib/kafka/producer.rb:238:in block in deliver_messages' 2018-10-24 11:17:01 +0400 [warn]: #0 /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.6.7/lib/kafka/instrumenter.rb:23:in instrument'
2018-10-24 11:17:01 +0400 [warn]: #0 /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.6.7/lib/kafka/producer.rb:231:in deliver_messages' 2018-10-24 11:17:01 +0400 [warn]: #0 /usr/local/lib/ruby/gems/2.4.0/gems/fluent-plugin-kafka-0.7.9/lib/fluent/plugin/out_kafka.rb:240:in emit'
2018-10-24 11:17:01 +0400 [warn]: #0 /usr/local/lib/ruby/gems/2.4.0/gems/fluentd-1.1.1/lib/fluent/compat/output.rb:164:in process' 2018-10-24 11:17:01 +0400 [warn]: #0 /usr/local/lib/ruby/gems/2.4.0/gems/fluentd-1.1.1/lib/fluent/plugin/output.rb:760:in emit_sync'
2018-10-24 11:17:01 +0400 [warn]: #0 /usr/local/lib/ruby/gems/2.4.0/gems/fluentd-1.1.1/lib/fluent/event_router.rb:96:in emit_stream' 2018-10-24 11:17:01 +0400 [warn]: #0 /usr/local/lib/ruby/gems/2.4.0/gems/fluentd-1.1.1/lib/fluent/event_router.rb:87:in emit'
2018-10-24 11:17:01 +0400 [warn]: #0 /usr/local/lib/ruby/gems/2.4.0/gems/fluentd-1.1.1/lib/fluent/engine.rb:207:in block in log_event_loop' 2018-10-24 11:17:01 +0400 [warn]: #0 /usr/local/lib/ruby/gems/2.4.0/gems/fluentd-1.1.1/lib/fluent/engine.rb:205:in each'
2018-10-24 11:17:01 +0400 [warn]: #0 /usr/local/lib/ruby/gems/2.4.0/gems/fluentd-1.1.1/lib/fluent/engine.rb:205:in `log_event_loop'
2018-10-24 11:17:01 +0400 [error]: #0 failed to emit fluentd's log event tag="fluent.info" event={"worker"=>0, "message"=>"fluentd worker is now running worker=0"} error_class=Kafka::ConnectionError error="Could not connect to any of the seed brokers:\n- kafka://kafka-amq-cluster-kafka-bootstrap-logging.xxxx.xxxx.com:443: Connection error EOFError: end of file reached"

Thanks In Advance!!

**Comment by repeatedly** [comment]
fluent-plugin-kafka uses ruby-kafka internally.

https://github.com/zendesk/ruby-kafka#setting-up-the-kafka-client
https://github.com/zendesk/ruby-kafka#encryption-and-authentication-using-ssl

You can use small script to check your kafka setup is ok or not without fluentd.
There are several reasons:

- kafka / ruby-kafka version mismatch
- kafka setup mismatch
- etc

**Comment by baaree** [comment]
Hi,

To assist on this we have followed simple steps to adress this issue, but error persists even after upgrading ruby-kafka to 0.7.2/0.7.3
Even after lunching same thing over multiple servers result is the same.

NOTE That if we enforce traffic to go to other port NOT 443, but 30XXX+ it will result with successful execution.
Question is if ruby-kafka plugin supporting TLS with SNI ?
Because if it don't than we have explanation what is RCA of this issue.

On the other hand using logstash-kafka output works with same parameters configured.
Also same kafka using standard producer/consumer with TLS enabled with same certificate works as per expectation.

Is there anything that i could share with you that might give better insight to this issue and help us in resolving this issue or having clarity what might be an issue?


Runned code:
`require "kafka"
kafka = Kafka.new(["kafka-amq-cluster-kafka-bootstrap-logging.openshift.xxx.com:443"], ssl_ca_cert: File.read('/root/cert'))
kafka.topics`

After running in debug mode mentioned code this is response that we are getting:

`ruby -d test_kafka
Exception `LoadError' at /usr/local/lib/ruby/2.4.0/rubygems.rb:1347 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /usr/local/lib/ruby/2.4.0/rubygems.rb:1356 - cannot load such file -- rubygems/defaults/ruby
Exception `LoadError' at /usr/local/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55 - cannot load such file -- kafka
/usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.2/lib/kafka/protocol/metadata_response.rb:116: warning: shadowing outer local variable - broker
/usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.2/lib/kafka/protocol/metadata_response.rb:148: warning: assigned but unused variable - rack
/usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.2/lib/kafka/protocol/metadata_response.rb:162: warning: assigned but unused variable - is_internal
/usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.2/lib/kafka/protocol/describe_groups_response.rb:48: warning: assigned but unused variable - metadata
/usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.2/lib/kafka/protocol/message.rb:70: warning: assigned but unused variable - crc
/usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.2/lib/kafka/connection.rb:145: warning: instance variable @last_request not initialized
/usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.2/lib/kafka/connection.rb:68: warning: instance variable @socket not initialized
Exception `IO::EINPROGRESSWaitWritable' at /usr/local/lib/ruby/2.4.0/socket.rb:1198 - Operation now in progress - connect(2) would block
Exception `Errno::EISCONN' at /usr/local/lib/ruby/2.4.0/socket.rb:1198 - Transport endpoint is already connected - connect(2) for 10.119.0.58:443
Exception `OpenSSL::SSL::SSLErrorWaitReadable' at /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.2/lib/kafka/ssl_socket_with_timeout.rb:68 - read would block
Exception `OpenSSL::SSL::SSLErrorWaitReadable' at /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.2/lib/kafka/ssl_socket_with_timeout.rb:68 - read would block
Exception `OpenSSL::SSL::SSLErrorWaitReadable' at /usr/local/lib/ruby/2.4.0/openssl/buffering.rb:182 - read would block
Exception `EOFError' at /usr/local/lib/ruby/2.4.0/openssl/buffering.rb:182 - end of file reached
Exception `Kafka::ConnectionError' at /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.2/lib/kafka/connection.rb:115 - Connection error EOFError: end of file reached
Exception `Kafka::ConnectionError' at /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.2/lib/kafka/broker.rb:198 - Connection error EOFError: end of file reached
Exception `Kafka::ConnectionError' at /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.2/lib/kafka/cluster.rb:396 - Could not connect to any of the seed brokers:
- kafka://kafka-amq-cluster-kafka-bootstrap-logging.openshift.XXX.com:443: Connection error EOFError: end of file reached
/usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.2/lib/kafka/connection.rb:145: warning: instance variable @last_request not initialized
/usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.2/lib/kafka/connection.rb:68: warning: instance variable @socket not initialized
Exception `IO::EINPROGRESSWaitWritable' at /usr/local/lib/ruby/2.4.0/socket.rb:1198 - Operation now in progress - connect(2) would block
Exception `Errno::EISCONN' at /usr/local/lib/ruby/2.4.0/socket.rb:1198 - Transport endpoint is already connected - connect(2) for 10.119.0.58:443
Exception `OpenSSL::SSL::SSLErrorWaitReadable' at /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.2/lib/kafka/ssl_socket_with_timeout.rb:68 - read would block
Exception `OpenSSL::SSL::SSLErrorWaitReadable' at /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.2/lib/kafka/ssl_socket_with_timeout.rb:68 - read would block
Exception `OpenSSL::SSL::SSLErrorWaitReadable' at /usr/local/lib/ruby/2.4.0/openssl/buffering.rb:182 - read would block
Exception `EOFError' at /usr/local/lib/ruby/2.4.0/openssl/buffering.rb:182 - end of file reached
Exception `Kafka::ConnectionError' at /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.2/lib/kafka/connection.rb:115 - Connection error EOFError: end of file reached
Exception `Kafka::ConnectionError' at /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.2/lib/kafka/broker.rb:198 - Connection error EOFError: end of file reached
Exception `Kafka::ConnectionError' at /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.2/lib/kafka/cluster.rb:396 - Could not connect to any of the seed brokers:
- kafka://kafka-amq-cluster-kafka-bootstrap-logging.openshift.XXX.com:443: Connection error EOFError: end of file reached
Exception `Kafka::ConnectionError' at /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.2/lib/kafka/client.rb:628 - Could not connect to any of the seed brokers:
- kafka://kafka-amq-cluster-kafka-bootstrap-logging.openshift.XXX.com:443: Connection error EOFError: end of file reached
/usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.2/lib/kafka/cluster.rb:396:in `fetch_cluster_info': Could not connect to any of the seed brokers: (Kafka::ConnectionError)
- kafka://kafka-amq-cluster-kafka-bootstrap-logging.openshift.XXX.com:443: Connection error EOFError: end of file reached
        from /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.2/lib/kafka/cluster.rb:350:in `cluster_info'
        from /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.2/lib/kafka/cluster.rb:98:in `refresh_metadata!'
        from /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.2/lib/kafka/cluster.rb:102:in `refresh_metadata_if_necessary!'
        from /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.2/lib/kafka/cluster.rb:400:in `random_broker'
        from /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.2/lib/kafka/cluster.rb:330:in `list_topics'
        from /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.2/lib/kafka/client.rb:624:in `topics'`
