### ISSUE TITLE
Can not send message to kafka use 0.8.1

### ISSUE THREAD

**Issue by zhigang** [fluent/fluent-plugin-kafka#229]
I got error when send message to kafka. My environment is in kubernetes cluster.
Please tell me what can I do. Thanks.

- Version
  - kafka:2.11-1.0.2
  - fluentd: 1.2.2
  - fluent-plugin-kafka: 0.8.1
  - ruby-kafka: 0.7.4

- Config

```
    <match **>
      @type kafka2
      brokers kafka-0:9092,kafka-1:9092,kafka-2:9092
      default_topic k8slog
      # ruby-kafka producer options
      compression_codec gzip
      <inject>
        tag_key   tag
        time_key  time
      </inject>
      <format>
        @type json
      </format>
      <buffer>
        @type file
        path /var/log/fluentd-buffers/kubernetes.system.buffer
        flush_mode interval
        retry_type exponential_backoff
        flush_thread_count 2
        flush_interval 180s
        retry_forever true
        retry_max_interval 30
        overflow_action block
      </buffer>
    </match>
```

- Error log:

```
2018-12-06 05:16:35 +0000 [warn]: Send exception occurred: wrong number of arguments (given 1, expected 2)
2018-12-06 05:16:35 +0000 [warn]: Exception Backtrace : /var/lib/gems/2.3.0/gems/ruby-kafka-0.7.4/lib/kafka.rb:333:in `initialize'
/var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.8.1/lib/fluent/plugin/kafka_producer_ext.rb:244:in `exception'
/var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.8.1/lib/fluent/plugin/kafka_producer_ext.rb:244:in `raise'
/var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.8.1/lib/fluent/plugin/kafka_producer_ext.rb:244:in `deliver_messages_with_retries'
/var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.8.1/lib/fluent/plugin/kafka_producer_ext.rb:130:in `deliver_messages'
/var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.8.1/lib/fluent/plugin/out_kafka2.rb:224:in `write'
/var/lib/gems/2.3.0/gems/fluentd-1.2.2/lib/fluent/plugin/output.rb:1099:in `try_flush'
/var/lib/gems/2.3.0/gems/fluentd-1.2.2/lib/fluent/plugin/output.rb:1378:in `flush_thread_run'
/var/lib/gems/2.3.0/gems/fluentd-1.2.2/lib/fluent/plugin/output.rb:440:in `block (2 levels) in start'
/var/lib/gems/2.3.0/gems/fluentd-1.2.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-12-06 05:16:35 +0000 [warn]: got unrecoverable error in primary and no secondary error_class=ArgumentError error="wrong number of arguments (given 1, expected 2)"
2018-12-06 05:16:35 +0000 [warn]: bad chunk is moved to /tmp/fluentd-buffers/backup/worker0/object_3fd8d3c84560/57c538ecab130f8c41509d587593ea4c.log
```

**Comment by repeatedly** [comment]
Will check it.

**Comment by zhigang** [comment]
> Will check it.

Thank for fixed, But I got another error.
```
2018-12-07 03:02:35 +0000 [warn]: Send exception occurred: Failed to send messages to k8slog/2, k8slog/0, k8slog/1
2018-12-07 03:02:35 +0000 [warn]: Exception Backtrace : /var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.8.1/lib/fluent/plugin/kafka_producer_ext.rb:244:in `deliver_messages_with_retries'
/var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.8.1/lib/fluent/plugin/kafka_producer_ext.rb:130:in `deliver_messages'
/var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.8.1/lib/fluent/plugin/out_kafka2.rb:224:in `write'
/var/lib/gems/2.3.0/gems/fluentd-1.2.2/lib/fluent/plugin/output.rb:1099:in `try_flush'
/var/lib/gems/2.3.0/gems/fluentd-1.2.2/lib/fluent/plugin/output.rb:1378:in `flush_thread_run'
/var/lib/gems/2.3.0/gems/fluentd-1.2.2/lib/fluent/plugin/output.rb:440:in `block (2 levels) in start'
/var/lib/gems/2.3.0/gems/fluentd-1.2.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-12-07 03:02:35 +0000 [warn]: failed to flush the buffer. retry_time=0 next_retry_seconds=2018-12-07 03:02:36 +0000 chunk="57c65c3817a844f5a1fc2067a67d9534" error_class=Kafka::DeliveryFailed error="Failed to send messages to k8slog/2, k8slog/0, k8slog/1"
  2018-12-07 03:02:35 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.8.1/lib/fluent/plugin/kafka_producer_ext.rb:244:in `deliver_messages_with_retries'
  2018-12-07 03:02:35 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.8.1/lib/fluent/plugin/kafka_producer_ext.rb:130:in `deliver_messages'
  2018-12-07 03:02:35 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.8.1/lib/fluent/plugin/out_kafka2.rb:224:in `write'
  2018-12-07 03:02:35 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.2.2/lib/fluent/plugin/output.rb:1099:in `try_flush'
  2018-12-07 03:02:35 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.2.2/lib/fluent/plugin/output.rb:1378:in `flush_thread_run'
  2018-12-07 03:02:35 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.2.2/lib/fluent/plugin/output.rb:440:in `block (2 levels) in start'
  2018-12-07 03:02:35 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.2.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```

**Comment by repeatedly** [comment]
This is not fluentd related error.
ruby-kafka can't write messages to your cluster.
So your setup or something is wrong.

**Comment by zhigang** [comment]
> This is not fluentd related error.
> ruby-kafka can't write messages to your cluster.
> So your setup or something is wrong.

OK. I will check this. Thanks.

**Comment by yuanzy1994** [comment]
> > This is not fluentd related error.
> > ruby-kafka can't write messages to your cluster.
> > So your setup or something is wrong.
> 
> OK. I will check this. Thanks.

Please, Have you resolving this?

**Comment by zhigang** [comment]
> > > This is not fluentd related error.
> > > ruby-kafka can't write messages to your cluster.
> > > So your setup or something is wrong.
> > 
> > 
> > OK. I will check this. Thanks.
> 
> Please, Have you resolving this?

I use a hight kafka version in this case. and ruby-kafka is limited support for it.
