### ISSUE TITLE
fluent-plugin-kafka 0.8.1 to kafka 0.10.2.1 failed

### ISSUE THREAD

**Issue by like-inspur** [fluent/fluent-plugin-kafka#232]
I create kubernetes kafka with version 0.10.2.1, and install fluentd write kafka with plugin 0.8.1

when I use kafka_buffered for output to kafka, the error is like this:
2018-12-13 11:53:54 +0000 [warn]: failed to flush the buffer. retry_time=3 next_retry_seconds=2018-12-13 11:53:57 +0000 chunk="57ce5f7c0f79df60d7559148cbc6073a" error_class=Kafka::DeliveryFailed error="Failed to send messages to fluentd/1, fluentd/0"
  2018-12-13 11:53:54 +0000 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.7.4/lib/kafka/producer.rb:412:in `deliver_messages_with_retries'
  2018-12-13 11:53:54 +0000 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.7.4/lib/kafka/producer.rb:247:in `block in deliver_messages'
  2018-12-13 11:53:54 +0000 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.7.4/lib/kafka/instrumenter.rb:23:in `instrument'
  2018-12-13 11:53:54 +0000 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.7.4/lib/kafka/producer.rb:240:in `deliver_messages'
  2018-12-13 11:53:54 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.8.1/lib/fluent/plugin/out_kafka_buffered.rb:285:in `deliver_messages'
  2018-12-13 11:53:54 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.8.1/lib/fluent/plugin/out_kafka_buffered.rb:334:in `block in write'
  2018-12-13 11:53:54 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/event.rb:323:in `each'
  2018-12-13 11:53:54 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/event.rb:323:in `block in each'
  2018-12-13 11:53:54 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/plugin/buffer/file_chunk.rb:172:in `open'
  2018-12-13 11:53:54 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/event.rb:322:in `each'
  2018-12-13 11:53:54 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.8.1/lib/fluent/plugin/out_kafka_buffered.rb:302:in `write'
  2018-12-13 11:53:54 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/compat/output.rb:131:in `write'
  2018-12-13 11:53:54 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/plugin/output.rb:1110:in `try_flush'
  2018-12-13 11:53:54 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/plugin/output.rb:1389:in `flush_thread_run'
  2018-12-13 11:53:54 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/plugin/output.rb:444:in `block (2 levels) in start'
  2018-12-13 11:53:54 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'

And kafka also outputs error like this:
[2018-12-13 11:38:47,102] ERROR Closing socket for 158.158.104.104:9093-158.158.72.116:51890 because of error (kafka.network.Processor)
org.apache.kafka.common.errors.InvalidRequestException: Error getting request for apiKey: 0 and apiVersion: 3
Caused by: java.lang.IllegalArgumentException: Invalid version for API key 0: 3
	at org.apache.kafka.common.protocol.ProtoUtils.schemaFor(ProtoUtils.java:31)
	at org.apache.kafka.common.protocol.ProtoUtils.requestSchema(ProtoUtils.java:50)
	at org.apache.kafka.common.protocol.ProtoUtils.parseRequest(ProtoUtils.java:66)
	at org.apache.kafka.common.requests.ProduceRequest.parse(ProduceRequest.java:210)
	at org.apache.kafka.common.requests.AbstractRequest.getRequest(AbstractRequest.java:83)
	at kafka.network.RequestChannel$Request.liftedTree2$1(RequestChannel.scala:94)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:89)
	at kafka.network.Processor$$anonfun$processCompletedReceives$1.apply(SocketServer.scala:513)
	at kafka.network.Processor$$anonfun$processCompletedReceives$1.apply(SocketServer.scala:505)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at kafka.network.Processor.processCompletedReceives(SocketServer.scala:505)
	at kafka.network.Processor.run(SocketServer.scala:433)
	at java.lang.Thread.run(Thread.java:748)

**Comment by like-inspur** [comment]
when I use kafka2 for output to kafka, the error is like this:
2018-12-13 12:05:18 +0000 [warn]: Send exception occurred: wrong number of arguments (given 1, expected 2)
2018-12-13 12:05:18 +0000 [warn]: Exception Backtrace : /var/lib/gems/2.3.0/gems/ruby-kafka-0.7.4/lib/kafka.rb:333:in `initialize'
/var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.8.1/lib/fluent/plugin/kafka_producer_ext.rb:244:in `exception'
/var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.8.1/lib/fluent/plugin/kafka_producer_ext.rb:244:in `raise'
/var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.8.1/lib/fluent/plugin/kafka_producer_ext.rb:244:in `deliver_messages_with_retries'
/var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.8.1/lib/fluent/plugin/kafka_producer_ext.rb:130:in `deliver_messages'
/var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.8.1/lib/fluent/plugin/out_kafka2.rb:224:in `write'
/var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/plugin/output.rb:1110:in `try_flush'
/var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/plugin/output.rb:1389:in `flush_thread_run'
/var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/plugin/output.rb:444:in `block (2 levels) in start'
/var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-12-13 12:05:18 +0000 [warn]: got unrecoverable error in primary and no secondary error_class=ArgumentError error="wrong number of arguments (given 1, expected 2)"

**Comment by like-inspur** [comment]
Doesn't the new version support old version kafka? Which version do I need ? Thank you!

**Comment by repeatedly** [comment]
> Doesn't the new version support old version kafka?

Yes because ruby-kafka update support kafka version for new features.

> Which version do I need ?

Check ruby-kafka document and downgrade ruby-kafka and fluent-plugin-kafka.

https://github.com/zendesk/ruby-kafka#compatibility

I didn't test but fluent-plugin-kafka v0.6 or v0.7 may work.

**Comment by like-inspur** [comment]
ruby-kafka version 0.5.4 and fluent-plugin-kafka version 0.7.9 works.

**Comment by like-inspur** [comment]
I use kafka2 for output kafka, and then use logstash output elasticsearch. But found that there is no tag filed which stored in elasticsearch . Does it works by using followed config:
<inject>
    tag_key tag
</inject>

**Comment by kenhys** [comment]
Solved by https://github.com/fluent/fluent-plugin-kafka/issues/232#issuecomment-447542613
