### ISSUE TITLE
undefined local variable or method `logger'

### ISSUE THREAD

**Issue by wgtmpeters** [fluent/fluent-plugin-kafka#234]
I am trying to define a source using the type kafka in a fluentd setup with kube-fluentd-operator.
The config part on kube-system namespace:

```aconf
<source>
  @type kafka

  brokers kafka.kafka.svc.cluster.local:9092
  topics systemevent
</source>
```

This should be allowed and I do see that it tries to start the kafkainput but I see errors:

```log
2018-12-17 12:46:43 +0000 [error]: #0 unexpected error error_class=NameError error="undefined local variable or method `logger' for #<Fluent::KafkaInput:007f7caf44fd80>"
  2018-12-17 12:46:43 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.7.7/lib/fluent/plugin/in_kafka.rb:186:in `start'
  2018-12-17 12:46:43 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.3/lib/fluent/compat/call_super_mixin.rb:42:in `start'
  2018-12-17 12:46:43 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.3/lib/fluent/root_agent.rb:165:in `block in start'
  2018-12-17 12:46:43 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.3/lib/fluent/root_agent.rb:154:in `block (2 levels) in lifecycle'
  2018-12-17 12:46:43 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.3/lib/fluent/root_agent.rb:153:in `each'
  2018-12-17 12:46:43 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.3/lib/fluent/root_agent.rb:153:in `block in lifecycle'
  2018-12-17 12:46:43 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.3/lib/fluent/root_agent.rb:140:in `each'
  2018-12-17 12:46:43 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.3/lib/fluent/root_agent.rb:140:in `lifecycle'
  2018-12-17 12:46:43 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.3/lib/fluent/root_agent.rb:164:in `start'
  2018-12-17 12:46:43 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.3/lib/fluent/engine.rb:274:in `start'
  2018-12-17 12:46:43 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.3/lib/fluent/engine.rb:219:in `run'
  2018-12-17 12:46:43 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.3/lib/fluent/supervisor.rb:774:in `run_engine'
  2018-12-17 12:46:43 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.3/lib/fluent/supervisor.rb:523:in `block in run_worker'
  2018-12-17 12:46:43 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.3/lib/fluent/supervisor.rb:699:in `main_process'
  2018-12-17 12:46:43 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.3/lib/fluent/supervisor.rb:518:in `run_worker'
  2018-12-17 12:46:43 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.3/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
  2018-12-17 12:46:43 +0000 [error]: #0 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2018-12-17 12:46:43 +0000 [error]: #0 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2018-12-17 12:46:43 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.3/bin/fluentd:8:in `<top (required)>'
  2018-12-17 12:46:43 +0000 [error]: #0 /usr/local/bin/fluentd:22:in `load'
  2018-12-17 12:46:43 +0000 [error]: #0 /usr/local/bin/fluentd:22:in `<main>'
```

Is there maybe something missing in this fluentd version that the plugin needs? 
I see for example in a couple of the ruby files in this repo that the logger is explicitly set to nil for the logger argument.

**Comment by kenhys** [comment]
Fixed via #214 and shipped as v0.7.8
