### ISSUE TITLE
[out_kafka] failed to flush the buffer

### ISSUE THREAD

**Issue by dmgcodevil** [fluent/fluent-plugin-kafka#246]
Hi, I know there are bunch of similar tickets on the github, but I still can't figure out how to fix the problem. 

I use fluentd-daemonset-kafka - kubernetes DaemonSet to collect logs. My config file for fluentd kafka looks as follows:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-logging
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.3-debian-kafka
        env:
          - name: FLUENT_KAFKA_BROKERS
            value: kafka-svc.default.svc.cluster.local:9092
          - name: FLUENT_KAFKA_DEFAULT_TOPIC
            value: kube-logs
          - name: FLUENT_KAFKA_REQUIRED_ACKS
            value: "-1"
          - name: FLUENT_KAFKA_COMPRESSION_CODEC
            value: "gzip"
          - name: FLUENT_KAFKA_MAX_SEND_LIMIT_BYTES
            value: "1000000"    
          - name: FLUENT_UID
            value: "0"
          - name: FLUENTD_SYSTEMD_CONF
            value: "disable"  
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
``` 

I use spotify/kafka docker image, deployment config:

```
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  labels:
    app: kafka
spec:
  type: ClusterIP
  ports:
  - port: 9092
    protocol: TCP
    targetPort: 9092
    name: kafka
  - port: 2181
    targetPort: 2181
    protocol: TCP
    name: zk
  selector:
    app: kafka
# Service is looking for pods with the label `app=hello-world`
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: spotify/kafka
        ports:
        - containerPort: 9092
        - containerPort: 2181
```

kafka is working, if I `docker exec -it [kafka-docker-id]  /bin/bash ` and run kafka-console-producer and kafka-console-consumer I see messages are being received by consumer. 

kafka version `kafka_2.11-0.10.1.0`

but when I run fluentd daemonset and don't see any messages delivered to kafka. Logs:

```
2019-02-27 20:49:23 +0000 [warn]: #0 [out_kafka] Send exception occurred: Failed to send messages to kube-logs/0
2019-02-27 20:49:23 +0000 [warn]: #0 [out_kafka] Exception Backtrace : /fluentd/vendor/bundle/ruby/2.3.0/gems/ruby-kafka-0.6.8/lib/kafka/producer.rb:330:in `deliver_messages_with_retries'
/fluentd/vendor/bundle/ruby/2.3.0/gems/ruby-kafka-0.6.8/lib/kafka/producer.rb:238:in `block in deliver_messages'
/fluentd/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/notifications.rb:170:in `instrument'
/fluentd/vendor/bundle/ruby/2.3.0/gems/ruby-kafka-0.6.8/lib/kafka/instrumenter.rb:21:in `instrument'
/fluentd/vendor/bundle/ruby/2.3.0/gems/ruby-kafka-0.6.8/lib/kafka/producer.rb:231:in `deliver_messages'
/fluentd/vendor/bundle/ruby/2.3.0/gems/fluent-plugin-kafka-0.7.9/lib/fluent/plugin/out_kafka_buffered.rb:281:in `deliver_messages'
/fluentd/vendor/bundle/ruby/2.3.0/gems/fluent-plugin-kafka-0.7.9/lib/fluent/plugin/out_kafka_buffered.rb:344:in `write'
/fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.3.2/lib/fluent/compat/output.rb:131:in `write'
/fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.3.2/lib/fluent/plugin/output.rb:1123:in `try_flush'
/fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.3.2/lib/fluent/plugin/output.rb:1423:in `flush_thread_run'
/fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.3.2/lib/fluent/plugin/output.rb:452:in `block (2 levels) in start'
/fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.3.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-02-27 20:49:23 +0000 [info]: #0 [out_kafka] initialized kafka producer: kafka
2019-02-27 20:49:23 +0000 [warn]: #0 [out_kafka] failed to flush the buffer. retry_time=5 next_retry_seconds=2019-02-27 20:49:38 +0000 chunk="582e64a2f1732566a9294130f8ee7769" error_class=Kafka::DeliveryFailed error="Failed to send messages to kube-logs/0"
  2019-02-27 20:49:23 +0000 [warn]: #0 suppressed same stacktrace
```

also I see a bunch of 

```
2019-02-27 20:49:32 +0000 [warn]: #0 [in_systemd_docker] Systemd::JournalError: No such file or directory retrying in 1s
2019-02-27 20:49:32 +0000 [warn]: #0 [in_systemd_bootkube] Systemd::JournalError: No such file or directory retrying in 1s
2019-02-27 20:49:32 +0000 [warn]: #0 [in_systemd_kubelet] Systemd::JournalError: No such file or directory retrying in 1s
```

However I think it shouldn't matter. 

Also I tried to use fluent_kafka plugin with fluentd w/o docker & kubernetes, buffered version , and was getting the following error:

```
/fluentd-1.4.0/lib/fluent/plugin/output.rb:1125:in `try_flush'\n/Library/Ruby/Gems/2.3.0/gems/fluentd-1.4.0/lib/fluent/plugin/output.rb:1425:in `flush_thread_run'\n/Library/Ruby/Gems/2.3.0/gems/fluentd-1.4.0/lib/fluent/plugin/output.rb:454:in `block (2 levels) in start'\n/Library/Ruby/Gems/2.3.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'"}

{"error":"#<NoMethodError: undefined method `key' for #<Fluent::Plugin::Buffer::FileChunk:0x00007f7f18a7c828>>","message":"[out_kafka] got unrecoverable error in primary and no secondary error_class=NoMethodError error=\"undefined method `key' for #<Fluent::Plugin::Buffer::FileChunk:0x00007f7f18a7c828>\""}
 ```

Does anybody know what the problem is or how to troubleshoot ?

**Comment by repeatedly** [comment]
> 2019-02-27 20:49:23 +0000 [warn]: #0 [out_kafka] Send exception occurred: Failed to send messages to kube-logs/0
> 2019-02-27 20:49:23 +0000 [warn]: #0 [out_kafka] Exception Backtrace : /fluentd/vendor/bundle/ruby/2.3.0/gems/ruby-kafka-0.6.8/lib/kafka/producer.rb:330:in `deliver_messages_with_retries'

I didn't test but I assume your kafka cluster is old version so ruby-kafka doesn't support such older clusters.
Maybe, downgrade fluent-plugin-kafka and ruby-kafka may resolve it.

**Comment by repeatedly** [comment]
Here is compatibility note between ruby-kafka and kafka: https://github.com/zendesk/ruby-kafka#compatibility

**Comment by dmgcodevil** [comment]
@repeatedly thanks for the reply. I downgraded `ruby-kafka` to 0.5.4 but the problem still persists:

```
19-02-28 15:39:12 +0000 [warn]: Send exception occurred: Failed to send messages to kube-logs/0
2019-02-28 15:39:12 +0000 [warn]: Exception Backtrace : /fluentd/vendor/bundle/ruby/2.3.0/gems/ruby-kafka-0.5.4/lib/kafka/producer.rb:328:in `deliver_messages_with_retries'
/fluentd/vendor/bundle/ruby/2.3.0/gems/ruby-kafka-0.5.4/lib/kafka/producer.rb:236:in `block in deliver_messages'
/fluentd/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/notifications.rb:170:in `instrument'
/fluentd/vendor/bundle/ruby/2.3.0/gems/ruby-kafka-0.5.4/lib/kafka/instrumenter.rb:19:in `instrument'
/fluentd/vendor/bundle/ruby/2.3.0/gems/ruby-kafka-0.5.4/lib/kafka/producer.rb:229:in `deliver_messages'
/fluentd/vendor/bundle/ruby/2.3.0/gems/fluent-plugin-kafka-0.7.9/lib/fluent/plugin/out_kafka_buffered.rb:281:in `deliver_messages'
/fluentd/vendor/bundle/ruby/2.3.0/gems/fluent-plugin-kafka-0.7.9/lib/fluent/plugin/out_kafka_buffered.rb:330:in `block in write'
/fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-0.12.43/lib/fluent/plugin/buf_memory.rb:67:in `feed_each'
/fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-0.12.43/lib/fluent/plugin/buf_memory.rb:67:in `msgpack_each'
/fluentd/vendor/bundle/ruby/2.3.0/gems/fluent-plugin-kafka-0.7.9/lib/fluent/plugin/out_kafka_buffered.rb:298:in `write'
/fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-0.12.43/lib/fluent/buffer.rb:354:in `write_chunk'
/fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-0.12.43/lib/fluent/buffer.rb:333:in `pop'
/fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-0.12.43/lib/fluent/output.rb:342:in `try_flush'
/fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-0.12.43/lib/fluent/output.rb:149:in `run'
2019-02-28 15:39:12 +0000 [info]: initialized kafka producer: kafka
2019-02-28 15:39:12 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-02-28 15:40:16 +0000 error_class="Kafka::DeliveryFailed" error="Failed to send messages to kube-logs/0" plugin_id="out_kafka"
```

**Comment by dmgcodevil** [comment]
ruby-kafka client itself works:

```
require 'rubygems'
gem 'ruby-kafka', '=0.5.4'
require 'kafka'


kafka = Kafka.new(["kfk101"], client_id: "my-application")
kafka.deliver_message("Hello, World!", topic: "my topic")
```

I see the message delivered and consumed by kafka console consumer.
