### ISSUE TITLE
write data to kafka error

### ISSUE THREAD

**Issue by wanghonglei5181** [fluent/fluent-plugin-kafka#251]
**my enviroment**
os:centos7.3 64bit
fluentd: td-agent-3.3.0-1.el7.x86_64
ruby-kafka:ruby-kafka-0.7.6
kafka: 0.9.0
**my config files**
 **1. cat /etc/td-agent/td-agent.conf**
```
<system>
  log_level debug
</system>
@include config.d/*.conf
```
**2. cat /etc/td-agent/config.d/kafka.conf**
```
<source>
  @type tail
  path /data1/td-agent/httpd-access.log
  pos_file /data1/td-agent/httpd-access.log.pos
  tag nginx.access
  #format nginx
  format none
</source>

<match nginx.access>
  @type copy
  <store>
    @type kafka_buffered

    # list of seed brokers
    brokers 10.13.88.190:9092,10.13.88.191:9092,10.13.88.193:9092,10.13.88.194:9092

    # buffer settings
    #buffer_type file
    buffer_type memory
    #buffer_path /data1/td-agent/buffer/td
    flush_interval 3s

    # topic settings
    default_topic fluented_from_neo4j003

    # data type settings
    output_data_type json
    compression_codec gzip

    # producer settings
    max_send_retries 1
    required_acks -1
  </store>
  <store>
    @type file
    path /data1/td-agent/fluented_from_neo4j003.outfile
  </store>
</match>
```
**here is the errors **
```
2019-04-16 16:34:18 +0800 [debug]: #0 3 messages send.
2019-04-16 16:34:18 +0800 [warn]: #0 Send exception occurred: Could not connect to any of the seed brokers:
- kafka://10.13.88.190:9092: Connection error EOFError: EOFError
- kafka://10.13.88.191:9092: Connection error EOFError: EOFError
- kafka://10.13.88.193:9092: Connection error EOFError: EOFError
- kafka://10.13.88.194:9092: Connection error EOFError: EOFError
2019-04-16 16:34:18 +0800 [warn]: #0 Exception Backtrace : /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.6/lib/kafka/cluster.rb:396:in `fetch_cluster_info'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.6/lib/kafka/cluster.rb:350:in `cluster_info'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.6/lib/kafka/cluster.rb:98:in `refresh_metadata!'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.6/lib/kafka/cluster.rb:52:in `add_target_topics'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.6/lib/kafka/producer.rb:361:in `deliver_messages_with_retries'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.6/lib/kafka/producer.rb:251:in `block in deliver_messages'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.6/lib/kafka/instrumenter.rb:23:in `instrument'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.6/lib/kafka/producer.rb:244:in `deliver_messages'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kafka-0.9.2/lib/fluent/plugin/out_kafka_buffered.rb:286:in `deliver_messages'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kafka-0.9.2/lib/fluent/plugin/out_kafka_buffered.rb:349:in `write'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/compat/output.rb:131:in `write'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/plugin/output.rb:1123:in `try_flush'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/plugin/output.rb:1423:in `flush_thread_run'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/plugin/output.rb:452:in `block (2 levels) in start'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-04-16 16:34:18 +0800 [info]: #0 initialized kafka producer: kafka
2019-04-16 16:34:18 +0800 [debug]: #0 taking back chunk for errors. chunk="586a19e75010951485dc4b5ddf156692"
2019-04-16 16:34:18 +0800 [warn]: #0 failed to flush the buffer. retry_time=7 next_retry_seconds=2019-04-16 16:35:16 +0800 chunk="586a19e75010951485dc4b5ddf156692" error_class=Kafka::ConnectionError error="Could not connect to any of the seed brokers:\n- kafka://10.13.88.190:9092: Connection error EOFError: EOFError\n- kafka://10.13.88.191:9092: Connection error EOFError: EOFError\n- kafka://10.13.88.193:9092: Connection error EOFError: EOFError\n- kafka://10.13.88.194:9092: Connection error EOFError: EOFError"
  2019-04-16 16:34:18 +0800 [warn]: #0 suppressed same stacktrace
```

**Comment by repeatedly** [comment]
Maybe kafka 0.9.0 is not supported by latest ruby-kafka: https://github.com/zendesk/ruby-kafka#compatibility
You need to downgrade ruby-kafka and fluent-plugin-kafka or upgrade your oldest kafka cluster.

**Comment by wanghonglei5181** [comment]
@repeatedly    
which version ?   ruby-kafka-0.4.4? fluent-plugin-kafka0.6.9

**Comment by wanghonglei5181** [comment]
i have  downgraded ruby-kafka and fluent-plugin-kafka to 0.4.4 and 0.7.9,  found errors below
```
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.4.4/lib/kafka/client.rb:53:in `initialize'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.4.4/lib/kafka.rb:233:in `new'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.4.4/lib/kafka.rb:233:in `new'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kafka-0.7.9/lib/fluent/plugin/out_kafka_buffered.rb:135:in `refresh_client'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kafka-0.7.9/lib/fluent/plugin/out_kafka_buffered.rb:203:in `start'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/compat/call_super_mixin.rb:42:in `start'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/root_agent.rb:165:in `block in start'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/root_agent.rb:154:in `block (2 levels) in lifecycle'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/root_agent.rb:153:in `each'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/root_agent.rb:153:in `block in lifecycle'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/root_agent.rb:140:in `each'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/root_agent.rb:140:in `lifecycle'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/root_agent.rb:164:in `start'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/engine.rb:274:in `start'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/engine.rb:219:in `run'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/supervisor.rb:799:in `run_engine'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/supervisor.rb:549:in `block in run_worker'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/supervisor.rb:724:in `main_process'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/supervisor.rb:544:in `run_worker'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/bin/fluentd:8:in `<top (required)>'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/bin/fluentd:23:in `load'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/bin/fluentd:23:in `<main>'
2019-04-16 17:16:13 +0800 [error]: #0 unexpected error error_class=ArgumentError error="unknown keyword: ssl_ca_certs_from_system"
  2019-04-16 17:16:13 +0800 [error]: #0 suppressed same stacktrace
2019-04-16 17:16:13 +0800 [info]: fluent/log.rb:322:info: Worker 0 finished unexpectedly with status 1
2019-04-16 17:16:13 +0800 [info]: gem 'fluent-plugin-elasticsearch' version '3.0.1'
2019-04-16 17:16:13 +0800 [info]: gem 'fluent-plugin-grep' version '0.3.4'
2019-04-16 17:16:13 +0800 [info]: gem 'fluent-plugin-kafka' version '0.7.9'
2019-04-16 17:16:13 +0800 [info]: gem 'fluent-plugin-record-modifier' version '1.1.0'
2019-04-16 17:16:13 +0800 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.1.1'
2019-04-16 17:16:13 +0800 [info]: gem 'fluent-plugin-s3' version '1.1.7'
2019-04-16 17:16:13 +0800 [info]: gem 'fluent-plugin-td' version '1.0.0'
2019-04-16 17:16:13 +0800 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.4'
2019-04-16 17:16:13 +0800 [info]: gem 'fluent-plugin-webhdfs' version '1.2.3'
2019-04-16 17:16:13 +0800 [info]: gem 'fluentd' version '1.3.3'
2019-04-16 17:16:13 +0800 [info]: adding match pattern="nginx.access" type="copy"
2019-04-16 17:16:13 +0800 [debug]: #0 adding store type="kafka_buffered"
2019-04-16 17:16:13 +0800 [info]: #0 brokers has been set directly: ["10.13.88.190:9092", "10.13.88.191:9092", "10.13.88.193:9092", "10.13.88.194:9092"]
2019-04-16 17:16:13 +0800 [debug]: #0 adding store type="file"
2019-04-16 17:16:13 +0800 [info]: adding source type="tail"
2019-04-16 17:16:13 +0800 [info]: #0 starting fluentd worker pid=17918 ppid=15326 worker=0
2019-04-16 17:16:13 +0800 [debug]: #0 buffer started instance=70181297332740 stage_size=315324 queue_size=0
2019-04-16 17:16:13 +0800 [debug]: #0 flush_thread actually running
2019-04-16 17:16:13 +0800 [debug]: #0 buffer started instance=70181311138640 stage_size=0 queue_size=0
2019-04-16 17:16:13 +0800 [debug]: #0 enqueue_thread actually running
2019-04-16 17:16:13 +0800 [error]: #0 unexpected error error_class=ArgumentError error="unknown keyword: ssl_ca_certs_from_system"
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.4.4/lib/kafka/client.rb:53:in `initialize'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.4.4/lib/kafka.rb:233:in `new'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.4.4/lib/kafka.rb:233:in `new'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kafka-0.7.9/lib/fluent/plugin/out_kafka_buffered.rb:135:in `refresh_client'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kafka-0.7.9/lib/fluent/plugin/out_kafka_buffered.rb:203:in `start'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/compat/call_super_mixin.rb:42:in `start'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/root_agent.rb:165:in `block in start'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/root_agent.rb:154:in `block (2 levels) in lifecycle'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/root_agent.rb:153:in `each'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/root_agent.rb:153:in `block in lifecycle'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/root_agent.rb:140:in `each'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/root_agent.rb:140:in `lifecycle'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/root_agent.rb:164:in `start'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/engine.rb:274:in `start'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/engine.rb:219:in `run'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/supervisor.rb:799:in `run_engine'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/supervisor.rb:549:in `block in run_worker'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/supervisor.rb:724:in `main_process'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/supervisor.rb:544:in `run_worker'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/bin/fluentd:8:in `<top (required)>'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/bin/fluentd:23:in `load'
  2019-04-16 17:16:13 +0800 [error]: #0 /opt/td-agent/embedded/bin/fluentd:23:in `<main>'
2019-04-16 17:16:13 +0800 [error]: #0 unexpected error error_class=ArgumentError error="unknown keyword: ssl_ca_certs_from_system"
  2019-04-16 17:16:13 +0800 [error]: #0 suppressed same stacktrace
2019-04-16 17:16:13 +0800 [info]: fluent/log.rb:322:info: Worker 0 finished unexpectedly with status 1

```

**Comment by wanghonglei5181** [comment]
yes  
it works at
fluent-plugin-kafka (0.6.6)
ruby-kafka (0.4.4)

**Comment by repeatedly** [comment]
ok. closed the issue. BTW, kafka 0.9.0 is dead version so we recommend to upgrade the version to recent.
