### ISSUE TITLE
kafka group and cef format raise error: "undefined method call for nil:NilClass"

### ISSUE THREAD

**Issue by paerlundgren** [fluent/fluent-plugin-kafka#254]
Having issue with reading from kafka topic and parsing messages in CEF format.

Source configuration looks like this:
```
<source>
  @type kafka_group
  brokers <some ip>:<some port>
  consumer_group <some group>
  topics <some topic>
  start_from_beginning false
  format cef
</source>
```

Also tried with `parse_strict_mode false`, no difference.

From trace:
```
fluentd    | 2019-04-29 05:58:04 +0000 [warn]: #0 parser error in <some topic>/0 error="undefined method `call' for nil:NilClass" value="CEF:0|..." offset=9014017
fluentd    |   2019-04-29 05:58:04 +0000 [debug]: #0 /usr/local/lib/ruby/gems/2.6.0/gems/fluent-plugin-kafka-0.9.2/lib/fluent/plugin/in_kafka_group.rb:226:in `block (2 levels) in run'
fluentd    |   2019-04-29 05:58:04 +0000 [debug]: #0 /usr/local/lib/ruby/gems/2.6.0/gems/fluent-plugin-kafka-0.9.2/lib/fluent/plugin/in_kafka_group.rb:224:in `each'
fluentd    |   2019-04-29 05:58:04 +0000 [debug]: #0 /usr/local/lib/ruby/gems/2.6.0/gems/fluent-plugin-kafka-0.9.2/lib/fluent/plugin/in_kafka_group.rb:224:in `block in run'
fluentd    |   2019-04-29 05:58:04 +0000 [debug]: #0 /usr/local/lib/ruby/gems/2.6.0/gems/ruby-kafka-0.7.6/lib/kafka/consumer.rb:322:in `block (3 levels) in each_batch'
fluentd    |   2019-04-29 05:58:04 +0000 [debug]: #0 /usr/local/lib/ruby/gems/2.6.0/gems/ruby-kafka-0.7.6/lib/kafka/instrumenter.rb:23:in `instrument'
fluentd    |   2019-04-29 05:58:04 +0000 [debug]: #0 /usr/local/lib/ruby/gems/2.6.0/gems/ruby-kafka-0.7.6/lib/kafka/instrumenter.rb:35:in `instrument'
fluentd    |   2019-04-29 05:58:04 +0000 [debug]: #0 /usr/local/lib/ruby/gems/2.6.0/gems/ruby-kafka-0.7.6/lib/kafka/consumer.rb:320:in `block (2 levels) in each_batch'
fluentd    |   2019-04-29 05:58:04 +0000 [debug]: #0 /usr/local/lib/ruby/gems/2.6.0/gems/ruby-kafka-0.7.6/lib/kafka/consumer.rb:302:in `each'
fluentd    |   2019-04-29 05:58:04 +0000 [debug]: #0 /usr/local/lib/ruby/gems/2.6.0/gems/ruby-kafka-0.7.6/lib/kafka/consumer.rb:302:in `block in each_batch'
fluentd    |   2019-04-29 05:58:04 +0000 [debug]: #0 /usr/local/lib/ruby/gems/2.6.0/gems/ruby-kafka-0.7.6/lib/kafka/consumer.rb:404:in `block in consumer_loop'
fluentd    |   2019-04-29 05:58:04 +0000 [debug]: #0 /usr/local/lib/ruby/gems/2.6.0/gems/ruby-kafka-0.7.6/lib/kafka/instrumenter.rb:23:in `instrument'
fluentd    |   2019-04-29 05:58:04 +0000 [debug]: #0 /usr/local/lib/ruby/gems/2.6.0/gems/ruby-kafka-0.7.6/lib/kafka/instrumenter.rb:35:in `instrument'
fluentd    |   2019-04-29 05:58:04 +0000 [debug]: #0 /usr/local/lib/ruby/gems/2.6.0/gems/ruby-kafka-0.7.6/lib/kafka/consumer.rb:403:in `consumer_loop'
fluentd    |   2019-04-29 05:58:04 +0000 [debug]: #0 /usr/local/lib/ruby/gems/2.6.0/gems/ruby-kafka-0.7.6/lib/kafka/consumer.rb:299:in `each_batch'
fluentd    |   2019-04-29 05:58:04 +0000 [debug]: #0 /usr/local/lib/ruby/gems/2.6.0/gems/fluent-plugin-kafka-0.9.2/lib/fluent/plugin/in_kafka_group.rb:218:in `run'
```
Content of value is replaced with `...` above.

Reading from topic with format set to `text` works.

System:
Running docker on ubuntu 18.04 with base image fluent/fluentd:v1.4-debian-2 and gems installed on top.

**Comment by repeatedly** [comment]
> Reading from topic with format set to text works.

if so, `cef` parser seems to have a problem.

**Comment by kenhys** [comment]
Closed because of https://github.com/fluent/fluent-plugin-kafka/issues/254#issuecomment-490792843
