### ISSUE TITLE
NoMethodError: undefined method `merge'

### ISSUE THREAD

**Issue by toughrogrammer** [fluent/fluent-plugin-kafka#275]
I suddenly got errors like below since few times ago. 
Only specific topic throws these errors.
My kafka broker version is 2.2.0, and message format version is 2.1.

```
Exception raised when processing ${topic_name}/99 in offset range 334766839..334773586 -- NoMethodError: undefined method `merge' for #<String:0x00007f4fb2fcf770>
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-prometheus-1.4.0/lib/fluent/plugin/prometheus.rb:78:in `block in instrument'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.5.2/lib/fluent/event.rb:193:in `block in each'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.5.2/lib/fluent/event.rb:192:in `each'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.5.2/lib/fluent/event.rb:192:in `each'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-prometheus-1.4.0/lib/fluent/plugin/prometheus.rb:77:in `instrument'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-prometheus-1.4.0/lib/fluent/plugin/filter_prometheus.rb:25:in `filter_stream'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.5.2/lib/fluent/event_router.rb:177:in `block in filter_stream'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.5.2/lib/fluent/event_router.rb:177:in `each'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.5.2/lib/fluent/event_router.rb:177:in `reduce'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.5.2/lib/fluent/event_router.rb:177:in `filter_stream'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.5.2/lib/fluent/event_router.rb:158:in `emit_events'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.5.2/lib/fluent/event_router.rb:96:in `emit_stream'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kafka-0.9.6/lib/fluent/plugin/in_kafka_group.rb:269:in `emit_events'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kafka-0.9.6/lib/fluent/plugin/in_kafka_group.rb:251:in `block in run'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.8/lib/kafka/consumer.rb:322:in `block (3 levels) in each_batch'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.8/lib/kafka/instrumenter.rb:23:in `instrument'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.8/lib/kafka/instrumenter.rb:35:in `instrument'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.8/lib/kafka/consumer.rb:320:in `block (2 levels) in each_batch'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.8/lib/kafka/consumer.rb:302:in `each'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.8/lib/kafka/consumer.rb:302:in `block in each_batch'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.8/lib/kafka/consumer.rb:404:in `block in consumer_loop'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.8/lib/kafka/instrumenter.rb:23:in `instrument'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.8/lib/kafka/instrumenter.rb:35:in `instrument'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.8/lib/kafka/consumer.rb:403:in `consumer_loop'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.8/lib/kafka/consumer.rb:299:in `each_batch'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kafka-0.9.6/lib/fluent/plugin/in_kafka_group.rb:222:in `run'
```

Here is my td agent configuration.

```
<source>
  @type kafka_group

  brokers ${broker_address}
  consumer_group fluentd
  topics ${topic_name}
  format json
  add_prefix kafka
  retry_emit_limit 5

  # ruby-kafka consumer options
  max_bytes 10485760
  max_wait_time 10
  min_bytes 1
  offset_commit_interval 10s
  offset_commit_threshold 1000
  fetcher_max_queue_size 1 # low value to resolve memory pressure
  start_from_beginning true
</source>
```

**Comment by repeatedly** [comment]
From the code, the value should be Hash object: https://github.com/fluent/fluent-plugin-prometheus/blob/050c47a0fd2f993b91381edf232776e249dfa70c/lib/fluent/plugin/prometheus.rb#L78
You use json format in `kafka_group` so it accepts String type, not only Hash.
You need to check actual value to investigate the problem.
