### ISSUE TITLE
Connection error EOFError: EOFError

### ISSUE THREAD

**Issue by lw8008** [fluent/fluent-plugin-kafka#289]
Version of Ruby: ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
Version of Kafka: 1.2.1.0
Version of fluentd: 1.6.3
Version of ruby-kafka: 0.7.10
Version of fluent-plugin-kafka: 0.11.1

fluentd output conf:
```
       @type kafka2
       @log_level debug
       brokers 31.67.159.7:9092,31.67.159.8:9092,31.67.159.9:9092
       use_event_time true
       topic_key ctest
       <format>
          @type json
       </format>
```

See Error Log as below:
```
2019-08-28 09:54:11 +0000 [info]: [dnskafkalog] brokers has been set: ["31.67.159.7:9092", "31.67.159.8:9092", "31.67.159.9:9092"]
2019-08-28 09:54:12 +0000 [debug]: [dnskafkalog] buffer started instance=70321520772000 stage_size=0 queue_size=0
2019-08-28 09:54:12 +0000 [info]: [dnskafkalog] initialized kafka producer: fluentd
2019-08-28 09:54:12 +0000 [debug]: [dnskafkalog] flush_thread actually running
2019-08-28 09:54:12 +0000 [debug]: [dnskafkalog] flush_thread actually running
2019-08-28 09:54:12 +0000 [debug]: [dnskafkalog] enqueue_thread actually running
2019-08-28 09:54:27 +0000 [warn]: [dnskafkalog] Send exception occurred: Could not connect to any of the seed brokers:
- kafka://31.67.159.8:9092: Connection error EOFError: EOFError
- kafka://31.67.159.7:9092: Connection error EOFError: EOFError
- kafka://31.67.159.9:9092: Connection error EOFError: EOFError
2019-08-28 09:54:27 +0000 [warn]: [dnskafkalog] Exception Backtrace : /var/lib/gems/2.3.0/gems/ruby-kafka-0.7.10/lib/kafka/cluster.rb:396:in `fetch_cluster_info'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.7.10/lib/kafka/cluster.rb:350:in `cluster_info'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.7.10/lib/kafka/cluster.rb:98:in `refresh_metadata!'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.7.10/lib/kafka/cluster.rb:52:in `add_target_topics'
/var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.11.1/lib/fluent/plugin/kafka_producer_ext.rb:91:in `initialize'
/var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.11.1/lib/fluent/plugin/kafka_producer_ext.rb:60:in `new'
/var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.11.1/lib/fluent/plugin/kafka_producer_ext.rb:60:in `topic_producer'
/var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.11.1/lib/fluent/plugin/out_kafka2.rb:227:in `write'
/var/lib/gems/2.3.0/gems/fluentd-1.6.3/lib/fluent/plugin/output.rb:1128:in `try_flush'
/var/lib/gems/2.3.0/gems/fluentd-1.6.3/lib/fluent/plugin/output.rb:1434:in `flush_thread_run'
/var/lib/gems/2.3.0/gems/fluentd-1.6.3/lib/fluent/plugin/output.rb:457:in `block (2 levels) in start'
/var/lib/gems/2.3.0/gems/fluentd-1.6.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-08-28 09:54:27 +0000 [info]: [dnskafkalog] initialized kafka producer: fluentd
2019-08-28 09:54:27 +0000 [debug]: [dnskafkalog] taking back chunk for errors. chunk="5912a5f107807db4e2447c7cd4c635ae"
2019-08-28 09:54:27 +0000 [warn]: [dnskafkalog] failed to flush the buffer. retry_time=0 next_retry_seconds=2019-08-28 09:54:28 +0000 chunk="5912a5f107807db4e2447c7cd4c635ae" error_class=Kafka::ConnectionError error="Could not connect to any of the seed brokers:\n- kafka://31.67.159.8:9092: Connection error EOFError: EOFError\n- kafka://31.67.159.7:9092: Connection error EOFError: EOFError\n- kafka://31.67.159.9:9092: Connection error EOFError: EOFError"
  2019-08-28 09:54:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.7.10/lib/kafka/cluster.rb:396:in `fetch_cluster_info'
  2019-08-28 09:54:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.7.10/lib/kafka/cluster.rb:350:in `cluster_info'
  2019-08-28 09:54:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.7.10/lib/kafka/cluster.rb:98:in `refresh_metadata!'
  2019-08-28 09:54:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.7.10/lib/kafka/cluster.rb:52:in `add_target_topics'
  2019-08-28 09:54:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.11.1/lib/fluent/plugin/kafka_producer_ext.rb:91:in `initialize'
  2019-08-28 09:54:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.11.1/lib/fluent/plugin/kafka_producer_ext.rb:60:in `new'
  2019-08-28 09:54:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.11.1/lib/fluent/plugin/kafka_producer_ext.rb:60:in `topic_producer'
  2019-08-28 09:54:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.11.1/lib/fluent/plugin/out_kafka2.rb:227:in `write'
  2019-08-28 09:54:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.6.3/lib/fluent/plugin/output.rb:1128:in `try_flush'
  2019-08-28 09:54:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.6.3/lib/fluent/plugin/output.rb:1434:in `flush_thread_run'
  2019-08-28 09:54:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.6.3/lib/fluent/plugin/output.rb:457:in `block (2 levels) in start'
  2019-08-28 09:54:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.6.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'

```

Is it due to ruby_kafka version?

**Comment by repeatedly** [comment]
> Is it due to ruby_kafka version?

I'm not sure. Please check other ruby-kafka version, v0.6, v0.5, ....

**Comment by lw8008** [comment]
works with old kafka versions. thanks

**Comment by Charith32** [comment]
I am facing the same issue as this. What old versions of ruby-kafka or kafka was used to correct this?

**Comment by lw8008** [comment]
kafka 0.8 or 0.9 works

**Comment by Charith32** [comment]
Hi, I downgraded the plugins as below.
 fluent-plugin-kafka 0.6.6
 ruby-kafka 0.4.4
 kafka 0.8
I am still getting the same error as yours. Any other suggestions?

**Comment by Charith32** [comment]
Hi, I figured this out. In the configuration, I've added `topic_key test`, I removed this and added `default_topic test`. Now everything works as expected even in the newer versions of fluent-plugin-kafka,ruby-kafka and kafka.

**Comment by lw8008** [comment]
I use default_topic but not works for other versions. i will test again next time. thanks

**Comment by jigetage** [comment]
> Hi, I figured this out. In the configuration, I've added `topic_key test`, I removed this and added `default_topic test`. Now everything works as expected even in the newer versions of fluent-plugin-kafka,ruby-kafka and kafka.

bro, u r right
