### ISSUE TITLE
Send exception occurred. Failed to send messages to <topic>

### ISSUE THREAD

**Issue by satyatumati** [fluent/fluent-plugin-kafka#292]
I am trying to send json messages to kafka 2.2.1 cluster
Using fluentd version 1.6

I am using the following section 
```<match **>
      @type kafka2
      brokers b-3.livelogs.ducjzu.c1.kafka.us-east-1.amazonaws.com:9092,b-2.livelogs.ducjzu.c1.kafka.us-east-1.amazonaws.com:9092,b-1.livelogs.ducjzu.c1.kafka.us-east-1.amazonaws.com:9092
      default_topic livelogs-es
       <format>
        @type json
      </format>
      
    </match>
```

```
#0 Send exception occurred: Failed to send messages to livelogs-es/0
 #0 Send exception occurred: Failed to send messages to livelogs-es/0

 #0 Exception Backtrace : /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kafka-0.10.0/lib/fluent/plugin/kafka_producer_ext.rb:244:in `deliver_messages_with_retries'
 #0 Exception Backtrace : /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kafka-0.10.0/lib/fluent/plugin/kafka_producer_ext.rb:244:in `deliver_messages_with_retries'
 #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2019-09-25 21:34:43 +0000 chunk="5936767b7d59075fc3161a9a5ce7b9c8" error_class=Kafka::DeliveryFailed error="Failed to send messages to livelogs-es/0"
 #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kafka-0.10.0/lib/fluent/plugin/kafka_producer_ext.rb:244:in `deliver_messages_with_retries'

14:34:42
 #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kafka-0.10.0/lib/fluent/plugin/kafka_producer_ext.rb:130:in `deliver_messages'
 #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kafka-0.10.0/lib/fluent/plugin/kafka_producer_ext.rb:130:in `deliver_messages'
 #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kafka-0.10.0/lib/fluent/plugin/out_kafka2.rb:237:in `write'
 #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/fluent/plugin/output.rb:1128:in `try_flush'
 #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/fluent/plugin/output.rb:1434:in `flush_thread_run'
 #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/fluent/plugin/output.rb:457:in `block (2 levels) in start'
 #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```
I tried using `kafka_buffered` as well. It kept throwing similar errors when trying to flush the buffer

My sample message looks like this

```
{"Uuid":"a91167d8-f9c6-4300-a33c-3bea00657b89","Timestamp":"2019-09-25T16:36:22","Type":"log4j","Logger":"JLOg","Severity":7,"Payload":"Completed task ","EnvVersion":"","Pid":12749,"Hostname":"*****","ClusterUuid":"new-cluster","Version":"5.1.0~DA1-7554","JobId":"CREATE_VMWARE:::0","Class":"job.ABC.com","Thread":"job-executor-9"}
```

**Comment by satyatumati** [comment]
@repeatedly Let me know if you need anymore env details.

**Comment by repeatedly** [comment]
> if you need anymore env details. :)

I can't help you from myside because your configuration works on my test environment.
So the problem seems the outside of fluent-plugin-kafka.

**Comment by styshoo** [comment]
I've seen this before, the fluentd configuration has nothing wrong.
The reason is your kafka doesn't set listeners with IP, maybe it use default setting.
`listeners=PLAINTEXT://:9092`
so, when ruby-kafka asks for kafka metadata, it returns domain name instead of IP. And, ruby-kafka can't connect kafka with domain name.

**Solution**: set kafka listeners with exact IP, maybe it will fix this.
`listeners=PLAINTEXT://<your kafka server IP>:9092`

You can turn on get_kafka_client_log of fluent-plugin-kafka plugin, to figure out what is going on.
```
<match **>
        @type kafka2
        @log_level trace
        get_kafka_client_log true
...
</match>
```

**Comment by kenhys** [comment]
See https://github.com/fluent/fluent-plugin-kafka/issues/292#issuecomment-634380050
