### ISSUE TITLE
Could not connect to broker: Connection error EOFError: EOFError

### ISSUE THREAD

**Issue by YaoZengzeng** [fluent/fluent-plugin-kafka#295]
I use the fluent-plugin-kafka to forward logs from fluentd to kafka, but always encounter the following problems.

```
2019-10-18 10:19:47 +0800 [info]: #0 New topics added to target list: TEST_DATA_LOG
2019-10-18 10:19:47 +0800 [info]: #0 Fetching cluster metadata from kafka://192.168.0.243:9092
2019-10-18 10:19:47 +0800 [info]: #0 Discovered cluster metadata; nodes: 192.168.0.225:9092 (node_id=2), 192.168.0.243:9092 (node_id=1), 192.168.0.55:9092 (node_id=0)
2019-10-18 10:19:47 +0800 [info]: #0 Sending 1 messages to 192.168.0.55:9092 (node_id=0)
2019-10-18 10:19:47 +0800 [error]: #0 Could not connect to broker 192.168.0.55:9092 (node_id=0): Connection error EOFError: EOFError
2019-10-18 10:19:47 +0800 [warn]: #0 Failed to send all messages; attempting retry 1 of 2 after 1s
2019-10-18 10:19:48 +0800 [info]: #0 Fetching cluster metadata from kafka://192.168.0.55:9092
2019-10-18 10:19:48 +0800 [info]: #0 Discovered cluster metadata; nodes: 192.168.0.225:9092 (node_id=2), 192.168.0.243:9092 (node_id=1), 192.168.0.55:9092 (node_id=0)
2019-10-18 10:19:48 +0800 [info]: #0 Sending 1 messages to 192.168.0.55:9092 (node_id=0)
2019-10-18 10:19:48 +0800 [error]: #0 Could not connect to broker 192.168.0.55:9092 (node_id=0): Connection error EOFError: EOFError
2019-10-18 10:19:48 +0800 [warn]: #0 Failed to send all messages; attempting retry 2 of 2 after 1s
2019-10-18 10:19:49 +0800 [info]: #0 Fetching cluster metadata from kafka://192.168.0.243:9092
2019-10-18 10:19:49 +0800 [info]: #0 Discovered cluster metadata; nodes: 192.168.0.225:9092 (node_id=2), 192.168.0.243:9092 (node_id=1), 192.168.0.55:9092 (node_id=0)
2019-10-18 10:19:49 +0800 [info]: #0 Sending 1 messages to 192.168.0.55:9092 (node_id=0)
2019-10-18 10:19:49 +0800 [error]: #0 Could not connect to broker 192.168.0.55:9092 (node_id=0): Connection error EOFError: EOFError
2019-10-18 10:19:49 +0800 [error]: #0 Failed to send all messages; keeping remaining messages in buffer
2019-10-18 10:19:49 +0800 [warn]: #0 Send exception occurred: Failed to send messages to TEST_DATA_LOG/0
2019-10-18 10:19:49 +0800 [warn]: #0 Exception Backtrace : /usr/local/bundle/gems/fluent-plugin-kafka-0.12.1/lib/fluent/plugin/kafka_producer_ext.rb:240:in `deliver_messages_with_retries'
/usr/local/bundle/gems/fluent-plugin-kafka-0.12.1/lib/fluent/plugin/kafka_producer_ext.rb:126:in `deliver_messages'
/usr/local/bundle/gems/fluent-plugin-kafka-0.12.1/lib/fluent/plugin/out_kafka2.rb:265:in `write'
/usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.6.0/lib/fluent/plugin/output.rb:1127:in `try_flush'
/usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.6.0/lib/fluent/plugin/output.rb:1433:in `flush_thread_run'
/usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.6.0/lib/fluent/plugin/output.rb:456:in `block (2 levels) in start'
/usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.6.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-10-18 10:19:49 +0800 [info]: #0 initialized kafka producer: fluentd
2019-10-18 10:19:49 +0800 [info]: #0 Disconnecting broker 0
2019-10-18 10:19:49 +0800 [warn]: #0 failed to flush the buffer. retry_time=8 next_retry_seconds=2019-10-18 10:21:58 +0800 chunk="59525eeba60357de06e8356242323e83" error_class=Kafka::DeliveryFailed error="Failed to send messages to TEST_DATA_LOG/0"
```

It seems that we could connect to the kafka cluster, but the brokers will kill the connections?

And my configuration for fluentd as follows:

```
  fluent.conf: |-
    <system>
      workers 1
      rpc_endpoint 127.0.0.1:24444
    </system>

    <source>
      @type dummy
      dummy {"hello":"world"}
      tag app.test
    </source>

    <match app.**>
      @type kafka2

      brokers 192.168.0.225:9092,192.168.0.243:9092,192.168.0.55:9092
      default_topic TEST_DATA_LOG
      get_kafka_client_log true

      <format>
        @type json
      </format>

      <buffer topic>
        flush_interval 1s
      </buffer>
    </match>
```

The version of fluent-plugin-kafka is `0.12.1`

**Comment by ganmacs** [comment]
> It seems that we could connect to the kafka cluster, 

Could you tell us how you confirmed it?

**Comment by YaoZengzeng** [comment]
```
2019-10-18 10:19:47 +0800 [info]: #0 Fetching cluster metadata from kafka://192.168.0.243:9092
2019-10-18 10:19:47 +0800 [info]: #0 Discovered cluster metadata; nodes: 192.168.0.225:9092 (node_id=2), 192.168.0.243:9092 (node_id=1), 192.168.0.55:9092 (node_id=0)
```

The  log include above content :)

**Comment by repeatedly** [comment]
If your kafka version is old, please upgrade kafka vesion or downgrade ruby-kafka/fluent-plugin-kafka version.

**Comment by YaoZengzeng** [comment]
```
[root@zk03 ~]# ps aux | grep kafka
root     12850  0.0  0.0 112712   964 pts/2    S+   10:39   0:00 grep --color=auto kafka
hadoop   29354  0.4  6.6 8013112 1075720 ?     Sl   Oct16  12:04 /usr/local/jdk/bin/java -Xmx1G -Xms1G -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:+DisableExplicitGC -Djava.awt.headless=true -Xloggc:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../logs/kafkaServer-gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dkafka.logs.dir=/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../logs -Dlog4j.configuration=file:bin/../config/log4j.properties -cp :/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/aopalliance-repackaged-2.5.0-b05.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/argparse4j-0.7.0.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/connect-api-0.10.2.1.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/connect-file-0.10.2.1.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/connect-json-0.10.2.1.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/connect-runtime-0.10.2.1.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/connect-transforms-0.10.2.1.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/guava-18.0.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/hk2-api-2.5.0-b05.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/hk2-locator-2.5.0-b05.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/hk2-utils-2.5.0-b05.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/jackson-annotations-2.8.0.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/jackson-annotations-2.8.5.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/jackson-core-2.8.5.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/jackson-databind-2.8.5.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/jackson-jaxrs-base-2.8.5.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/jackson-jaxrs-json-provider-2.8.5.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/jackson-module-jaxb-annotations-2.8.5.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/javassist-3.20.0-GA.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/javax.annotation-api-1.2.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/javax.inject-1.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/javax.inject-2.5.0-b05.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/javax.servlet-api-3.1.0.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/javax.ws.rs-api-2.0.1.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/jersey-client-2.24.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/jersey-common-2.24.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/jersey-container-servlet-2.24.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/jersey-container-servlet-core-2.24.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/jersey-guava-2.24.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/jersey-media-jaxb-2.24.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/jersey-server-2.24.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/jetty-continuation-9.2.15.v20160210.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/jetty-http-9.2.15.v20160210.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/jetty-io-9.2.15.v20160210.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/jetty-security-9.2.15.v20160210.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/jetty-server-9.2.15.v20160210.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/jetty-servlet-9.2.15.v20160210.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/jetty-servlets-9.2.15.v20160210.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/jetty-util-9.2.15.v20160210.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/jopt-simple-5.0.3.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/kafka_2.11-0.10.2.1.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/kafka_2.11-0.10.2.1-sources.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/kafka_2.11-0.10.2.1-test-sources.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/kafka-clients-0.10.2.1.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/kafka-log4j-appender-0.10.2.1.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/kafka-streams-0.10.2.1.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/kafka-streams-examples-0.10.2.1.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/kafka-tools-0.10.2.1.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/log4j-1.2.17.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/lz4-1.3.0.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/metrics-core-2.2.0.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/osgi-resource-locator-1.0.1.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/reflections-0.9.10.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/rocksdbjni-5.0.1.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/scala-library-2.11.8.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/scala-parser-combinators_2.11-1.0.4.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/slf4j-api-1.7.21.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/slf4j-log4j12-1.7.21.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/snappy-java-1.1.2.6.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/validation-api-1.1.0.Final.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/zkclient-0.10.jar:/home/hadoop/apps/kafka_2.11-0.10.2.1/bin/../libs/zookeeper-3.4.9.jar kafka.Kafka config/server.properties
```

So my kafka version is 0.10.2? And my ruby-kafka/fluent-plugin-kafka version is 0.12.1 which released 3 days ago. Maybe it's too new?

**Comment by repeatedly** [comment]
See: https://github.com/zendesk/ruby-kafka#compatibility

**Comment by neilcx** [comment]
Any Update on this issue ?

I am using 
- Kafka 2.2 
-  fluent-plugin-kafka 0.12.1
- ruby-kafka 0.7.10

And I got this error:

```
2020-11-17 06:29:51 +0000 [error]: #0 Failed to fetch metadata from kafka://kk-cx-kafka-outer-svc.ins:9092: SASL PLAIN authentication failed: EOFError
2020-11-17 06:29:51 +0000 [warn]: #0 Send exception occurred: Could not connect to any of the seed brokers:
- kafka://kk-cx-kafka-outer-svc.ins:9092: SASL PLAIN authentication failed: EOFError
```
