### ISSUE TITLE
plugin parse error 

### ISSUE THREAD

**Issue by ZMMWMY** [fluent/fluent-plugin-kafka#299]
hello ,there is a problem, I don't know how to solve it.
This is the exception log
```
fluent_1     | 2019-11-20 04:11:22 +0000 [warn]: #0 fluent/log.rb:342:warn: parser error in commander.prod/2 error="unexpected characters after the JSON document at line 1, column 4 [parse.c:611] in '2019-11-20 12:11:09.736  INFO 1 --- [ntainer#2-0-C-1] c.s.log.commander.runner.MonitorRunner   : \u5F00\u59CB\u8BA1\u6570isv\u8BF7\u6C42\u5F02\u5E38\n" value="2019-11-20 12:11:09.736  INFO 1 --- [ntainer#2-0-C-1] c.s.log.commander.runner.MonitorRunner   : \xE5\xBC\x80\xE5\xA7\x8B\xE8\xAE\xA1\xE6\x95\xB0isv\xE8\xAF\xB7\xE6\xB1\x82\xE5\xBC\x82\xE5\xB8\xB8\n" offset=122742
fluent_1     |   2019-11-20 04:11:22 +0000 [debug]: #0 plugin/in_kafka_group.rb:235:block in run: /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kafka-0.12.1/lib/fluent/plugin/in_kafka_group.rb:145:in `load'
fluent_1     |   2019-11-20 04:11:22 +0000 [debug]: #0 plugin/in_kafka_group.rb:235:block in run: /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kafka-0.12.1/lib/fluent/plugin/in_kafka_group.rb:145:in `block in setup_parser'
fluent_1     |   2019-11-20 04:11:22 +0000 [debug]: #0 plugin/in_kafka_group.rb:235:block in run: /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kafka-0.12.1/lib/fluent/plugin/in_kafka_group.rb:237:in `block (2 levels) in run'
fluent_1     |   2019-11-20 04:11:22 +0000 [debug]: #0 plugin/in_kafka_group.rb:235:block in run: /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kafka-0.12.1/lib/fluent/plugin/in_kafka_group.rb:235:in `each'
fluent_1     |   2019-11-20 04:11:22 +0000 [debug]: #0 plugin/in_kafka_group.rb:235:block in run: /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kafka-0.12.1/lib/fluent/plugin/in_kafka_group.rb:235:in `block in run'
fluent_1     |   2019-11-20 04:11:22 +0000 [debug]: #0 plugin/in_kafka_group.rb:235:block in run: /usr/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.10/lib/kafka/consumer.rb:322:in `block (3 levels) in each_batch'
fluent_1     |   2019-11-20 04:11:22 +0000 [debug]: #0 plugin/in_kafka_group.rb:235:block in run: /usr/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.10/lib/kafka/instrumenter.rb:23:in `instrument'
fluent_1     |   2019-11-20 04:11:22 +0000 [debug]: #0 plugin/in_kafka_group.rb:235:block in run: /usr/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.10/lib/kafka/instrumenter.rb:35:in `instrument'
fluent_1     |   2019-11-20 04:11:22 +0000 [debug]: #0 plugin/in_kafka_group.rb:235:block in run: /usr/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.10/lib/kafka/consumer.rb:320:in `block (2 levels) in each_batch'
fluent_1     |   2019-11-20 04:11:22 +0000 [debug]: #0 plugin/in_kafka_group.rb:235:block in run: /usr/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.10/lib/kafka/consumer.rb:302:in `each'
fluent_1     |   2019-11-20 04:11:22 +0000 [debug]: #0 plugin/in_kafka_group.rb:235:block in run: /usr/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.10/lib/kafka/consumer.rb:302:in `block in each_batch'
fluent_1     |   2019-11-20 04:11:22 +0000 [debug]: #0 plugin/in_kafka_group.rb:235:block in run: /usr/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.10/lib/kafka/consumer.rb:404:in `block in consumer_loop'
fluent_1     |   2019-11-20 04:11:22 +0000 [debug]: #0 plugin/in_kafka_group.rb:235:block in run: /usr/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.10/lib/kafka/instrumenter.rb:23:in `instrument'
fluent_1     |   2019-11-20 04:11:22 +0000 [debug]: #0 plugin/in_kafka_group.rb:235:block in run: /usr/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.10/lib/kafka/instrumenter.rb:35:in `instrument'
fluent_1     |   2019-11-20 04:11:22 +0000 [debug]: #0 plugin/in_kafka_group.rb:235:block in run: /usr/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.10/lib/kafka/consumer.rb:403:in `consumer_loop'
fluent_1     |   2019-11-20 04:11:22 +0000 [debug]: #0 plugin/in_kafka_group.rb:235:block in run: /usr/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.10/lib/kafka/consumer.rb:299:in `each_batch'
fluent_1     |   2019-11-20 04:11:22 +0000 [debug]: #0 plugin/in_kafka_group.rb:235:block in run: /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kafka-0.12.1/lib/fluent/plugin/in_kafka_group.rb:229:in `run'
fluent_1     | 2019-11-20 04:11:22 +0000 [warn]: #0 fluent/log.rb:342:warn: parser error in commander.prod/2 error="unexpected characters after the JSON document at line 1, column 4 [parse.c:611] in '2019-11-20 12:11:09.764  INFO 1 --- [ntainer#2-0-C-1] c.s.log.commander.runner.MonitorRunner   : \u5F00\u59CB\u8BA1\u6570\u8D85\u65F6\u8BF7\u6C42\u5F02\u5E38\n" value="2019-11-20 12:11:09.764  INFO 1 --- [ntainer#2-0-C-1] c.s.log.commander.runner.MonitorRunner   : \xE5\xBC\x80\xE5\xA7\x8B\xE8\xAE\xA1\xE6\x95\xB0\xE8\xB6\x85\xE6\x97\xB6\xE8\xAF\xB7\xE6\xB1\x82\xE5\xBC\x82\xE5\xB8\xB8\n" offset=122743
fluent_1     |   2019-11-20 04:11:22 +0000 [debug]: #0 plugin/in_kafka_group.rb:235:block in run: suppressed same stacktrace
fluent_1     | 2019-11-20 04:11:22 +0000 [warn]: #0 fluent/log.rb:342:warn: parser error in commander.prod/2 error="unexpected characters after the JSON document at line 1, column 4 [parse.c:611] in '2019-11-20 12:11:12.828  WARN 1 --- [pool-5-thread-1] c.s.log.commander.runner.MonitorRunner   : apiName=songxiaocai.report.native.get\u57281\u5206\u949F\u5185,\u53D1\u751F\u4E863\u6B21\u8C03\u7528,\u5171\u8BA13\u6B21isv\u9519\u8BEF\uFF0C\u4E0D\u89E6\u53D1\u62A5\u8B66\n" value="2019-11-20 12:11:12.828  WARN 1 --- [pool-5-thread-1] c.s.log.commander.runner.MonitorRunner   : apiName=songxiaocai.report.native.get\xE5\x9C\xA81\xE5\x88\x86\xE9\x92\x9F\xE5\x86\x85,\xE5\x8F\x91\xE7\x94\x9F\xE4\xBA\x863\xE6\xAC\xA1\xE8\xB0\x83\xE7\x94\xA8,\xE5\x85\xB1\xE8\xAE\xA13\xE6\xAC\xA1isv\xE9\x94\x99\xE8\xAF\xAF\xEF\xBC\x8C\xE4\xB8\x8D\xE8\xA7\xA6\xE5\x8F\x91\xE6\x8A\xA5\xE8\xAD\xA6\n" offset=122744
```
This is the configuration file
```
<source>
  @type kafka_group
  brokers 
  consumer_group fluentd-commander-prod
  topics commander.prod
  offset_commit_interval  10
  start_from_beginning    false
  @label @LOG_COMMANDER
  tag commander
</source>

<label @LOG_COMMANDER>


<match **>
  @type elasticsearch
  @log_level debug
  log_es_400_reason true
  hosts
  user 
  password 
  logstash_format true
  logstash_dateformat 000001
  request_timeout 15s
  logstash_prefix commander
  retry_max_times 300
  reconnect_on_error true
  reload_on_failure true
  reload_connections false
  <buffer tag>
    @type file
    flush_thread_count 8
    path /fluentd/buffer/buffer-commander/fluent.*.buffer
    flush_interval 6s
  </buffer>
</match>
</label>
```
I think this is a problem with decoding failure, but I didn't find a field that can be configured for decoding.
Thank you in advance!

**Comment by ZMMWMY** [comment]
My mistake, I re-read the error log, I found the configuration problem of format, I don't know its default configuration is json
