### ISSUE TITLE
rdkafka issue

### ISSUE THREAD

**Issue by arnitolog** [fluent/fluent-plugin-kafka#301]
Hi guys,

Git some weird error. Tried rdkafka 0.6.0 and 0.7.0 gems with the same result.
I use fluentd 1.7.4 deployed in Kubernetes
Has anyone faced the same and is there a way to solve it? 
here is an error:

```
  2019-11-28 17:08:41 +0000 [warn]: #0 /opt/bitnami/fluentd/gems/rdkafka-0.6.0/lib/rdkafka/config.rb:163:in `each'
  2019-11-28 17:08:41 +0000 [warn]: #0 /opt/bitnami/fluentd/gems/rdkafka-0.6.0/lib/rdkafka/config.rb:163:in `block in native_config'
  2019-11-28 17:08:41 +0000 [warn]: #0 /opt/bitnami/fluentd/gems/rdkafka-0.6.0/lib/rdkafka/config.rb:161:in `tap'
  2019-11-28 17:08:41 +0000 [warn]: #0 /opt/bitnami/fluentd/gems/rdkafka-0.6.0/lib/rdkafka/config.rb:161:in `native_config'
  2019-11-28 17:08:41 +0000 [warn]: #0 /opt/bitnami/fluentd/gems/rdkafka-0.6.0/lib/rdkafka/config.rb:138:in `producer'
  2019-11-28 17:08:41 +0000 [warn]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-kafka-0.12.1/lib/fluent/plugin/out_rdkafka2.rb:244:in `block in get_producer'
  2019-11-28 17:08:41 +0000 [warn]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-kafka-0.12.1/lib/fluent/plugin/out_rdkafka2.rb:241:in `synchronize'
  2019-11-28 17:08:41 +0000 [warn]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-kafka-0.12.1/lib/fluent/plugin/out_rdkafka2.rb:241:in `get_producer'
  2019-11-28 17:08:41 +0000 [warn]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-kafka-0.12.1/lib/fluent/plugin/out_rdkafka2.rb:275:in `write'
  2019-11-28 17:08:41 +0000 [warn]: #0 /opt/bitnami/fluentd/gems/fluentd-1.7.4/lib/fluent/plugin/output.rb:1125:in `try_flush'
  2019-11-28 17:08:41 +0000 [warn]: #0 /opt/bitnami/fluentd/gems/fluentd-1.7.4/lib/fluent/plugin/output.rb:1431:in `flush_thread_run'
  2019-11-28 17:08:41 +0000 [warn]: #0 /opt/bitnami/fluentd/gems/fluentd-1.7.4/lib/fluent/plugin/output.rb:461:in `block (2 levels) in start'
  2019-11-28 17:08:41 +0000 [warn]: #0 /opt/bitnami/fluentd/gems/fluentd-1.7.4/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-11-28 17:08:42 +0000 [warn]: #0 Send exception occurred: No such configuration property: "ssl.ca.location" at /opt/bitnami/fluentd/gems/rdkafka-0.6.0/lib/rdkafka/config.rb:173:in `block (2 levels) in native_config'
2019-11-28 17:08:42 +0000 [debug]: #0 taking back chunk for errors. chunk="5986b2a17527a855d063ef76f0b1f04e"
2019-11-28 17:08:42 +0000 [warn]: #0 failed to flush the buffer. retry_time=1 next_retry_seconds=2019-11-28 17:08:43 +0000 chunk="5986b2a17527a855d063ef76f0b1f04e" error_class=Rdkafka::Config::ConfigError error="No such configuration property: \"ssl.ca.location\""
  2019-11-28 17:08:42 +0000 [warn]: #0 suppressed same stacktrace
```
Here is my config:

>     <source>
>       @type beats
>       tag beats.input
>       @log_level debug
>     </source>
> 
>     <source>
>       @type http
>       bind 0.0.0.0
>       port 9880
>     </source>
> 
>     <match beats.**>
>       @type rdkafka2
>       @log_level debug
>       brokers kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9093
>       default_topic kafka-test
>       <buffer kafka-test>
>         flush_interval 3s
>       </buffer>
>       ssl_ca_cert /tmp/certs/ca.crt
>       required_acks -1
>       compression_codec gzip
>       <format>
>         @type json
>       </format
>       rdkafka_options {
>         "log_level" : 1     
>       }
>       rdkafka_delivery_handle_poll_timeout 30
>     </match>

**Comment by StephGit** [comment]
Might be your solution too: https://github.com/fluent/fluent-plugin-kafka/issues/314
