### ISSUE TITLE
Not able to configure zstd for compression codec

### ISSUE THREAD

**Issue by sivaparams** [fluent/fluent-plugin-kafka#310]
Hi Team,

Warm Wishes. Need help.

New to fluentd.

Not able to configure zstd as compression codec.
Not sure what is the miss. Could you help.

Versions of gems:

fluent-plugin-kafka (0.9.2)
fluentd (0.12.42)
zstd-ruby (1.4.4.0)

Match section of fluentd configuration:

```
  <match tag.kafka>
    @type kafka_buffered
    default_topic example
    brokers <ip>:9092
    buffer_type file
    buffer_path /fluentd/kafka
    flush_interval 5s
    output_data_type json
    compression_codec zstd
    max_send_retries 1
    required_acks -1
  </match>
```

Error Log: 

```
2020-01-10 09:31:40 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2020-01-10 09:32:08 +0000 error_class="Kafka::UnknownError" error="Kafka::UnknownError" plugin_id="object:43921204"
  2020-01-10 09:31:40 +0000 [warn]: suppressed same stacktrace
2020-01-10 09:32:08 +0000 [debug]: 1 messages send.
2020-01-10 09:32:08 +0000 [warn]: Send exception occurred: Kafka::UnknownError
2020-01-10 09:32:08 +0000 [warn]: Exception Backtrace : /usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/protocol.rb:160:in `handle_error'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/produce_operation.rb:153:in `block in handle_response'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/protocol/produce_response.rb:36:in `block (2 levels) in each_partition'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/protocol/produce_response.rb:35:in `each'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/protocol/produce_response.rb:35:in `block in each_partition'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/protocol/produce_response.rb:34:in `each'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/protocol/produce_response.rb:34:in `each_partition'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/produce_operation.rb:144:in `handle_response'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/produce_operation.rb:133:in `block in send_buffered_messages'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/produce_operation.rb:105:in `each'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/produce_operation.rb:105:in `send_buffered_messages'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/produce_operation.rb:62:in `block in execute'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/instrumenter.rb:23:in `instrument'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/produce_operation.rb:53:in `execute'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/producer.rb:402:in `block in deliver_messages_with_retries'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/producer.rb:390:in `loop'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/producer.rb:390:in `deliver_messages_with_retries'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/producer.rb:253:in `block in deliver_messages'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/instrumenter.rb:23:in `instrument'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/producer.rb:246:in `deliver_messages'
/usr/local/lib/ruby/gems/2.3/gems/fluent-plugin-kafka-0.9.2/lib/fluent/plugin/out_kafka_buffered.rb:286:in `deliver_messages'
/usr/local/lib/ruby/gems/2.3/gems/fluent-plugin-kafka-0.9.2/lib/fluent/plugin/out_kafka_buffered.rb:349:in `write'
/usr/local/lib/ruby/gems/2.3/gems/fluentd-0.12.42/lib/fluent/buffer.rb:354:in `write_chunk'
/usr/local/lib/ruby/gems/2.3/gems/fluentd-0.12.42/lib/fluent/buffer.rb:333:in `pop'
/usr/local/lib/ruby/gems/2.3/gems/fluentd-0.12.42/lib/fluent/output.rb:342:in `try_flush'
/usr/local/lib/ruby/gems/2.3/gems/fluentd-0.12.42/lib/fluent/output.rb:149:in `run'
2020-01-10 09:32:08 +0000 [info]: initialized kafka producer: kafka
2020-01-10 09:32:08 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2020-01-10 09:33:17 +0000 error_class="Kafka::UnknownError" error="Kafka::UnknownError" plugin_id="object:43921204"
```

**Comment by sivaparams** [comment]
Hi Team,

Have a critical release planned depending on the same. 
Can we get an update ?

Thanks,
Siva

**Comment by ganmacs** [comment]
I'm not sure but it looks like a not fluentd issue.  
According to https://github.com/zendesk/ruby-kafka/issues/227#issuecomment-227846911

> The error you're seeing is a generic server error. I'm not sure what's causing it – can you try tailing the Kafka broker log and see what shows up?

could you take check the kafka broker log?

**Comment by repeatedly** [comment]
I tested zstd and it worked.
My env is below:

- fluentd v1.7.4 and kafka2 (fluentd v0.12 is dead version so use v1 serise)
- fluent-plugin-kafka v0.12.2
- ruby-kafka 0.7.10
- zstd-ruby 1.4.4.0

**Comment by sivaparams** [comment]
Hi Masahiro,

Could you confirm on the exact configuration used by you.

Re-pasting my configuration from above.

<match tag.kafka>
    @type kafka_buffered
    default_topic example
    brokers <ip>:9092
    buffer_type file
    buffer_path /fluentd/kafka
    flush_interval 5s
    output_data_type json
    compression_codec zstd
    max_send_retries 1
    required_acks -1
  </match>

**Comment by repeatedly** [comment]
Yes. It worked.

```
<match test.**>
  @type kafka2

  brokers localhost:9092
  default_topic example
  required_acks -1
  compression_codec zstd
  max_send_retries 1
  <format>
    @type json
  </format>
  <buffer>
    flush_interval 5s
  </buffer>
</match>
```

**Comment by sivaparams** [comment]
Further looking on what we can do.|
We have hard call not to change the fluentd version.

Our requirement is 

Export the json logs to kafka with compression enabled.

### Could you suggest the best version fit for this requirement.
Its a request to give your comments on whether any version change of kafka would require a change in kafka ruby version. 
Current versions:

**fluentd (0.12.42)
fluent-plugin-kafka (0.9.2)
ruby-kafka (0.7.10)
fluent-plugin-cat-sweep (0.1.5)**

**ruby: ruby 2.3.4p301** 

Our kafka version is 
**kafka_2.12-2.3.1**

**Comment by repeatedly** [comment]
> Could you suggest the best version fit for this requirement.

Working version is mentioned in above my comment.
Unfortunately, I can't send good advise for you because I don't know why it doesn't work. I and you use same ruby-kafka and kafka version.
Maybe, asking it on kafka community with all your detailed kafka log and kafka configration is better.
`kafka_buffered` output is wrapper of ruby-kafka, so post it on ruby-kafka repository with reproducible code is another approach.
