### ISSUE TITLE
"Kafka::DeliveryFailed" error="Failed to send messages to topic/0"

### ISSUE THREAD

**Issue by sivaparams** [fluent/fluent-plugin-kafka#312]
Hi Team,

I am able to telnet to the kafka broker. It is working.

**My Versions:
fluentd (0.12.42)
fluent-plugin-kafka (0.9.2)
ruby-kafka (0.7.10)
fluent-plugin-cat-sweep (0.1.5)**

But getting the below error and also I dont get much info enabling the trace too. 
Could you advise.

2020-01-22 09:01:14 +0000 [warn]: Send exception occurred: Failed to send messages to topic/0
2020-01-22 09:01:14 +0000 [warn]: Exception Backtrace : /usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/producer.rb:430:in `deliver_messages_with_retries'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/producer.rb:253:in `block in deliver_messages'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/instrumenter.rb:23:in `instrument'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/producer.rb:246:in `deliver_messages'
/usr/local/lib/ruby/gems/2.3/gems/fluent-plugin-kafka-0.9.2/lib/fluent/plugin/out_kafka_buffered.rb:286:in `deliver_messages'
/usr/local/lib/ruby/gems/2.3/gems/fluent-plugin-kafka-0.9.2/lib/fluent/plugin/out_kafka_buffered.rb:349:in `write'
/usr/local/lib/ruby/gems/2.3/gems/fluentd-0.12.42/lib/fluent/buffer.rb:354:in `write_chunk'
/usr/local/lib/ruby/gems/2.3/gems/fluentd-0.12.42/lib/fluent/buffer.rb:333:in `pop'
/usr/local/lib/ruby/gems/2.3/gems/fluentd-0.12.42/lib/fluent/output.rb:342:in `try_flush'
/usr/local/lib/ruby/gems/2.3/gems/fluentd-0.12.42/lib/fluent/output.rb:149:in `run'
2020-01-22 09:01:14 +0000 [info]: initialized kafka producer: kafka
2020-01-22 09:01:14 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2020-01-22 10:15:09 +0000 error_class="Kafka::DeliveryFailed" error="Failed to send messages to raw-log/0" plugin_id="object:4391bb38"
  2020-01-22 09:01:14 +0000 [warn]: suppressed same stacktrace

**Comment by sivaparams** [comment]
Hi Team,

Adding an entry in /etc/hosts for my kafka cluster resolved the problem.

Closing the issue

Thanks,
Siva

**Comment by rahulkohli23** [comment]
@sivaparams can you provide the fluentd.conf file where you have configured kafka plugin also the entry that you made on your host ?
