### ISSUE TITLE
Not able to configure snappy for compression codec

### ISSUE THREAD

**Issue by sivaparams** [fluent/fluent-plugin-kafka#313]
Hi Team,

Warm Wishes. Need help.

Not able to configure snappy for compression codec.
Not sure what is the miss. Could you help.

Versions of gems:

fluent-plugin-kafka (0.9.2)
fluentd (0.12.42)
snappy (0.0.15)

**I also have other issue opened regarding zstd I want to try for snappy. Neither works** -
 https://github.com/fluent/fluent-plugin-kafka/issues/310

Snappy Configuration:
```
<match tag.kafka>
    @type kafka_buffered
    default_topic example
    brokers <ip>:9092
    buffer_type file
    buffer_path /fluentd/kafka
    flush_interval 5s
    output_data_type json
    compression_codec snappy
    max_send_retries 1
    required_acks -1
  </match>
```
Encountering the same problem.

```
2020-01-22 12:53:13 +0000 [info]: initialized kafka producer: kafka
2020-01-22 12:54:04 +0000 [debug]: in_cat_sweep: process: {filename:"abcd.json",size:51858}
2020-01-22 12:54:05 +0000 [debug]: 1 messages send.
2020-01-22 12:54:05 +0000 [warn]: Send exception occurred: Kafka::UnknownError
2020-01-22 12:54:05 +0000 [warn]: Exception Backtrace : /usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/protocol.rb:160:in `handle_error'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/produce_operation.rb:153:in `block in handle_response'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/protocol/produce_response.rb:36:in `block (2 levels) in each_partition'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/protocol/produce_response.rb:35:in `each'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/protocol/produce_response.rb:35:in `block in each_partition'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/protocol/produce_response.rb:34:in `each'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/protocol/produce_response.rb:34:in `each_partition'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/produce_operation.rb:144:in `handle_response'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/produce_operation.rb:133:in `block in send_buffered_messages'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/produce_operation.rb:105:in `each'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/produce_operation.rb:105:in `send_buffered_messages'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/produce_operation.rb:62:in `block in execute'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/instrumenter.rb:23:in `instrument'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/produce_operation.rb:53:in `execute'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/producer.rb:402:in `block in deliver_messages_with_retries'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/producer.rb:390:in `loop'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/producer.rb:390:in `deliver_messages_with_retries'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/producer.rb:253:in `block in deliver_messages'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/instrumenter.rb:23:in `instrument'
/usr/local/lib/ruby/gems/2.3/gems/ruby-kafka-0.7.10/lib/kafka/producer.rb:246:in `deliver_messages'
/usr/local/lib/ruby/gems/2.3/gems/fluent-plugin-kafka-0.9.2/lib/fluent/plugin/out_kafka_buffered.rb:286:in `deliver_messages'
/usr/local/lib/ruby/gems/2.3/gems/fluent-plugin-kafka-0.9.2/lib/fluent/plugin/out_kafka_buffered.rb:349:in `write'
/usr/local/lib/ruby/gems/2.3/gems/fluentd-0.12.42/lib/fluent/buffer.rb:354:in `write_chunk'
/usr/local/lib/ruby/gems/2.3/gems/fluentd-0.12.42/lib/fluent/buffer.rb:333:in `pop'
/usr/local/lib/ruby/gems/2.3/gems/fluentd-0.12.42/lib/fluent/output.rb:342:in `try_flush'
/usr/local/lib/ruby/gems/2.3/gems/fluentd-0.12.42/lib/fluent/output.rb:149:in `run'
2020-01-22 12:54:05 +0000 [info]: initialized kafka producer: kafka
2020-01-22 12:54:05 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2020-01-22 12:54:06 +0000 error_class="Kafka::UnknownError" error="Kafka::UnknownError" plugin_id="object:4391e504"
```

**Comment by ganmacs** [comment]
check this https://github.com/fluent/fluent-plugin-kafka/issues/310#issuecomment-573978205 .
