### ISSUE TITLE
Unable to publish key-value message to kafka topic, using message_key_key

### ISSUE THREAD

**Issue by merugu** [fluent/fluent-plugin-kafka#320]
Hi 

We are trying to publish key-value message to Kafka topic and consumer application will use Kafka streams to read the message from Kafka topic  The below is the fluentd configuration 
  <source>
    @type tail
    path "/var/log/test.log"
    tag "kubernetes.*"
    read_from_head true
    <parse>
      @type "json"
    </parse>
  </source>
  <match *.**>
    @type kafka2
    brokers broker_list
    topic_key "topicname"
    message_key_key "message_key"
    max_send_retries 1
    required_acks -1
    compression_codec "gzip"
    <buffer topic>
      flush_interval 60s
      flush_at_shutdown true
      flush_thread_count 8
      retry_max_times 10
      retry_wait 10s
      retry_forever 
    </buffer>
    <format>
      @type "json"
    </format>
  </match>
 

Sample message trying to post  
{
  "message_key": {
    "keyfield1": "abc",
    "keyfie;d2": "efg"
  },
  "value": {
    "messagevaluefield1": "hello",
    "messagevaluefield2": "world"
  }
}
 
The consumer application will use Kafka Streams API to read keyvalue message

And I’m getting below error, wondering I’m I missing something in configuration

2020-02-17 18:09:45 +0000 [warn]: #0 got unrecoverable error in primary and no secondary error_class=TypeError error="no implicit conversion of Hash into String"
  2020-02-17 18:09:45 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.10/lib/kafka/partitioner.rb:31:in `crc32'
  2020-02-17 18:09:45 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.10/lib/kafka/partitioner.rb:31:in `partition_for_key'
  2020-02-17 18:09:45 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kafka-0.12.2/lib/fluent/plugin/kafka_producer_ext.rb:253:in `block in assign_partitions!'
  2020-02-17 18:09:45 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.10/lib/kafka/pending_message_queue.rb:38:in `each'
  2020-02-17 18:09:45 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.10/lib/kafka/pending_message_queue.rb:38:in `each'
  2020-02-17 18:09:45 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kafka-0.12.2/lib/fluent/plugin/kafka_producer_ext.rb:248:in `assign_partitions!'
  2020-02-17 18:09:45 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kafka-0.12.2/lib/fluent/plugin/kafka_producer_ext.rb:209:in `block in deliver_messages_with_retries'

**Comment by merugu** [comment]
Also, I tried removed the message_key_key "message_key" from the configuration file and end up with same error

**Comment by merugu** [comment]
Finally, I figured out the issue with below file
https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/partitioner.rb
It is accepting only string as key...If I publish message key as String it is working fine...And failing if the message key is json object...

Also, One more thing I found is 
when I mention message_key_key it is taking message_key_key value as kafka message key
but the value it is taking as entire record

Don't if I can modify the record before sending to kafka

**Comment by repeatedly** [comment]
> It is accepting only string as key...If I publish message key as String it is working fine...And failing if the message key is json object...
> Also, One more thing I found is when I mention message_key_key in configuration file, it is taking message_key_key value as kafka message key but the value it is taking as entire record

This is expected behaviour. kafka's record key type is string. And you use `json` format, so value is entire record.
What is the problem?

**Comment by merugu** [comment]
If we mention message_key_key, we should delete the message_key_key value from the record itself, once the message_key_key value is assigned to local variable message_key
Because now in the consumer streaming application I'm ending up with designing model
Key Object -- Is the combination of multiple fields
Value --- Key Object  + Value(which is combination of multiple fields)

**Comment by repeatedly** [comment]
> If we mention message_key_key, we should delete the message_key_key value from the record itself

`exclude_message_key` doesn't work? https://github.com/fluent/fluent-plugin-kafka#output-plugin

**Comment by merugu** [comment]
It worked... I added exclude_message_key true, in configuration
