### ISSUE TITLE
#0 Could not connect to broker <ip> Connection error EOFError: EOFError

### ISSUE THREAD

**Issue by xhulioxole** [fluent/fluent-plugin-kafka#329]
I am trying to send logs from a fluentd container which retrieves them from an app container towards a kafka topic which is hosted in cloud. 

I also checked the other issues and i think the problem might be with versions compatibility but still couldn't resolve it.

Below are the configurations that i am using:

ruby 2.5.2
kafka 2.1.0
ruby-kafka-1.0.0
fluent-plugin-kafka 0.13.0
fluentd-1.3.2

Error Logs:
```

[info]: #0 New topics added to target list: test-topic
[info]: #0 Fetching cluster metadata from kafka://localhost:9092
[info]: #0 Discovered cluster metadata; nodes: localhost:9092
[error]: #0 Could not connect to broker localhost:9092 (node_id=2): Connection error EOFError: EOFError
...
[warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2020-03-30 10:30:38 +0000 chunk="5a20fed3e66e7875fe9995366a4eb4b3" error_class=Kafka::DeliveryFailed error="Failed to send messages to test-topic"
[warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kafka-0.13.0/lib/fluent/plugin/kafka_producer_ext.rb:240:in `deliver_messages_with_retries'
[warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kafka-0.13.0/lib/fluent/plugin/kafka_producer_ext.rb:126:in `deliver_messages'
[warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kafka-0.13.0/lib/fluent/plugin/out_kafka2.rb:265:in `write'
[warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.2/lib/fluent/plugin/output.rb:1123:in `try_flush'
[warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.2/lib/fluent/plugin/output.rb:1423:in `flush_thread_run'
[warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.2/lib/fluent/plugin/output.rb:452:in `block (2 levels) in start'
[warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
[info]: #0 New topics added to target list: test-topic
```

**Comment by ganmacs** [comment]
> Could not connect to broker localhost:9092 (node_id=2): Connection error EOFError: EOFError

You are trying to connect to `localhost`. please check your kafka is running and listening to localhost.

**Comment by xhulioxole** [comment]
Hi,

the problem was not with localhost. I just removed the real ip from the logs.

**Solution**

The below configurations made it work:

ruby-kafka version 0.4.4
kafka 0.9
fluent-plugin-kafka version 0.6.6,

Thanks
