### ISSUE TITLE
Rdkafka send buffer problem

### ISSUE THREAD

**Issue by xidiandb** [fluent/fluent-plugin-kafka#332]
My fluentd USES the k8s deployment, and the configuration USES buffers：
```
    <match *.template>
      @id template
      @type rdkafka2
      brokers "kafka-0.kafka-svc:9092,kafka-1.kafka-svc:9092,kafka-2.kafka-svc:9092"
      default_topic template
      rdkafka_options {
        "compression.codec" : "lz4",
        "request.required.acks" : 1
      }
      <format>
        @type json
      </format>
      <buffer>
        @type file_single
        path /log/buffer/kafka/template
        total_limit_size 2G
        chunk_limit_size 15M
        retry_type periodic
        retry_wait 60
        flush_mode interval
        flush_thread_count 2
        flush_interval 60s
        retry_forever true
        overflow_action block
      </buffer>
    </match>

```

When I run it for a while, and then restart it, it will look like this 
It's like fluentd is retrying like crazy
```
2020-04-02 06:45:42 +0000 [warn]: #2 [system] failed to flush the buffer. retry_time=0 next_retry_seconds=2020-04-02 06:46:42 +0000 chunk="5a248edfd8423123f6d600f37fd636cc" error_class=Rdkafka::RdkafkaError error="Local: Unknown topic (unknown_topic)"
  2020-04-02 06:45:42 +0000 [warn]: #2 suppressed same stacktrace
2020-04-02 06:45:44 +0000 [warn]: #2 [lma] Send exception occurred: Local: Unknown topic (unknown_topic) at /var/lib/gems/2.5.0/gems/rdkafka-0.7.0/lib/rdkafka/producer.rb:135:in `produce'
2020-04-02 06:45:44 +0000 [warn]: #2 [lma] failed to flush the buffer. retry_time=3 next_retry_seconds=2020-04-02 06:46:38 +0000 chunk="5a248ee1f1e82bbef5d18793e4402e22" error_class=Rdkafka::RdkafkaError error="Local: Unknown topic (unknown_topic)"
  2020-04-02 06:45:44 +0000 [warn]: #2 suppressed same stacktrace
2020-04-02 06:46:00 +0000 [warn]: #2 [middleware] Send exception occurred: Local: Unknown topic (unknown_topic) at /var/lib/gems/2.5.0/gems/rdkafka-0.7.0/lib/rdkafka/producer.rb:135:in `produce'
2020-04-02 06:46:00 +0000 [warn]: #2 [middleware] failed to flush the buffer. retry_time=2 next_retry_seconds=2020-04-02 06:47:07 +0000 chunk="5a248efb8f8a9cf9d40ae784c7e3b860" error_class=Rdkafka::RdkafkaError error="Local: Unknown topic (unknown_topic)"
  2020-04-02 06:46:00 +0000 [warn]: #2 suppressed same stacktrace
2020-04-02 06:46:01 +0000 [warn]: #2 [openstack] Send exception occurred: Local: Unknown topic (unknown_topic) at /var/lib/gems/2.5.0/gems/rdkafka-0.7.0/lib/rdkafka/producer.rb:135:in `produce'
2020-04-02 06:46:01 +0000 [warn]: #2 [openstack] failed to flush the buffer. retry_time=1 next_retry_seconds=2020-04-02 06:47:03 +0000 chunk="5a248ed1c24b12f4e4deffb38f7c7d4e" error_class=Rdkafka::RdkafkaError error="Local: Unknown topic (unknown_topic)"
  2020-04-02 06:46:01 +0000 [warn]: #2 suppressed same stacktrace
2020-04-02 06:46:01 +0000 [warn]: #2 [openstack] retry succeeded. chunk_id="5a2491dee3e035a5e13a414b7730f352"
2020-04-02 06:46:01 +0000 [warn]: #1 [openstack] Send exception occurred: Local: Unknown topic (unknown_topic) at /var/lib/gems/2.5.0/gems/rdkafka-0.7.0/lib/rdkafka/producer.rb:135:in `produce'
2020-04-02 06:46:01 +0000 [warn]: #1 [openstack] failed to flush the buffer. retry_time=6 next_retry_seconds=2020-04-02 06:46:59 +0000 chunk="5a248ed078965a849d6d7391bb3bda32" error_class=Rdkafka::RdkafkaError error="Local: Unknown topic (unknown_topic)"
  2020-04-02 06:46:01 +0000 [warn]: #1 suppressed same stacktrace
2020-04-02 06:46:02 +0000 [warn]: #2 [openstack] Send exception occurred: Local: Unknown topic (unknown_topic) at /var/lib/gems/2.5.0/gems/rdkafka-0.7.0/lib/rdkafka/producer.rb:135:in `produce'
2020-04-02 06:46:02 +0000 [warn]: #2 [openstack] failed to flush the buffer. retry_time=0 next_retry_seconds=2020-04-02 06:47:02 +0000 chunk="5a248ed1c24b12f4e4deffb38f7c7d4e" error_class=Rdkafka::RdkafkaError error="Local: Unknown topic (unknown_topic)"
  2020-04-02 06:46:02 +0000 [warn]: #2 suppressed same stacktrace

```

**Comment by xidiandb** [comment]
The plugin was installed completely new without any problems and booms when restarted
