### ISSUE TITLE
Required acks :all not showing valid configuration

### ISSUE THREAD

**Issue by kpiyush17** [fluent/fluent-plugin-kafka#340]
I am trying to add idempotent producer to my fluentd configuration. It is saying I need to add `required_acks :all`. Despite adding this config, fluentd is giving error to add the same.

Fluentd conf:
```
<match dbaudit.**>
    @type kafka2
    @log_level "debug"
    brokers ****:9094
    username "dev-kafka"
    password xxxxxx
    default_topic "test"
    scram_mechanism "sha512"
    sasl_over_ssl true
    ssl_ca_cert /usr/local/share/ca-certificates/kafka.crt
    idempotent true
    required_acks :all
    compression_codec "snappy"
    <buffer topic>
      flush_interval 10s
    </buffer>
    <format>
      @type "json"
    </format>
  </match>
```

Error Log:
```
#0 Send exception occurred: You must set required_acks option to :all to use idempotent / transactional production
#0 Exception Backtrace : /fluentd/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/produce_operation.rb:46:in `execute'
/fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kafka-0.12.4/lib/fluent/plugin/kafka_producer_ext.rb:210:in `block in deliver_messages_with_retries'
/fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kafka-0.12.4/lib/fluent/plugin/kafka_producer_ext.rb:200:in `loop'
/fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kafka-0.12.4/lib/fluent/plugin/kafka_producer_ext.rb:200:in `deliver_messages_with_retries'
/fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kafka-0.12.4/lib/fluent/plugin/kafka_producer_ext.rb:126:in `deliver_messages'
/fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kafka-0.12.4/lib/fluent/plugin/out_kafka2.rb:265:in `write'
/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.4/lib/fluent/plugin/output.rb:1133:in `try_flush'
/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.4/lib/fluent/plugin/output.rb:1439:in `flush_thread_run'
/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.4/lib/fluent/plugin/output.rb:461:in `block (2 levels) in start'
/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.4/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2020-05-21 08:09:13 +0000 [info]: #0 initialized kafka producer: fluentd
```

I am using fluend-kafka-plugin version `0.13.0`.

**Comment by kpiyush17** [comment]
Thanks for the answer. So, the above issue does not need attention?

Also, how can we do batching in `kafka2`? I tried to use `kafka_agg_max_bytes` but it seems to be only available for buffered_kafka.

**Comment by repeatedly** [comment]
> So, the above issue does not need attention?

Yes

> how can we do batching in kafka2? 

Buffered output plugin uses chunk for batching.
Configure `chunk_limit_size` of buffer on your requirement.

**Comment by kpiyush17** [comment]
@repeatedly But how do I enabled `idempotent true`? It is saying to have `required_acks :all` to be mandatory, same error as above.

**Comment by repeatedly** [comment]
> But how do I enabled idempotent true? It is saying to have required_acks :all to be mandatory, same error as above.

I can't reproduce your error.

```
<source>
  @type forward
</source>

<match test.**>
  @type kafka2
  @log_level "debug"
  default_topic "test"
  idempotent true
  # Remove unnecessary parameters for test
  <buffer topic>
    flush_interval 5s
  </buffer>
  <format>
    @type "json"
  </format>
</match>
```

- fluent-plugin-kafka v0.13.0
- ruby-kafka 0.7.10
- kafka 2.4.0
