### ISSUE TITLE
undefined method `call' for Kafka::Partitioner:Class`

### ISSUE THREAD

**Issue by dmilde** [fluent/fluent-plugin-kafka#359]
Hi,
getting the following error in 1.11.2 (after the "Partitioner.partition_for_key undefined" fix):

```
2020-08-07 21:00:12 +0000 [warn]: #5 [kafka] got unrecoverable error in primary and no secondary error_class=NoMethodError error="undefined method `call' for Kafka::Partitioner:Class"
  2020-08-07 21:00:12 +0000 [warn]: #5 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kafka-0.14.0/lib/fluent/plugin/kafka_producer_ext.rb:253:in `block in assign_partitions!'
  2020-08-07 21:00:12 +0000 [warn]: #5 /usr/lib/ruby/gems/2.5.0/gems/ruby-kafka-1.2.0/lib/kafka/pending_message_queue.rb:38:in `each'
  2020-08-07 21:00:12 +0000 [warn]: #5 /usr/lib/ruby/gems/2.5.0/gems/ruby-kafka-1.2.0/lib/kafka/pending_message_queue.rb:38:in `each'
  2020-08-07 21:00:12 +0000 [warn]: #5 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kafka-0.14.0/lib/fluent/plugin/kafka_producer_ext.rb:248:in `assign_partitions!'
  2020-08-07 21:00:12 +0000 [warn]: #5 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kafka-0.14.0/lib/fluent/plugin/kafka_producer_ext.rb:209:in `block in deliver_messages_with_retries'
  2020-08-07 21:00:12 +0000 [warn]: #5 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kafka-0.14.0/lib/fluent/plugin/kafka_producer_ext.rb:200:in `loop'
  2020-08-07 21:00:12 +0000 [warn]: #5 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kafka-0.14.0/lib/fluent/plugin/kafka_producer_ext.rb:200:in `deliver_messages_with_retries'
  2020-08-07 21:00:12 +0000 [warn]: #5 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kafka-0.14.0/lib/fluent/plugin/kafka_producer_ext.rb:126:in `deliver_messages'
  2020-08-07 21:00:12 +0000 [warn]: #5 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kafka-0.14.0/lib/fluent/plugin/out_kafka2.rb:270:in `write'
  2020-08-07 21:00:12 +0000 [warn]: #5 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/plugin/output.rb:1133:in `try_flush'
  2020-08-07 21:00:12 +0000 [warn]: #5 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/plugin/output.rb:1439:in `flush_thread_run'
  2020-08-07 21:00:12 +0000 [warn]: #5 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/plugin/output.rb:461:in `block (2 levels) in start'
  2020-08-07 21:00:12 +0000 [warn]: #5 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```

Using the latest fluentd 1.11.2 (from Dockerfile) and ruby-kafka v1.2.0
Rdkafka2 is working.

**Comment by dmilde** [comment]
Should be fixed with: https://github.com/fluent/fluent-plugin-kafka/pull/361
