### ISSUE TITLE
Failed to connect to localhost:9092

### ISSUE THREAD

**Issue by sethest** [fluent/fluent-plugin-kafka#37]
Hi,

I started Kafka broker successfully (port 9092)
But I can't access broker when I started fluentd, What happened? 

Thanks
#### Instance

> Kafka  \* 1
> Zookeeper \* 1
> Mongod \* 1
#### Send some messages (Kafka)

```
$ kafka-console-producer.sh --broker-list localhost:9092 --topic test
This is a message
This is another message
```
#### Start a consumer (Kafka)

```
$ kafka-console-consumer.sh --zookeeper localhost:2181 --topic test --from-beginning
This is a message
This is another message     (kafka is OK)
```
#### Config file (Fluentd)

```
<source>
  type   kafka
  host   localhost
  port   9092
  topics test
  format ltsv
  message_key message
  max_bytes           nil
  max_wait_ms         nil
  min_bytes           nil
  socket_timeout_ms   nil
</source>

<match *.**>
  type copy
  <store>
    buffer_type memory
    buffer_queue_limit 100000000
    buffer_chunk_limit 8m
    flush_interval 1s
    flush_at_shutdown true

    type mongo
    host localhost
    port 27017
    database test
    collection kafka_output
  </store>
  <store>
    type file
    path /home/vagrant/fluentd/out_file/kafka_output
    time_slice_format %Y%m%d
    time_slice_wait 10m
    time_format %Y%m%dT%H%M%S%z
    compress gzip
    utc
  </store>
</match>
```
#### Error message (Fluentd)

```
2016-01-07 09:43:08 +0000 [error]: Failed to connect to localhost:9092
gems/poseidon-0.0.5/lib/poseidon/connection.rb:166:in `raise_connection_failed_error'     
gems/poseidon-0.0.5/lib/poseidon/connection.rb:123:in `rescue in read_response'           
gems/poseidon-0.0.5/lib/poseidon/connection.rb:113:in `read_response'                     
gems/poseidon-0.0.5/lib/poseidon/connection.rb:85:in `offset'                             
gems/poseidon-0.0.5/lib/poseidon/partition_consumer.rb:190:in `resolve_offset_if_necessary'
gems/poseidon-0.0.5/lib/poseidon/partition_consumer.rb:136:in `next_offset'               
gems/poseidon-0.0.5/lib/poseidon/partition_consumer.rb:218:in `build_topic_fetch_request' 
gems/poseidon-0.0.5/lib/poseidon/partition_consumer.rb:107:in `fetch'                     
gems/fluent-plugin-kafka-0.1.2/lib/fluent/plugin/in_kafka.rb:159:in `consume'             
gems/fluent-plugin-kafka-0.1.2/lib/fluent/plugin/in_kafka.rb:142:in `call'                 
gems/fluent-plugin-kafka-0.1.2/lib/fluent/plugin/in_kafka.rb:142:in `on_timer'             
gems/cool.io-1.4.2/lib/cool.io/loop.rb:88:in `run_once'                                   
gems/cool.io-1.4.2/lib/cool.io/loop.rb:88:in `run'                                         
gems/fluent-plugin-kafka-0.1.2/lib/fluent/plugin/in_kafka.rb:110:in `run'   

```

**Comment by repeatedly** [comment]
If you get same error with latest version, please reopen it.

**Comment by ezolnbl** [comment]
same problem on windows, everything works fine with latest version from everything, i can send messages to kafka, i can connect to it, tried connection with:
-localhost
-127.0.0.1
-0.0.0.0
no luck
