### ISSUE TITLE
Unable to publish Kafka message over IPV6 broker. 

### ISSUE THREAD

**Issue by talkraghu** [fluent/fluent-plugin-kafka#387]
I am unable to publish kafka message over IPV6 broker address. 

Plugin version under use
--------------------------
fluent-plugin-kafka (0.7.9)
ruby-kafka (0.6.8)

ERROR log message seen
--------------------------
  2021-01-20 12:16:12 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.6.8/lib/kafka.rb:252:in `new'
  2021-01-20 12:16:12 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.6.8/lib/kafka.rb:252:in `new'
  2021-01-20 12:16:12 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kafka-0.7.9/lib/fluent/plugin/out_kafka2.rb:89:in `refresh_client'
  2021-01-20 12:16:12 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kafka-0.7.9/lib/fluent/plugin/out_kafka2.rb:154:in `start'
  2021-01-20 12:16:12 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/root_agent.rb:165:in `block in start'
  2021-01-20 12:16:12 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/root_agent.rb:144:in `block (2 levels) in lifecycle'
  2021-01-20 12:16:12 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/agent.rb:119:in `block (2 levels) in lifecycle'
  2021-01-20 12:16:12 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/agent.rb:118:in `each'
  2021-01-20 12:16:12 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/agent.rb:118:in `block in lifecycle'
  2021-01-20 12:16:12 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/agent.rb:111:in `each'
  2021-01-20 12:16:12 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/agent.rb:111:in `lifecycle'
  2021-01-20 12:16:12 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/root_agent.rb:143:in `block in lifecycle'
  2021-01-20 12:16:12 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/root_agent.rb:140:in `each'
  2021-01-20 12:16:12 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/root_agent.rb:140:in `lifecycle'
  2021-01-20 12:16:12 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/root_agent.rb:164:in `start'
  2021-01-20 12:16:12 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/engine.rb:274:in `start'
  2021-01-20 12:16:12 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/engine.rb:219:in `run'
  2021-01-20 12:16:12 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/supervisor.rb:799:in `run_engine'
  2021-01-20 12:16:12 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/supervisor.rb:549:in `block in run_worker'
  2021-01-20 12:16:12 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/supervisor.rb:724:in `main_process'
  2021-01-20 12:16:12 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/supervisor.rb:544:in `run_worker'
  2021-01-20 12:16:12 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
  2021-01-20 12:16:12 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2021-01-20 12:16:12 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2021-01-20 12:16:12 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/bin/fluentd:8:in `<top (required)>'
  2021-01-20 12:16:12 +0530 [error]: #0 /opt/td-agent/embedded/bin/fluentd:23:in `load'
  2021-01-20 12:16:12 +0530 [error]: #0 /opt/td-agent/embedded/bin/fluentd:23:in `<main>'
2021-01-20 12:16:12 +0530 [error]: #0 unexpected error error_class=URI::InvalidURIError error="bad URI(is not URI?): kafka://fded:fade:face:acea::7:9092"
  2021-01-20 12:16:12 +0530 [error]: #0 suppressed same stacktrace
2021-01-20 12:16:12 +0530 [info]: Worker 0 finished unexpectedly with status 1

Kafka output configuration at td-agent.conf
--------------------------
      @type kafka2
      default_topic xyz-topic
      brokers fded:fade:face:acea::7:9092
      sasl_over_ssl false
      <buffer topic>
        flush_interval 1s
      </buffer>
      <format>
        @type json
      </format>

I am able to consume the kafka messages from kafka-console-consumer.sh via the same broker address (fded:fade:face:acea::7:9092)
--------------------------
[root@ipv4v6vm ~]# /opt/nsp/os/kafka/bin/kafka-console-consumer.sh --topic xyz-topic --bootstrap-server fded:fade:face:acea::7:9092 --consumer.config /opt/nsp/os/kafka/config/consumer.properties --from-beginning

test message
^CProcessed a total of 1 messages
[root@ipv4v6vm ~]# 

Why is the kafka2 plugin throwing the bad URI error ?
2021-01-20 12:16:12 +0530 [error]: #0 unexpected error error_class=URI::InvalidURIError error="bad URI(is not URI?): kafka://fded:fade:face:acea::7:9092"

Is there any workaround ?

**Comment by repeatedly** [comment]
How about using `[fded:fade:face:acea::7]:9092` instead?

**Comment by talkraghu** [comment]
@repeatedly , Yes. I tried adding square bracket at IPv6 address at kafka broker part (as suggested)
**brokers [2607:f160:f:f001:aaa:abab:0:101]:9092,[2607:f160:f:f001:aaa:abab:0:102]:9092**
This solution did not work. The square brackets are treated as json elements and formatting fails. 
Infact td-agent will NOT start and fails with ConfigParseError
 
[root@ipv4v6vm td-agent]# /etc/init.d/td-agent configtest 
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/config/basic_parser.rb:92:in `parse_error!': got incomplete JSON array configuration at td-agent.conf line 124,9 (Fluent::ConfigParseError)


To overcome the problem with special square bracket chars, I tried escaping it (like below)
**brokers \[2607:f160:f:f001:aaa:abab:0:101\]:9092,\[2607:f160:f:f001:aaa:abab:0:102\]:9092**
The parsing works and td-agent starts. However, the connection errors still remains with below error

2021-01-20 07:44:29 -0500 [error]: #0 unexpected error error_class=URI::InvalidURIError error="bad URI(is not URI?): kafka://\\[fded:fade:face:acea::7\\]:9092"

May be the escape chars being part of broker address is causing the connection problem

**Comment by talkraghu** [comment]
I tried reworking out_kafka2.rb at configure method that set brokers. 
1) Detect whether the each broker has more than 1 colon (:)
2) If more than 1 colon, we can assume it to be a IPv6 address 
3) Append square brackets and reconstruct the new broker address

      if @brokers.size > 0
        log.info "brokers has been set: #{@brokers}"
```
        @new_brokers = Array.new
        brokers.each do |st|
          colon_count = st.count(':')
          if(colon_count > 1)
            broker_parts = st.rpartition(':')
            new_broker = "[" + broker_parts[0] + "]" + broker_parts[1] + broker_parts[2]
          else
            new_broker = st
          end
          log.info "broker has been set part2: #{new_broker}"
          @new_brokers.push(new_broker)
        end

        @seed_brokers = @new_brokers

```
        log.info "new brokers has been set: #{@seed_brokers}"


Can we do something like this and auto add the square brackets when the broker host is of type IPV6 ?

**Comment by repeatedly** [comment]
How about `brokers ["[2607:f160:f:f001:aaa:abab:0:101]:9092","[2607:f160:f:f001:aaa:abab:0:102]:9092"]`?
brokers parameter is array type.

**Comment by talkraghu** [comment]
Hi @repeatedly ,

The format you proposed worked. The td-agent starts well with this format and messages can be published to the topic vis these  broker address

For multi broker the conf would be
brokers ["[2607:f160:f:f001:aaa:abab:0:101]:9092","[2607:f160:f:f001:aaa:abab:0:102]:9092"]

For standalone broker the conf would be
brokers ["[2607:f160:f:f001:aaa:abab:0:101]:9092”]

Logs:
2021-01-21 21:20:06 -0500 [info]: gem 'fluentd' version '1.2.6'
2021-01-21 21:20:06 -0500 [info]: adding match in @alogs pattern="nsp-activitylog" type="copy"
2021-01-21 21:20:06 -0500 [info]: #0 brokers has been set: ["[fded:fade:face:acea::7]:9092"]

**Comment by talkraghu** [comment]
Closing the issue as the given format works
