### ISSUE TITLE
Unrecoverable error with kafka_group input reading snappy compressed records

### ISSUE THREAD

**Issue by geraudster** [fluent/fluent-plugin-kafka#391]
## Versions

td-agent 4.1.0 
fluentd 1.12.1 
fluent-plugin-kafka (0.16.0)
ruby-kafka (1.3.0)

## Description

When a compressed record is present in a kafka topic, fluentd will throw an exception about missing library and cannot recover from the error. The problem is that on the next start, fluentd will try to read the same record and fail indefinitely.

Is there a way to skip incorrect records and/or to put them in a dead letter queue ? The idea is to prevent fluentd from crashing when an incorrect record (either compressed with a non supported algorithm or for any other reason) has been pushed to Kafka.

There is a sample project to help reproduce the issue: https://github.com/geraudster/fluentd_kafka_error

**Comment by kenhys** [comment]
Here is the logs :https://github.com/geraudster/fluentd_kafka_error

```
td-agent_1   | 2021-06-29 04:25:33 +0000 [info]: adding match pattern="*" type="stdout"
td-agent_1   | 2021-06-29 04:25:33 +0000 [trace]: #0 registered output plugin 'stdout'
td-agent_1   | 2021-06-29 04:25:33 +0000 [trace]: #0 registered buffer plugin 'memory'
td-agent_1   | 2021-06-29 04:25:33 +0000 [trace]: #0 registered formatter plugin 'stdout'
td-agent_1   | 2021-06-29 04:25:33 +0000 [trace]: #0 registered formatter plugin 'json'
td-agent_1   | 2021-06-29 04:25:33 +0000 [info]: adding source type="kafka_group"
td-agent_1   | 2021-06-29 04:25:33 +0000 [trace]: #0 registered input plugin 'kafka_group'
kafka1_1     | [2021-06-29 04:25:33,969] INFO Awaiting socket connections on 0.0.0.0:9092. (kafka.network.Acceptor)
td-agent_1   | 2021-06-29 04:25:33 +0000 [info]: #0 Will watch for topics test_topic at brokers kafka1:9092 and 'test_cg' group
td-agent_1   | 2021-06-29 04:25:33 +0000 [debug]: #0 No fluent logger for internal event
td-agent_1   | 2021-06-29 04:25:33 +0000 [info]: #0 starting fluentd worker pid=16 ppid=1 worker=0
td-agent_1   | 2021-06-29 04:25:33 +0000 [info]: #0 Subscribe to topic test_topic
td-agent_1   | #<Thread:0x000055d04f1a1970 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/fetcher.rb:57 run> terminated with exception (report_on_exception is true):
td-agent_1   | /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/snappy_codec.rb:16:in `rescue in load': Using snappy compression requires adding a dependency on the `snappy` gem to your Gemfile. (LoadError)
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/snappy_codec.rb:13:in `load'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/compression.rb:40:in `find_codec_by_id'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/record_batch.rb:183:in `decode'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/fetch_response.rb:100:in `block (2 levels) in decode'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/decoder.rb:79:in `times'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/decoder.rb:79:in `each'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/decoder.rb:79:in `map'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/decoder.rb:79:in `array'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/fetch_response.rb:75:in `block in decode'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/decoder.rb:79:in `times'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/decoder.rb:79:in `each'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/decoder.rb:79:in `map'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/decoder.rb:79:in `array'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/fetch_response.rb:72:in `decode'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/connection.rb:195:in `read_response'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/connection.rb:207:in `block in wait_for_response'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/connection.rb:206:in `loop'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/connection.rb:206:in `wait_for_response'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/connection.rb:110:in `block in send_request'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/instrumenter.rb:23:in `instrument'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/connection.rb:100:in `send_request'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/broker.rb:200:in `send_request'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/broker.rb:54:in `fetch_messages'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/fetch_operation.rb:81:in `block in execute'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/fetch_operation.rb:71:in `each'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/fetch_operation.rb:71:in `flat_map'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/fetch_operation.rb:71:in `execute'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/fetcher.rb:204:in `fetch_batches'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/fetcher.rb:160:in `step'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/fetcher.rb:114:in `loop'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/fetcher.rb:59:in `block in start'
td-agent_1   | /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:146:in `require': cannot load such file -- snappy (LoadError)
td-agent_1   | 	from /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:146:in `require'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/snappy_codec.rb:14:in `load'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/compression.rb:40:in `find_codec_by_id'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/record_batch.rb:183:in `decode'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/fetch_response.rb:100:in `block (2 levels) in decode'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/decoder.rb:79:in `times'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/decoder.rb:79:in `each'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/decoder.rb:79:in `map'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/decoder.rb:79:in `array'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/fetch_response.rb:75:in `block in decode'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/decoder.rb:79:in `times'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/decoder.rb:79:in `each'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/decoder.rb:79:in `map'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/decoder.rb:79:in `array'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/fetch_response.rb:72:in `decode'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/connection.rb:195:in `read_response'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/connection.rb:207:in `block in wait_for_response'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/connection.rb:206:in `loop'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/connection.rb:206:in `wait_for_response'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/connection.rb:110:in `block in send_request'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/instrumenter.rb:23:in `instrument'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/connection.rb:100:in `send_request'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/broker.rb:200:in `send_request'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/broker.rb:54:in `fetch_messages'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/fetch_operation.rb:81:in `block in execute'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/fetch_operation.rb:71:in `each'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/fetch_operation.rb:71:in `flat_map'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/fetch_operation.rb:71:in `execute'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/fetcher.rb:204:in `fetch_batches'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/fetcher.rb:160:in `step'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/fetcher.rb:114:in `loop'
td-agent_1   | 	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/fetcher.rb:59:in `block in start'
td-agent_1   | 2021-06-29 04:25:37 +0000 [error]: #0 unexpected error error_class=LoadError error="Using snappy compression requires adding a dependency on the `snappy` gem to your Gemfile."
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/snappy_codec.rb:16:in `rescue in load'
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/snappy_codec.rb:13:in `load'
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/compression.rb:40:in `find_codec_by_id'
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/record_batch.rb:183:in `decode'
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/fetch_response.rb:100:in `block (2 levels) in decode'
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/decoder.rb:79:in `times'
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/decoder.rb:79:in `each'
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/decoder.rb:79:in `map'
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/decoder.rb:79:in `array'
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/fetch_response.rb:75:in `block in decode'
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/decoder.rb:79:in `times'
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/decoder.rb:79:in `each'
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/decoder.rb:79:in `map'
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/decoder.rb:79:in `array'
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/protocol/fetch_response.rb:72:in `decode'
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/connection.rb:195:in `read_response'
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/connection.rb:207:in `block in wait_for_response'
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/connection.rb:206:in `loop'
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/connection.rb:206:in `wait_for_response'
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/connection.rb:110:in `block in send_request'
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/instrumenter.rb:23:in `instrument'
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/connection.rb:100:in `send_request'
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/broker.rb:200:in `send_request'
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/broker.rb:54:in `fetch_messages'
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/fetch_operation.rb:81:in `block in execute'
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/fetch_operation.rb:71:in `each'
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/fetch_operation.rb:71:in `flat_map'
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/fetch_operation.rb:71:in `execute'
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/fetcher.rb:204:in `fetch_batches'
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/fetcher.rb:160:in `step'
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/fetcher.rb:114:in `loop'
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.3.0/lib/kafka/fetcher.rb:59:in `block in start'
td-agent_1   | 2021-06-29 04:25:37 +0000 [error]: #0 Using snappy compression requires adding a dependency on the `snappy` gem to your Gemfile. path=nil error_class=LoadError error="Using snappy compression requires adding a dependency on the `snappy` gem to your Gemfile."
td-agent_1   |   2021-06-29 04:25:37 +0000 [error]: #0 suppressed same stacktrace
td-agent_1   | 2021-06-29 04:25:37 +0000 [info]: fluent/log.rb:329:info: Worker 0 finished unexpectedly with status 2
td-agent_1   | 2021-06-29 04:25:37 +0000 [info]: fluent/log.rb:329:info: Received graceful stop
```

**Comment by cosmo0920** [comment]
This is because td-agent4 does not bundle snappy gem for.

Your Dockerfile seems that it just installs td-agent4 with script:
https://github.com/geraudster/fluentd_kafka_error/blob/main/td-agent/Dockerfile#L5

You should install snappy gem via `td-agent-gem` command before using snappy compression.

**Comment by kenhys** [comment]
At first, even though snappy is not installed, it may be better to avoid crashes, but reconsidered to require explicitly installing it beforehand is reasonable.

**Comment by beerus11** [comment]
@kenhys , how you fixed this issue, I'm also getting similar exception?
