### ISSUE TITLE
rdkafka2 with sasl_ssl doesn't work?

### ISSUE THREAD

**Issue by scharissis-wx** [fluent/fluent-plugin-kafka#414]
### Describe the bug

I'm trying to emit events to Azure EventHub via its Kafka interface and your `rdkafka2` output plugin. This works fine with `kafka2` output plugin with the following config:

```
  <store>
      @type kafka2

      brokers               xxx.servicebus.windows.net:9093
      default_topic         'zero'
      get_kafka_client_log  true

      <format>
        @type json
      </format>

    
      <inject>
        tag_key tag
        time_key time
      </inject>

      <buffer topic>
        flush_interval 2s
      </buffer>

      idempotent        false
      ssl_ca_certs_from_system true
      sasl_over_ssl     true
      max_send_retries  1
      required_acks     -1
      ack_timeout       nil

      username "$ConnectionString"
      password "Endpoint=sb:/xxx.servicebus.windows.net/;SharedAccessKeyName=xxx;SharedAccessKey=xxx=;EntityPath=xxx"
  </store>

</match>
```

However, with `rdkafka2` with this config I get the following error:

```
<store>
      @type rdkafka2
      @log_level debug

      brokers               xxx.servicebus.windows.net:9093
      default_topic         'zero'

      <format>
        @type json
      </format>

      <inject>
        tag_key tag
        time_key time
      </inject>

      <buffer topic>
        flush_interval 2s
      </buffer>

      ssl_ca_certs_from_system true
      max_send_retries  1
      required_acks     -1
      ack_timeout       nil

      rdkafka_options {
        "log_level" : 7,
        "request.timeout.ms": 5000,

        "security.protocol": "sasl_ssl",
        "ssl.ca.location": "/etc/ssl/certs/",
        "sasl.mechanism": "PLAIN",
        "sasl.username":     "$ConnectionString",
        "sasl.password": "Endpoint=sb://xxx.servicebus.windows.net/;SharedAccessKeyName=xxx;SharedAccessKey=xxx=;EntityPath=xxx"
      }

      rdkafka_delivery_handle_poll_timeout 5
  
  </store>
```

```
2021-08-20 05:11:57 +0000 [debug]: #0 adding store type="stdout"
2021-08-20 05:11:57 +0000 [debug]: #0 adding store type="rdkafka2"
2021-08-20 05:11:57 +0000 [info]: adding source type="http"
2021-08-20 05:11:57 +0000 [info]: #0 starting fluentd worker pid=31 ppid=1 worker=0
2021-08-20 05:11:57 +0000 [debug]: #0 buffer started instance=46978703552640 stage_size=0 queue_size=0
2021-08-20 05:11:57 +0000 [debug]: #0 listening http bind="0.0.0.0" port=9880
2021-08-20 05:11:57 +0000 [debug]: #0 flush_thread actually running
2021-08-20 05:11:57 +0000 [debug]: #0 enqueue_thread actually running
2021-08-20 05:11:57 +0000 [info]: #0 fluentd worker is now running worker=0
2021-08-20 05:11:57.511071478 +0000 fluent.info: {"pid":31,"ppid":1,"worker":0,"message":"starting fluentd worker pid=31 ppid=1 worker=0"}
2021-08-20 05:11:57.511259669 +0000 fluent.debug: {"instance":46978703552640,"stage_size":0,"queue_size":0,"message":"buffer started instance=46978703552640 stage_size=0 queue_size=0"}
2021-08-20 05:11:57.511942111 +0000 fluent.debug: {"bind":"0.0.0.0","port":9880,"message":"listening http bind=\"0.0.0.0\" port=9880"}
2021-08-20 05:11:57.512143971 +0000 fluent.debug: {"message":"flush_thread actually running"}
2021-08-20 05:11:57.512323582 +0000 fluent.debug: {"message":"enqueue_thread actually running"}
2021-08-20 05:11:57.514018507 +0000 fluent.info: {"worker":0,"message":"fluentd worker is now running worker=0"}
2021-08-20 05:12:01.478888383 +0000 : {"json":"test"}
#<Thread:0x000055742a8fa658@/opt/bitnami/fluentd/gems/rdkafka-0.9.0/lib/rdkafka/config.rb:17 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        3: from /opt/bitnami/fluentd/gems/rdkafka-0.9.0/lib/rdkafka/config.rb:18:in `block in <class:Config>'
        2: from /opt/bitnami/fluentd/gems/rdkafka-0.9.0/lib/rdkafka/config.rb:18:in `loop'
        1: from /opt/bitnami/fluentd/gems/rdkafka-0.9.0/lib/rdkafka/config.rb:20:in `block (2 levels) in <class:Config>'
/opt/bitnami/fluentd/gems/fluent-plugin-kafka-0.16.0/lib/fluent/plugin/out_rdkafka2.rb:113:in `add': wrong number of arguments (given 2, expected 1) (ArgumentError)
```

And if I change  the following config:
```
"security.protocol": "sasl_plaintext"
```

I then get this error (timeout):
```
2021-08-20 05:04:38 +0000 [debug]: #0 adding store type="stdout"
2021-08-20 05:04:38 +0000 [debug]: #0 adding store type="rdkafka2"
2021-08-20 05:04:38 +0000 [info]: adding source type="http"
2021-08-20 05:04:38 +0000 [info]: #0 starting fluentd worker pid=32 ppid=1 worker=0
2021-08-20 05:04:38 +0000 [debug]: #0 buffer started instance=47451782059520 stage_size=0 queue_size=0
2021-08-20 05:04:38 +0000 [debug]: #0 listening http bind="0.0.0.0" port=9880
2021-08-20 05:04:38 +0000 [debug]: #0 flush_thread actually running
2021-08-20 05:04:38 +0000 [debug]: #0 enqueue_thread actually running
2021-08-20 05:04:38 +0000 [info]: #0 fluentd worker is now running worker=0
2021-08-20 05:04:38.669300412 +0000 fluent.info: {"pid":32,"ppid":1,"worker":0,"message":"starting fluentd worker pid=32 ppid=1 worker=0"}
2021-08-20 05:04:38.669510162 +0000 fluent.debug: {"instance":47451782059520,"stage_size":0,"queue_size":0,"message":"buffer started instance=47451782059520 stage_size=0 queue_size=0"}
2021-08-20 05:04:38.670203084 +0000 fluent.debug: {"bind":"0.0.0.0","port":9880,"message":"listening http bind=\"0.0.0.0\" port=9880"}
2021-08-20 05:04:38.670359935 +0000 fluent.debug: {"message":"flush_thread actually running"}
2021-08-20 05:04:38.670522015 +0000 fluent.debug: {"message":"enqueue_thread actually running"}
2021-08-20 05:04:38.672051620 +0000 fluent.info: {"worker":0,"message":"fluentd worker is now running worker=0"}
2021-08-20 05:05:01.359257743 +0000 : {"json":"test"}
#<Thread:0x0000565075e106d8@/opt/bitnami/fluentd/gems/rdkafka-0.9.0/lib/rdkafka/config.rb:17 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        3: from /opt/bitnami/fluentd/gems/rdkafka-0.9.0/lib/rdkafka/config.rb:18:in `block in <class:Config>'
        2: from /opt/bitnami/fluentd/gems/rdkafka-0.9.0/lib/rdkafka/config.rb:18:in `loop'
        1: from /opt/bitnami/fluentd/gems/rdkafka-0.9.0/lib/rdkafka/config.rb:20:in `block (2 levels) in <class:Config>'
/opt/bitnami/fluentd/gems/fluent-plugin-kafka-0.16.0/lib/fluent/plugin/out_rdkafka2.rb:113:in `add': wrong number of arguments (given 2, expected 1) (ArgumentError)
2021-08-20 05:05:09 +0000 [warn]: #0 Send exception occurred: Waiting for delivery timed out after 5 seconds at /opt/bitnami/fluentd/gems/rdkafka-0.9.0/lib/rdkafka/abstract_handle.rb:52:in `block in wait'
2021-08-20 05:05:09.686916501 +0000 fluent.warn: {"message":"Send exception occurred: Waiting for delivery timed out after 5 seconds at /opt/bitnami/fluentd/gems/rdkafka-0.9.0/lib/rdkafka/abstract_handle.rb:52:in `block in wait'"}
2021-08-20 05:05:09 +0000 [debug]: #0 taking back chunk for errors. chunk="5c9f69c15b6e3487cf2300aa195ab2a7"
2021-08-20 05:05:09.687242402 +0000 fluent.debug: {"chunk":"5c9f69c15b6e3487cf2300aa195ab2a7","message":"taking back chunk for errors. chunk=\"5c9f69c15b6e3487cf2300aa195ab2a7\""}
2021-08-20 05:05:09 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2021-08-20 05:05:10 +0000 chunk="5c9f69c15b6e3487cf2300aa195ab2a7" error_class=Rdkafka::AbstractHandle::WaitTimeoutError error="Waiting for delivery timed out after 5 seconds"
2021-08-20 05:05:09.687702453 +0000 fluent.warn: {"retry_time":0,"next_retry_seconds":"2021-08-20 05:05:10 +0000","chunk":"5c9f69c15b6e3487cf2300aa195ab2a7","error":"#<Rdkafka::AbstractHandle::WaitTimeoutError: Waiting for delivery timed out after 5 seconds>","message":"failed to flush the buffer. retry_time=0 next_retry_seconds=2021-08-20 05:05:10 +0000 chunk=\"5c9f69c15b6e3487cf2300aa195ab2a7\" error_class=Rdkafka::AbstractHandle::WaitTimeoutError error=\"Waiting for delivery timed out after 5 seconds\""}
  2021-08-20 05:05:09 +0000 [warn]: #0 /opt/bitnami/fluentd/gems/rdkafka-0.9.0/lib/rdkafka/abstract_handle.rb:52:in `block in wait'
  2021-08-20 05:05:09 +0000 [warn]: #0 /opt/bitnami/fluentd/gems/rdkafka-0.9.0/lib/rdkafka/abstract_handle.rb:49:in `loop'
  2021-08-20 05:05:09 +0000 [warn]: #0 /opt/bitnami/fluentd/gems/rdkafka-0.9.0/lib/rdkafka/abstract_handle.rb:49:in `wait'
  2021-08-20 05:05:09 +0000 [warn]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-kafka-0.16.0/lib/fluent/plugin/out_rdkafka2.rb:325:in `block in write'
  2021-08-20 05:05:09 +0000 [warn]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-kafka-0.16.0/lib/fluent/plugin/out_rdkafka2.rb:324:in `each'
  2021-08-20 05:05:09 +0000 [warn]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-kafka-0.16.0/lib/fluent/plugin/out_rdkafka2.rb:324:in `write'
  2021-08-20 05:05:09 +0000 [warn]: #0 /opt/bitnami/fluentd/gems/fluentd-1.12.2/lib/fluent/plugin/output.rb:1136:in `try_flush'
  2021-08-20 05:05:09 +0000 [warn]: #0 /opt/bitnami/fluentd/gems/fluentd-1.12.2/lib/fluent/plugin/output.rb:1448:in `flush_thread_run'
  2021-08-20 05:05:09 +0000 [warn]: #0 /opt/bitnami/fluentd/gems/fluentd-1.12.2/lib/fluent/plugin/output.rb:462:in `block (2 levels) in start'
  2021-08-20 05:05:09 +0000 [warn]: #0 /opt/bitnami/fluentd/gems/fluentd-1.12.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2021-08-20 05:05:15 +0000 [warn]: #0 Send exception occurred: Waiting for delivery timed out after 5 seconds at /opt/bitnami/fluentd/gems/rdkafka-0.9.0/lib/rdkafka/abstract_handle.rb:52:in `block in wait'
```

My Dockerfile is like:
```
FROM bitnami/fluentd:1.12.2-debian-10-r4

USER root

RUN install_packages build-essential libsasl2-2 libsasl2-modules-gssapi-mit libsasl2-dev ca-certificates
RUN fluent-gem install rdkafka --no-document

...
```

### To Reproduce

Emit any message, like: `curl -X POST -d 'json={"json":"test"}' http://127.0.0.1:9880`

### Expected behavior

I expect to see a more descriptive error message.
Ideally, there'd be an example in the documentation.

### Your Environment

```markdown
- Fluentd version:
- TD Agent version: n/a
- fluent-plugin-kafka version:
- ruby-kafka version:
- Operating system:
- Kernel version:
```

### Your Configuration

<system>
  log_level debug
</system>

<label @FLUENT_LOG>
  <match fluent.*>
    @type stdout
  </match>
</label>

# Input
<source>
  @type http
  port 9880
  bind 0.0.0.0
  body_size_limit 32m
  keepalive_timeout 10s
</source>

<match *>
  @type copy

  # Output to stdout
  <store>
      @type stdout
  </store>

  # Output to EventHub
  <store>
      @type rdkafka2
      @log_level debug

      brokers              xxx.servicebus.windows.net:9093
      default_topic         'zero'

      <format>
        @type json
      </format>

      <inject>
        tag_key tag
        time_key time
      </inject>

      <buffer topic>
        flush_interval 2s
      </buffer>

      ssl_ca_certs_from_system true
      max_send_retries  1
      required_acks     -1
      ack_timeout       nil

      rdkafka_options {
        "log_level" : 7,
        "request.timeout.ms": 5000,

        "security.protocol": "sasl_ssl",
        "ssl.ca.location": "/etc/ssl/certs/",
        "sasl.mechanism": "PLAIN",
        "sasl.username":     "$ConnectionString",
        "sasl.password": "Endpoint=sb://xxx.servicebus.windows.net/;SharedAccessKeyName=xxx;SharedAccessKey=xxx;EntityPath=xxx"
      }

      rdkafka_delivery_handle_poll_timeout 5
  
  </store>

</match>

### Your Error Log

```shell
...
2021-08-20 05:11:57 +0000 [debug]: #0 adding store type="stdout"
2021-08-20 05:11:57 +0000 [debug]: #0 adding store type="rdkafka2"
2021-08-20 05:11:57 +0000 [info]: adding source type="http"
2021-08-20 05:11:57 +0000 [info]: #0 starting fluentd worker pid=31 ppid=1 worker=0
2021-08-20 05:11:57 +0000 [debug]: #0 buffer started instance=46978703552640 stage_size=0 queue_size=0
2021-08-20 05:11:57 +0000 [debug]: #0 listening http bind="0.0.0.0" port=9880
2021-08-20 05:11:57 +0000 [debug]: #0 flush_thread actually running
2021-08-20 05:11:57 +0000 [debug]: #0 enqueue_thread actually running
2021-08-20 05:11:57 +0000 [info]: #0 fluentd worker is now running worker=0
2021-08-20 05:11:57.511071478 +0000 fluent.info: {"pid":31,"ppid":1,"worker":0,"message":"starting fluentd worker pid=31 ppid=1 worker=0"}
2021-08-20 05:11:57.511259669 +0000 fluent.debug: {"instance":46978703552640,"stage_size":0,"queue_size":0,"message":"buffer started instance=46978703552640 stage_size=0 queue_size=0"}
2021-08-20 05:11:57.511942111 +0000 fluent.debug: {"bind":"0.0.0.0","port":9880,"message":"listening http bind=\"0.0.0.0\" port=9880"}
2021-08-20 05:11:57.512143971 +0000 fluent.debug: {"message":"flush_thread actually running"}
2021-08-20 05:11:57.512323582 +0000 fluent.debug: {"message":"enqueue_thread actually running"}
2021-08-20 05:11:57.514018507 +0000 fluent.info: {"worker":0,"message":"fluentd worker is now running worker=0"}
2021-08-20 05:12:01.478888383 +0000 : {"json":"test"}
#<Thread:0x000055742a8fa658@/opt/bitnami/fluentd/gems/rdkafka-0.9.0/lib/rdkafka/config.rb:17 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        3: from /opt/bitnami/fluentd/gems/rdkafka-0.9.0/lib/rdkafka/config.rb:18:in `block in <class:Config>'
        2: from /opt/bitnami/fluentd/gems/rdkafka-0.9.0/lib/rdkafka/config.rb:18:in `loop'
        1: from /opt/bitnami/fluentd/gems/rdkafka-0.9.0/lib/rdkafka/config.rb:20:in `block (2 levels) in <class:Config>'
/opt/bitnami/fluentd/gems/fluent-plugin-kafka-0.16.0/lib/fluent/plugin/out_rdkafka2.rb:113:in `add': wrong number of arguments (given 2, expected 1) (ArgumentError)
```
```


### Additional context

I'm happy to provide more info and/or debug further.

**Comment by kenhys** [comment]
I'm not sure but it seems that this issue is caused by change which is introduced since rdkafka-0.9.0,
https://github.com/appsignal/rdkafka-ruby/pull/97
 how about trying to use 0.8.1? does it solves error?

**Comment by scharissis-wx** [comment]
Hello,

Thank you for your response.

I tried with v0.8.1 and it indeed does work - I can see my events arrive into EventHub.
However, I do see these debug logs; not sure if they are of concern?:

```
2021-09-02 23:22:46 +0000 [debug]: #0 rdkafka: [thrd:sasl_ssl://test-kafka.servicebus.windows.net:9093/bootstrap]: sasl_ssl://test-kafka.servicebus.windows.net:9093/bootstrap: Protocol parse failure for ApiVersion v3 at 3/10 (rd_kafka_handle_ApiVersion:1911) (incorrect broker.version.fallback?)
2021-09-02 23:22:46.094771433 +0000 fluent.debug: {"message":"rdkafka: [thrd:sasl_ssl://test-kafka.servicebus.windows.net:9093/bootstrap]: sasl_ssl://test-kafka.servicebus.windows.net:9093/bootstrap: Protocol parse failure for ApiVersion v3 at 3/10 (rd_kafka_handle_ApiVersion:1911) (incorrect broker.version.fallback?)"}
2021-09-02 23:22:46 +0000 [debug]: #0 rdkafka: [thrd:sasl_ssl://test-kafka.servicebus.windows.net:9093/bootstrap]: sasl_ssl://test-kafka.servicebus.windows.net:9093/bootstrap: ApiArrayCnt -1 out of range
2021-09-02 23:22:46.095101946 +0000 fluent.debug: {"message":"rdkafka: [thrd:sasl_ssl://test-kafka.servicebus.windows.net:9093/bootstrap]: sasl_ssl://test-kafka.servicebus.windows.net:9093/bootstrap: ApiArrayCnt -1 out of range"}
```

Thank you for your help.

**Comment by davide-bolcioni** [comment]
I tried 0.10.0 and it has the same error.

With 0.8.1 I have the following errors:
```
{"time":"2021-09-07 23:49:44 +0000","level":"error","message":"[kafka] rdkafka: 
[thrd:ssl://10.7.53.125:9093/bootstrap]: ssl://10.7.53.125:9093/bootstrap: Disco
nnected (after 179ms in state UP)","worker_id":3}
{"time":"2021-09-07 23:49:44 +0000","level":"error","message":"[kafka] rdkafka: [thrd:ssl://10.7.53.125:9093/bootstrap]: ssl://10.7.53.125:9093/bootstrap: Disconnected (after 383ms in state UP)","worker_id":3}
{"time":"2021-09-07 23:49:45 +0000","level":"error","message":"[kafka] rdkafka: [thrd:ssl://10.7.54.73:9093/bootstrap]: ssl://10.7.54.73:9093/bootstrap: Disconnected (after 607ms in state UP)","worker_id":3}
{"time":"2021-09-07 23:49:45 +0000","level":"error","message":"[kafka] rdkafka: [thrd:ssl://10.7.52.87:9093/bootstrap]: ssl://10.7.52.87:9093/bootstrap: Disconnected (after 360ms in state UP)","worker_id":3}
{"time":"2021-09-07 23:49:45 +0000","level":"error","message":"[kafka] rdkafka: [thrd:ssl://10.7.52.87:9093/bootstrap]: 3/3 brokers are down","worker_id":3}
```

**Comment by davide-bolcioni** [comment]
I tried 0.10.0 and it has the same error.

**Comment by ashie** [comment]
Hmm, logger mechanism in rdkafka-ruby is changed since 0.9.0
https://github.com/appsignal/rdkafka-ruby/commit/3f9e5045e09420b5213859b02fae894bb001caf2#diff-98e932d49ef97cb9149e0d0e280d10f841f644f6f1b3b67313552fff22b16a33

We should follow this change.

**Comment by ashie** [comment]
@scharissis-wx @davide-bolcioni Using rdkafka 0.8.0 might avoid this issue.
