### ISSUE TITLE
DeliveryFailed log does not provide useful debugging information

### ISSUE THREAD

**Issue by brsolomon-deloitte** [fluent/fluent-plugin-kafka#431]
### Describe the bug

DeliveryFailed log does not provide useful debugging information.

It simply indicates that fluentd failed to send events to Kafka without a hint as to the reason why. Is it not possible to extract any actual meaningful information as to why the send failed?

### To Reproduce

```
2021-11-03 15:18:07 +0000 [warn]: #0 Send exception occurred: Failed to send messages to nginx/0
2021-11-03 15:18:07 +0000 [warn]: #0 Exception Backtrace : /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-kafka-0.16.3/lib/fluent/plugin/kafka_producer_ext.rb:242:in `deliver_messages_with_retries'
/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-kafka-0.16.3/lib/fluent/plugin/kafka_producer_ext.rb:128:in `deliver_messages'
/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-kafka-0.16.3/lib/fluent/plugin/out_kafka2.rb:279:in `write'
/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/plugin/output.rb:1138:in `try_flush'
/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/plugin/output.rb:1450:in `flush_thread_run'
/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/plugin/output.rb:462:in `block (2 levels) in start'
/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2021-11-03 15:18:07 +0000 [info]: #0 initialized kafka producer: fluentd
2021-11-03 15:18:07 +0000 [debug]: #0 taking back chunk for errors. chunk="5cfe3218839918fe0cf236cc63388ddb"
2021-11-03 15:18:07 +0000 [warn]: #0 failed to flush the buffer. retry_time=2 next_retry_seconds=2021-11-03 15:18:09 1269938388767099267273/4398046511104000000000 +0000 chunk="5cfe3218839918fe0cf236cc63388ddb" error_class=Kafka::DeliveryFailed error="Failed to send messages to nginx/0"
2021-11-03 15:18:07 +0000 [warn]: #0 suppressed same stacktrace
```

> Failed to send messages to nginx/0

Why? What failed? Was Kafka reachable but threw an exception? I can already tell that fluentd failed to send messages based on the existence of this stacktrace.

Kafka is reachable:

```bash
$ nc -vz -w 9 172.xx.xx.xx 32123
Connection to 172.xx.xx.xx 32123 port [tcp/*] succeeded!
```

### Expected behavior

Useful logs

### Your Environment

```markdown
- Fluentd version:
- TD Agent version:
- fluent-plugin-kafka version:
- ruby-kafka version:
- Operating system:
- Kernel version:
```

### Your Configuration

n/a

### Your Error Log

```
2021-11-03 15:18:07 +0000 [warn]: #0 Send exception occurred: Failed to send messages to nginx/0
2021-11-03 15:18:07 +0000 [warn]: #0 Exception Backtrace : /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-kafka-0.16.3/lib/fluent/plugin/kafka_producer_ext.rb:242:in `deliver_messages_with_retries'
/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-kafka-0.16.3/lib/fluent/plugin/kafka_producer_ext.rb:128:in `deliver_messages'
/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-kafka-0.16.3/lib/fluent/plugin/out_kafka2.rb:279:in `write'
/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/plugin/output.rb:1138:in `try_flush'
/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/plugin/output.rb:1450:in `flush_thread_run'
/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/plugin/output.rb:462:in `block (2 levels) in start'
/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2021-11-03 15:18:07 +0000 [info]: #0 initialized kafka producer: fluentd
2021-11-03 15:18:07 +0000 [debug]: #0 taking back chunk for errors. chunk="5cfe3218839918fe0cf236cc63388ddb"
2021-11-03 15:18:07 +0000 [warn]: #0 failed to flush the buffer. retry_time=2 next_retry_seconds=2021-11-03 15:18:09 1269938388767099267273/4398046511104000000000 +0000 chunk="5cfe3218839918fe0cf236cc63388ddb" error_class=Kafka::DeliveryFailed error="Failed to send messages to nginx/0"
2021-11-03 15:18:07 +0000 [warn]: #0 suppressed same stacktrace
```

**Comment by brsolomon-deloitte** [comment]
Using

```
  @log_level trace
  get_kafka_client_log true
```

gave me some more useful info, but IMO, the root message of this exception backtrace at debug level is not helpful.

**Comment by brsolomon-deloitte** [comment]
Closing this as I see that the documentation has already [made an effort to mention this](https://github.com/fluent/fluent-plugin-kafka/blob/1535c73d827cf8b1e18c2d266cf25e655e7db1c6/README.md#output-plugin)
