### ISSUE TITLE
Segmentation fault? 

### ISSUE THREAD

**Issue by dtboctor** [fluent/fluent-plugin-kafka#47]
Sometimes on certain messages it seems that I'm getting a segmentation fault error?  If I clear out the buffer to get rid of all messages the fault stops.    Here's what I'm seeing:

```
2016-03-27_18:09:09.88924 /opt/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/yajl-ruby-1.2.0/lib/yajl.rb:73: [BUG] Segmentation fault at 0x0000007ffffffb
2016-03-27_18:09:09.88928 ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-linux]
2016-03-27_18:09:09.88928
2016-03-27_18:09:09.88928 -- Control frame information -----------------------------------------------
2016-03-27_18:09:09.88929 c:0016 p:---- s:0087 e:000086 CFUNC  :encode
2016-03-27_18:09:09.88929 c:0015 p:0048 s:0082 e:000081 METHOD /opt/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/yajl-ruby-1.2.0/lib/yajl.rb:73
2016-03-27_18:09:09.88929 c:0014 p:0017 s:0074 e:000073 BLOCK  /opt/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/fluent-plugin-kafka-0.1.3/lib/fluent/plugin/out_kafka_buffered.rb:117 [FINISH]
2016-03-27_18:09:09.88930 c:0013 p:---- s:0069 e:000068 CFUNC  :call
2016-03-27_18:09:09.88931 c:0012 p:0131 s:0063 e:000062 BLOCK  /opt/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/fluent-plugin-kafka-0.1.3/lib/fluent/plugin/out_kafka_buffered.rb:157 [FINISH]
2016-03-27_18:09:09.88932 c:0011 p:---- s:0054 e:000053 CFUNC  :each
2016-03-27_18:09:09.88933 c:0010 p:0031 s:0051 e:000050 BLOCK  /opt/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/fluentd-0.12.22/lib/fluent/buffer.rb:123
2016-03-27_18:09:09.88933 c:0009 p:0018 s:0047 e:000046 METHOD /opt/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/fluentd-0.12.22/lib/fluent/plugin/buf_file.rb:71
2016-03-27_18:09:09.88934 c:0008 p:0007 s:0043 E:000de0 METHOD /opt/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/fluentd-0.12.22/lib/fluent/buffer.rb:120
2016-03-27_18:09:09.88935 c:0007 p:0031 s:0039 E:000fa8 METHOD /opt/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/fluent-plugin-kafka-0.1.3/lib/fluent/plugin/out_kafka_buffered.rb:148
2016-03-27_18:09:09.88935 c:0006 p:0010 s:0030 e:000029 METHOD /opt/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/fluentd-0.12.22/lib/fluent/buffer.rb:351
2016-03-27_18:09:09.88936 c:0005 p:0038 s:0025 e:000024 METHOD /opt/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/fluentd-0.12.22/lib/fluent/buffer.rb:330
2016-03-27_18:09:09.88936 c:0004 p:0157 s:0019 e:000018 METHOD /opt/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/fluentd-0.12.22/lib/fluent/output.rb:338
2016-03-27_18:09:09.88937 c:0003 p:0063 s:0009 e:000008 METHOD /opt/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/fluentd-0.12.22/lib/fluent/output.rb:149 [FINISH]
2016-03-27_18:09:09.88938 c:0002 p:---- s:0004 e:000003 IFUNC
2016-03-27_18:09:09.88939 c:0001 p:---- s:0002 e:000001 TOP    [FINISH]
2016-03-27_18:09:09.88940
2016-03-27_18:09:09.88940 /opt/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/fluentd-0.12.22/lib/fluent/output.rb:149:in `run'
2016-03-27_18:09:09.88940 /opt/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/fluentd-0.12.22/lib/fluent/output.rb:338:in `try_flush'
2016-03-27_18:09:09.88940 /opt/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/fluentd-0.12.22/lib/fluent/buffer.rb:330:in `pop'
2016-03-27_18:09:09.88940 /opt/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/fluentd-0.12.22/lib/fluent/buffer.rb:351:in `write_chunk'
2016-03-27_18:09:09.88941 /opt/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/fluent-plugin-kafka-0.1.3/lib/fluent/plugin/out_kafka_buffered.rb:148:in `write'
2016-03-27_18:09:09.88941 /opt/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/fluentd-0.12.22/lib/fluent/buffer.rb:120:in `msgpack_each'
2016-03-27_18:09:09.88941 /opt/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/fluentd-0.12.22/lib/fluent/plugin/buf_file.rb:71:in `open'
2016-03-27_18:09:09.88941 /opt/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/fluentd-0.12.22/lib/fluent/buffer.rb:123:in `block in msgpack_each'
2016-03-27_18:09:09.88941 /opt/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/fluentd-0.12.22/lib/fluent/buffer.rb:123:in `each'
2016-03-27_18:09:09.88942 /opt/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/fluent-plugin-kafka-0.1.3/lib/fluent/plugin/out_kafka_buffered.rb:157:in `block in write'
```

Looks like it could be an incompatibility between yajl and one of my messages but I'm not sure.

**Comment by htgc** [comment]
Sorry for late response. May I get the data? Thanks,

**Comment by repeatedly** [comment]
If the problem happens with latest version and ruby, please reopen the issue.
