### ISSUE TITLE
Could not connect to leader for partition/ Unknown Partition

### ISSUE THREAD

**Issue by 12ushan** [fluent/fluent-plugin-kafka#518]
### Describe the bug

Hi, as mentioned here in the fluentd [discussion](https://github.com/fluent/fluentd/discussions/4105#discussion-4984154) page.

To summarise: We have fluentd running in kubernetes sending logs to kafka (Amazon MSK). We're seeing errors intermittently mentioning "unknown partition"/Could not connect to leader for partition" where fluentd is trying to send to partition 14,15 or 16 for example when we only have 12 partitions on the topic. We've tried both kafka2 and rdkafka2 plugin as the type but get one of the error message mentioned above.

We have not been able to replicate this issue with a local setup so we're wondering if anyone has seen this issue at all? 

### To Reproduce

Use this plugin on fluentd running on kubernetes sending any logs to kafka on amazon MSK

### Expected behavior

The plugin should fetch from AWS the partition numbers that exist on the topic

### Your Environment

```markdown
- Fluentd version: 1.15.3
- fluent-plugin-kafka version: 0.19.3
- ruby-kafka version: 1.5.0
- Operating system: Debian GNU/Linux 11
- Kernel version: Linux 5.10.217-205.860.amzn2.x86_64 x86_64
- Kubernetes version: v1.28.12-eks-a18cd3a 
- Amazon MSK running Apache Kafka Version 3.5.1
```

### Your Configuration
```
<match **>
  <store>
    type kafka2
    brokers "kafka:9092"
    default_topic "logging.kubernetes.events"
    <buffer topic>
      flush_interval 3s
    </buffer>
    <format>
      @type json
    </format>
  </store>
</match>
```
### Your Error Log

```shell
[error]: #0 Could not connect to leader for partition logging.kubernetes.events/19: no partition 19 in topic logging.kubernetes.events 

OR 

[warn]: #0 Send exception occurred: Local: Unknown partition (unknown_partition) at /fluentd/vendor/bundle/ruby/3.1.0/gems/rdkafka-0.18.0/lib/rdkafka/producer.rb:363:in `produce'
```

### Additional context

We have seen the issue on older version of amazon msk too

**Comment by amitkumarjha** [comment]
We have exactly the same issue in fluentd

**Comment by cafe24-jmpark02** [comment]
We had the same issue. There were logs being sent to Fluentd in JSON format that used partition, offset, and topic as keys. The issue was resolved when we renamed those key names.

**Comment by Watson1978** [comment]
If the log data you sent contains a key named `partition`, it will be used as the destination partition number by default.


## Reproduce
Create topic
```sh
$ kafka-topics --create --topic test_topic --bootstrap-server 127.0.0.1:9092 --partitions 5
```

Fluentd configuration
```
<system>
  rpc_endpoint 127.0.0.1:24444
</system>

<source>
  @type sample
  sample { "message" : "hello", "partition": 6 }
  tag sample
  rate 5
  size 5
</source>

<match sample>
  @type rdkafka2

  # broker
  brokers "localhost:9092"

  <buffer topic>
    @type file
    path "#{File.expand_path('~/tmp/fluentd/buffer')}"
    flush_interval 3s
  </buffer>

  <format>
    @type json
  </format>

  # topic settings
  default_topic test_topic
</match>
```

Result
```
2025-10-03 18:51:10 +0900 [warn]: #0 Send exception occurred: Local: Unknown partition (unknown_partition) at /home/watson/.rbenv/versions/3.4.6/lib/ruby/gems/3.4.0/gems/rdkafka-0.18.0/lib/rdkafka/producer.rb:363:in 'Rdkafka::Producer#produce'
2025-10-03 18:51:10 +0900 [warn]: #0 failed to flush the buffer. retry_times=0 next_retry_time=2025-10-03 18:51:11 +0900 chunk="6403dd4b4e85fda9ca51cd0abbc0917b" error_class=Rdkafka::RdkafkaError error="Local: Unknown partition (unknown_partition)"
  2025-10-03 18:51:10 +0900 [warn]: #0 /home/watson/.rbenv/versions/3.4.6/lib/ruby/gems/3.4.0/gems/rdkafka-0.18.0/lib/rdkafka/producer.rb:363:in 'Rdkafka::Producer#produce'
  2025-10-03 18:51:10 +0900 [warn]: #0 /home/watson/.rbenv/versions/3.4.6/lib/ruby/gems/3.4.0/gems/fluent-plugin-kafka-0.19.5/lib/fluent/plugin/out_rdkafka2.rb:459:in 'block in Fluent::Rdkafka2Output#enqueue_with_retry'
  2025-10-03 18:51:10 +0900 [warn]: #0 <internal:kernel>:168:in 'Kernel#loop'
  2025-10-03 18:51:10 +0900 [warn]: #0 /home/watson/.rbenv/versions/3.4.6/lib/ruby/gems/3.4.0/gems/fluent-plugin-kafka-0.19.5/lib/fluent/plugin/out_rdkafka2.rb:456:in 'Fluent::Rdkafka2Output#enqueue_with_retry'
  2025-10-03 18:51:10 +0900 [warn]: #0 /home/watson/.rbenv/versions/3.4.6/lib/ruby/gems/3.4.0/gems/fluent-plugin-kafka-0.19.5/lib/fluent/plugin/out_rdkafka2.rb:427:in 'block in Fluent::Rdkafka2Output#write'
  2025-10-03 18:51:10 +0900 [warn]: #0 /home/watson/src/fluentd/lib/fluent/event.rb:320:in 'MessagePack::Unpacker#each'
  2025-10-03 18:51:10 +0900 [warn]: #0 /home/watson/src/fluentd/lib/fluent/event.rb:320:in 'block in Fluent::ChunkMessagePackEventStreamer#each'
  2025-10-03 18:51:10 +0900 [warn]: #0 /home/watson/src/fluentd/lib/fluent/plugin/buffer/file_chunk.rb:171:in 'Fluent::Plugin::Buffer::FileChunk#open'
  2025-10-03 18:51:10 +0900 [warn]: #0 /home/watson/src/fluentd/lib/fluent/event.rb:319:in 'Fluent::ChunkMessagePackEventStreamer#each'
  2025-10-03 18:51:10 +0900 [warn]: #0 /home/watson/.rbenv/versions/3.4.6/lib/ruby/gems/3.4.0/gems/fluent-plugin-kafka-0.19.5/lib/fluent/plugin/out_rdkafka2.rb:397:in 'Fluent::Rdkafka2Output#write'
  2025-10-03 18:51:10 +0900 [warn]: #0 /home/watson/src/fluentd/lib/fluent/plugin/output.rb:1212:in 'Fluent::Plugin::Output#try_flush'
  2025-10-03 18:51:10 +0900 [warn]: #0 /home/watson/src/fluentd/lib/fluent/plugin/output.rb:1527:in 'Fluent::Plugin::Output#flush_thread_run'
  2025-10-03 18:51:10 +0900 [warn]: #0 /home/watson/src/fluentd/lib/fluent/plugin/output.rb:490:in 'block (2 levels) in Fluent::Plugin::Output#start'
  2025-10-03 18:51:10 +0900 [warn]: #0 /home/watson/src/fluentd/lib/fluent/plugin_helper/thread.rb:78:in 'block in Fluent::PluginHelper::Thread#thread_create'
```


So, we might need a data you sent to investigate the issue...
