### ISSUE TITLE
Does not work with td-agent

### ISSUE THREAD

**Issue by alanyee** [fluent/fluent-plugin-kafka#74]
I install via `gem install fluent-plugin-kafka`, but I still keep getting

```
[error]: fluent/supervisor.rb:373:rescue in main_process: config error file="/etc/td-agent/td-agent.conf" error="Unknown input plugin 'kafka'. Run 'gem search -rd fluent-plugin' to find plugins"
```

**Comment by repeatedly** [comment]
See FAQ: http://docs.fluentd.org/articles/faq#i-installed-td-agent-and-want-to-add-custom-plugins-how-do-i-do-it

**Comment by alanyee** [comment]
I managed to install it, but now I have
```
from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:324:in `to_spec'
from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
from /opt/td-agent/embedded/bin/fluentd:22:in `<top (required)>'
from /usr/sbin/td-agent:7:in `load'
from /usr/sbin/td-agent:7:in `<main>'
```

**Comment by repeatedly** [comment]
Maybe, the problem is not the td-agent. Here is the result of my Ubuntu 14.04 box.

```
$ sudo /usr/sbin/td-agent-gem install fluent-plugin-kafka --no-document
Fetching: ruby-kafka-0.3.14.gem (100%)
Successfully installed ruby-kafka-0.3.14
Fetching: zookeeper-1.4.11.gem (100%)
Building native extensions.  This could take a while...
Successfully installed zookeeper-1.4.11
Fetching: fluent-plugin-kafka-0.3.1.gem (100%)
Successfully installed fluent-plugin-kafka-0.3.1
3 gems installed
```

**Comment by alanyee** [comment]
I guess I should clarify. I have already successfully installed the plugins, or at least, gotten the same installation success prompt as you just posted. I get the above error from `/etc/init.d/td-agent start`. In other words, td-agent will not start.

**Comment by repeatedly** [comment]
Worked so td-agent itself doesn't have a problem.

```
2016-09-02 15:14:30 -0700 [info]: reading config file path="/etc/td-agent/td-agent.conf"
2016-09-02 15:14:30 -0700 [info]: starting fluentd-0.12.26
2016-09-02 15:14:30 -0700 [info]: gem 'fluent-mixin-config-placeholders' version '0.4.0'
2016-09-02 15:14:30 -0700 [info]: gem 'fluent-mixin-plaintextformatter' version '0.2.6'
2016-09-02 15:14:30 -0700 [info]: gem 'fluent-plugin-kafka' version '0.3.1'
2016-09-02 15:14:30 -0700 [info]: gem 'fluent-plugin-mongo' version '0.7.13'
2016-09-02 15:14:30 -0700 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '1.5.5'
2016-09-02 15:14:30 -0700 [info]: gem 'fluent-plugin-s3' version '0.6.8'
2016-09-02 15:14:30 -0700 [info]: gem 'fluent-plugin-scribe' version '0.10.14'
2016-09-02 15:14:30 -0700 [info]: gem 'fluent-plugin-td' version '0.10.28'
2016-09-02 15:14:30 -0700 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.2'
2016-09-02 15:14:30 -0700 [info]: gem 'fluent-plugin-webhdfs' version '0.4.2'
2016-09-02 15:14:30 -0700 [info]: gem 'fluentd' version '0.12.26'
2016-09-02 15:14:30 -0700 [info]: adding match pattern="kafka.**" type="kafka_buffered"
2016-09-02 15:14:30 -0700 [info]: brokers has been set directly: ["localhost:9022"]
2016-09-02 15:14:30 -0700 [info]: adding match pattern="debug.**" type="stdout"
2016-09-02 15:14:30 -0700 [info]: adding source type="forward"
2016-09-02 15:14:30 -0700 [info]: using configuration file: <ROOT>
  <match kafka.**>
    @type kafka_buffered
    brokers localhost:9022
  </match>
  <match debug.**>
    @type stdout
  </match>
  <source>
    @type forward
  </source>
</ROOT>
2016-09-02 15:14:30 -0700 [info]: initialized kafka producer: kafka
2016-09-02 15:14:30 -0700 [info]: listening fluent socket on 0.0.0.0:24224
```

**Comment by alanyee** [comment]
What does my error message say? How do I fix it?

**Comment by repeatedly** [comment]
I'm not sure because I didn't hit such error with td-agent.
I know some companies uses fluent-plugin-kafka with td-agent and there is no such error report.
I assume your environment or your installation process have a problem for td-agent.

**Comment by repeatedly** [comment]
If you want to know the root cause,
try several installation approaches.

- use plain server for td-agent and fluent-plugin-kafka installation. plain means 'no setup additional software'
- setup server step by step.

Former should work because I and other developers don't have a problem.
I'm not sure how you setup your server but your one installation step causes the problem.
So step by step check may find the root cause.
