### ISSUE TITLE
Flush error with invalid fluentd record

### ISSUE THREAD

**Issue by ogibayashi** [fluent/fluent-plugin-kafka#80]
Hello,

Last day, out_kafka_buffered in my fluentd cluster had the following error.

```
2016-10-06 17:10:27 +0900 [warn]: temporarily failed to flush the buffer. next_retry=2016-10-06 17:10:28 +0900 error_class="NoMethodError" error="undefined method `[]=' for nil:NilClass" plugin_id="to_kafka"
  2016-10-06 17:10:27 +0900 [warn]: /home/myuser/local/ruby-2.2/lib/ruby/gems/2.2.0/gems/fluent-plugin-kafka-0.2.2/lib/fluent/plugin/out_kafka_buffered.rb:215:in `block in write'
  2016-10-06 17:10:27 +0900 [warn]: /home/myuser/local/ruby-2.2/lib/ruby/gems/2.2.0/gems/fluentd-0.12.28/lib/fluent/buffer.rb:123:in `each'
  2016-10-06 17:10:27 +0900 [warn]: /home/myuser/local/ruby-2.2/lib/ruby/gems/2.2.0/gems/fluentd-0.12.28/lib/fluent/buffer.rb:123:in `block in msgpack_each'
  2016-10-06 17:10:27 +0900 [warn]: /home/myuser/local/ruby-2.2/lib/ruby/gems/2.2.0/gems/fluentd-0.12.28/lib/fluent/plugin/buf_file.rb:71:in `open'
  2016-10-06 17:10:27 +0900 [warn]: /home/myuser/local/ruby-2.2/lib/ruby/gems/2.2.0/gems/fluentd-0.12.28/lib/fluent/buffer.rb:120:in `msgpack_each'
  2016-10-06 17:10:27 +0900 [warn]: /home/myuser/local/ruby-2.2/lib/ruby/gems/2.2.0/gems/fluent-plugin-kafka-0.2.2/lib/fluent/plugin/out_kafka_buffered.rb:210:in `write'
  2016-10-06 17:10:27 +0900 [warn]: /home/myuser/local/ruby-2.2/lib/ruby/gems/2.2.0/gems/fluentd-0.12.28/lib/fluent/buffer.rb:354:in `write_chunk'
  2016-10-06 17:10:27 +0900 [warn]: /home/myuser/local/ruby-2.2/lib/ruby/gems/2.2.0/gems/fluentd-0.12.28/lib/fluent/buffer.rb:333:in `pop'
  2016-10-06 17:10:27 +0900 [warn]: /home/myuser/local/ruby-2.2/lib/ruby/gems/2.2.0/gems/fluentd-0.12.28/lib/fluent/output.rb:338:in `try_flush'
  2016-10-06 17:10:27 +0900 [warn]: /home/myuser/local/ruby-2.2/lib/ruby/gems/2.2.0/gems/fluentd-0.12.28/lib/fluent/output.rb:149:in `run'
2016-10-06 17:10:28 +0900 [warn]: Send exception occurred: undefined method `[]=' for nil:NilClass
2016-10-06 17:10:28 +0900 [info]: initialized kafka producer: kafka  
```

From the errors from another fluentd which receives the same log, I realized that some of our client sent records with `nil`.

```
2016-10-06 17:10:08 +0900 [warn]: dump an error event: error_class=NoMethodError error="undefined method `/' for \"POST\":String" tag="sometag" time=1475741408 record={"time"=>"POST", "record"=>nil}
```

I know that this is the issue of the sender, but since our fluentd cluster aggregates logs from so many different client, this can happen. And once this happens, other normal logs will also get stuck in the buffer. So, it would be great if out_kafka_buffered could check such invalid record and drop them so that other normal logs will not be affected.

**Comment by repeatedly** [comment]
Hmm... catching invalid records and logging it in error is one idea. I will do it.

**Comment by ogibayashi** [comment]
Thanks! That's great.

**Comment by ogibayashi** [comment]
Thank you so much for the fix. I have upgrade to 0.3.3.
