### ISSUE TITLE
Kafka::DeliveryFailed

### ISSUE THREAD

**Issue by ahsandar** [fluent/fluent-plugin-kafka#81]
I can successfully connect and create a topic but the message delivery fails, as there is no detail about the error, its hard to point out the issue, and where are the messages buffered ?  can we specify the location if its on a file ?
```
2016-10-12 12:11:44 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2016-10-12 12:11:43 +0800 error_class="Kafka::DeliveryFailed" error="Failed to send messages to EnigmaProxyStaging/0" plugin_id="object:3fe70b58a354"
  2016-10-12 12:11:44 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.15/lib/kafka/producer.rb:329:in `deliver_messages_with_retries'
  2016-10-12 12:11:44 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.15/lib/kafka/producer.rb:243:in `block in deliver_messages'
  2016-10-12 12:11:44 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.15/lib/kafka/instrumenter.rb:21:in `call'
  2016-10-12 12:11:44 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.15/lib/kafka/instrumenter.rb:21:in `instrument'
  2016-10-12 12:11:44 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.15/lib/kafka/producer.rb:236:in `deliver_messages'
  2016-10-12 12:11:44 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kafka-0.3.1/lib/fluent/plugin/out_kafka_buffered.rb:220:in `block in write'
  2016-10-12 12:11:44 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/plugin/buf_memory.rb:67:in `feed_each'
  2016-10-12 12:11:44 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/plugin/buf_memory.rb:67:in `msgpack_each'
  2016-10-12 12:11:44 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kafka-0.3.1/lib/fluent/plugin/out_kafka_buffered.rb:200:in `write'
  2016-10-12 12:11:44 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/buffer.rb:354:in `write_chunk'
  2016-10-12 12:11:44 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/buffer.rb:333:in `pop'
  2016-10-12 12:11:44 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/output.rb:338:in `try_flush'
  2016-10-12 12:11:44 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/output.rb:149:in `run'
2016-10-12 12:11:46 +0800 [warn]: Send exception occurred: Failed to send messages to EnigmaProxyStaging/0
2016-10-12 12:11:46 +0800 [info]: initialized kafka producer: kafka
2016-10-12 12:11:46 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2016-10-12 12:11:45 +0800 error_class="Kafka::DeliveryFailed" error="Failed to send messages to EnigmaProxyStaging/0" plugin_id="object:3fe70b58a354"
  2016-10-12 12:11:46 +0800 [warn]: suppressed same stacktrace
2016-10-12 12:11:48 +0800 [warn]: Send exception occurred: Failed to send messages to EnigmaProxyStaging/0
2016-10-12 12:11:48 +0800 [info]: initialized kafka producer: kafka
2016-10-12 12:11:48 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2016-10-12 12:11:49 +0800 error_class="Kafka::DeliveryFailed" error="Failed to send messages to EnigmaProxyStaging/0" plugin_id="object:3fe70b58a354"
  2016-10-12 12:11:48 +0800 [warn]: suppressed same stacktrace
2016-10-12 12:11:51 +0800 [warn]: Send exception occurred: Failed to send messages to EnigmaProxyStaging/0
2016-10-12 12:11:51 +0800 [info]: initialized kafka producer: kafka
2016-10-12 12:11:51 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2016-10-12 12:11:57 +0800 error_class="Kafka::DeliveryFailed" error="Failed to send messages to EnigmaProxyStaging/0" plugin_id="object:3fe70b58a354"
  2016-10-12 12:11:51 +0800 [warn]: suppressed same stacktrace
2016-10-12 12:11:59 +0800 [warn]: Send exception occurred: Failed to send messages to EnigmaProxyStaging/0
2016-10-12 12:11:59 +0800 [info]: initialized kafka producer: kafka
2016-10-12 12:11:59 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2016-10-12 12:12:14 +0800 error_class="Kafka::DeliveryFailed" error="Failed to send messages to EnigmaProxyStaging/0" plugin_id="object:3fe70b58a354"
```

**Comment by repeatedly** [comment]
> "Kafka::DeliveryFailed" error="Failed to send messages to EnigmaProxyStaging/0"

This error message is unclear... I will add getting log message from ruby-kafka feature.

> can we specify the location if its on a file ?

What does this sentence mean? file buffer location? 
From your log, you use memory buffer. If you want to use file bufffer, set `buffer_type file` in your configuration.

**Comment by ahsandar** [comment]
I can run 
`/root/kafka_2.11-0.10.0.1/bin/kafka-console-producer.sh --broker-list localhost:9092 --topic EnigmaProxyStaging` 
on the kafka server and push a message,

from `ruby-kafka` docs seems `Kafka::DeliveryFailed` is a generic error raised when it fails to flush buffer, apparently doesn't seems it will give much enough

**Comment by ahsandar** [comment]
@htgc I think its because I have kafka 0.10 and there is limited support by `ruby-kafka` , will try with kafka 0.9 and get back on this

**Comment by ahsandar** [comment]
same issue with `kafka-0.9.0.1`
```
2016-10-13 09:56:25 +0800 [warn]: Send exception occurred: Failed to send messages to EnigmaProxyStaging/0
2016-10-13 09:56:25 +0800 [info]: initialized kafka producer: kafka
2016-10-13 09:56:25 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2016-10-13 09:56:25 +0800 error_class="Kafka::DeliveryFailed" error="Failed to send messages to EnigmaProxyStaging/0" plugin_id="object:3fab034bc970"
  2016-10-13 09:56:25 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.15/lib/kafka/producer.rb:329:in `deliver_messages_with_retries'
  2016-10-13 09:56:25 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.15/lib/kafka/producer.rb:243:in `block in deliver_messages'
  2016-10-13 09:56:25 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.15/lib/kafka/instrumenter.rb:21:in `call'
  2016-10-13 09:56:25 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.15/lib/kafka/instrumenter.rb:21:in `instrument'
  2016-10-13 09:56:25 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.15/lib/kafka/producer.rb:236:in `deliver_messages'
  2016-10-13 09:56:25 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kafka-0.3.1/lib/fluent/plugin/out_kafka_buffered.rb:220:in `block in write'
  2016-10-13 09:56:25 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/buffer.rb:123:in `each'
  2016-10-13 09:56:25 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/buffer.rb:123:in `block in msgpack_each'
  2016-10-13 09:56:25 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/plugin/buf_file.rb:71:in `open'
  2016-10-13 09:56:25 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/buffer.rb:120:in `msgpack_each'
  2016-10-13 09:56:25 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kafka-0.3.1/lib/fluent/plugin/out_kafka_buffered.rb:200:in `write'
  2016-10-13 09:56:25 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/buffer.rb:354:in `write_chunk'
  2016-10-13 09:56:25 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/buffer.rb:333:in `pop'
  2016-10-13 09:56:25 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/output.rb:338:in `try_flush'
  2016-10-13 09:56:25 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/output.rb:149:in `run'
2016-10-13 09:56:27 +0800 [warn]: Send exception occurred: Failed to send messages to EnigmaProxyStaging/0
2016-10-13 09:56:27 +0800 [info]: initialized kafka producer: kafka
2016-10-13 09:56:27 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2016-10-13 09:56:27 +0800 error_class="Kafka::DeliveryFailed" error="Failed to send messages to EnigmaProxyStaging/0" plugin_id="object:3fab034bc970"
  2016-10-13 09:56:27 +0800 [warn]: suppressed same stacktrace
2016-10-13 09:56:28 +0800 [warn]: Send exception occurred: Failed to send messages to EnigmaProxyStaging/0
2016-10-13 09:56:28 +0800 [info]: initialized kafka producer: kafka
2016-10-13 09:56:28 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2016-10-13 09:56:30 +0800 error_class="Kafka::DeliveryFailed" error="Failed to send messages to EnigmaProxyStaging/0" plugin_id="object:3fab034bc970"
  2016-10-13 09:56:28 +0800 [warn]: suppressed same stacktrace
2016-10-13 09:56:31 +0800 [warn]: Send exception occurred: Failed to send messages to EnigmaProxyStaging/0
2016-10-13 09:56:31 +0800 [info]: initialized kafka producer: kafka
2016-10-13 09:56:31 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2016-10-13 09:56:39 +0800 error_class="Kafka::DeliveryFailed" error="Failed to send messages to EnigmaProxyStaging/0" plugin_id="object:3fab034bc970"
```

**Comment by ahsandar** [comment]
any idea what are these characters appended to each message
 `<92><CE>W<FE><EC>Ł<A7>message<DA>^Cr`

**Comment by repeatedly** [comment]
Could you apply following patch to get detailed error?

```
diff --git a/lib/fluent/plugin/out_kafka_buffered.rb b/lib/fluent/plugin/out_kafka_buffered.rb
index 4975c1a..71946d2 100644
--- a/lib/fluent/plugin/out_kafka_buffered.rb
+++ b/lib/fluent/plugin/out_kafka_buffered.rb
@@ -78,7 +78,7 @@ DESC
     end
     begin
       if @seed_brokers.length > 0
-        @kafka = Kafka.new(seed_brokers: @seed_brokers, client_id: @client_id, ssl_ca_cert: read_ssl_file(@ssl_ca_cert),
+        @kafka = Kafka.new(seed_brokers: @seed_brokers, client_id: @client_id, logger: log, ssl_ca_cert: read_ssl_file(@ssl_ca_cert),
                            ssl_client_cert: read_ssl_file(@ssl_client_cert), ssl_client_cert_key: read_ssl_file(@ssl_client_cert_key))
         log.info "initialized kafka producer: #{@client_id}"
       else
```

**Comment by ahsandar** [comment]
found the issue , it was `advertised.hostname` value in `kafka` `broker`  `server.properties` that needed to be set to external IP (as have producer in another cloud ), would be good if we can somehow get to display such errors,

Thanks for your time

**Comment by repeatedly** [comment]
Yeah. I just added this feature: https://github.com/fluent/fluent-plugin-kafka/pull/83
