### ISSUE TITLE
Failed to assign partitions

### ISSUE THREAD

**Issue by ahsandar** [fluent/fluent-plugin-kafka#97]
I had 1  topic with 2 partition , and created 3 more topics each with 2 partitions as evident from the image all got created fine (had to remove topic names and some identifiable information),  the data is successfully sent to the original topic but the new topic keeps getting  the error `Failed to assign partitions` logging out not much detail

```
2016-11-08 16:11:35 +0800 [info]: initialized kafka producer: kafka
2016-11-08 16:11:35 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2016-11-08 16:15:45 +0800 error_class="Kafka::DeliveryFailed" error="Failed to assign partitions to 2 messages" plugin_id="object:3fe8f04a2220"
  2016-11-08 16:11:35 +0800 [warn]: suppressed same stacktrace
2016-11-08 16:11:39 +0800 [warn]: Send exception occurred: Failed to assign partitions to 5 messages
2016-11-08 16:11:39 +0800 [info]: initialized kafka producer: kafka
2016-11-08 16:11:39 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2016-11-08 16:15:40 +0800 error_class="Kafka::DeliveryFailed" error="Failed to assign partitions to 5 messages" plugin_id="object:3fe8f04ae7c8"
  2016-11-08 16:11:39 +0800 [warn]: suppressed same stacktrace
2016-11-08 16:11:45 +0800 [warn]: Send exception occurred: Failed to assign partitions to 1 messages
2016-11-08 16:11:45 +0800 [info]: initialized kafka producer: kafka
2016-11-08 16:11:45 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2016-11-08 16:16:16 +0800 error_class="Kafka::DeliveryFailed" error="Failed to assign partitions to 1 messages" plugin_id="object:3fe8f04ca810"
  2016-11-08 16:11:45 +0800 [warn]: suppressed same stacktrace
```
![screen shot 2016-11-08 at 4](https://cloud.githubusercontent.com/assets/2472371/20092101/31273c98-a5d1-11e6-81ad-86cb7ec689ca.png)

**Comment by ahsandar** [comment]
could the plugin having this issue ?  is there a way to define random partition key  ? 
https://cwiki.apache.org/confluence/display/KAFKA/FAQ#FAQ-Whyisdatanotevenlydistributedamongpartitionswhenapartitioningkeyisnotspecified?
http://mail-archives.apache.org/mod_mbox/kafka-dev/201310.mbox/%3CCAFbh0Q0aVh%2Bvqxfy7H-%2BMnRFBt6BnyoZk1LWBoMspwSmTqUKMg%40mail.gmail.com%3E

**Comment by ahsandar** [comment]
if this stacktrace from log is any help to identify the issue 
```
2016-11-08 17:10:00 +0800 [warn]: Send exception occurred: Failed to assign partitions to 1 messages
2016-11-08 17:10:00 +0800 [info]: initialized kafka producer: kafka
2016-11-08 17:10:00 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2016-11-08 17:10:00 +0800 error_class="Kafka::DeliveryFailed" error="Failed to as
sign partitions to 1 messages" plugin_id="object:3f931afe1d9c"
  2016-11-08 17:10:00 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.15/lib/kafka/producer.rb:323:in `deliver_messages_with_retries'
  2016-11-08 17:10:00 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.15/lib/kafka/producer.rb:243:in `block in deliver_messages'
  2016-11-08 17:10:00 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.15/lib/kafka/instrumenter.rb:21:in `call'
  2016-11-08 17:10:00 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.15/lib/kafka/instrumenter.rb:21:in `instrument'
  2016-11-08 17:10:00 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.15/lib/kafka/producer.rb:236:in `deliver_messages'
  2016-11-08 17:10:00 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kafka-0.3.1/lib/fluent/plugin/out_kafka_buffered.rb:220:in `block in
 write'
  2016-11-08 17:10:00 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/buffer.rb:123:in `each'
  2016-11-08 17:10:00 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/buffer.rb:123:in `block in msgpack_each'
  2016-11-08 17:10:00 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/plugin/buf_file.rb:71:in `open'
  2016-11-08 17:10:00 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/buffer.rb:120:in `msgpack_each'
  2016-11-08 17:10:00 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kafka-0.3.1/lib/fluent/plugin/out_kafka_buffered.rb:200:in `write'
  2016-11-08 17:10:00 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/buffer.rb:354:in `write_chunk'
  2016-11-08 17:10:00 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/buffer.rb:333:in `pop'
  2016-11-08 17:10:00 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/output.rb:338:in `try_flush'
  2016-11-08 17:10:00 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/output.rb:149:in `run'
2016-11-08 17:10:00 +0800 [warn]: Send exception occurred: Failed to assign partitions to 2 messages
2016-11-08 17:10:00 +0800 [info]: initialized kafka producer: kafka
2016-11-08 17:10:00 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2016-11-08 17:10:00 +0800 error_class="Kafka::DeliveryFailed" error="Failed to as
sign partitions to 2 messages" plugin_id="object:3f931afa9438"
  2016-11-08 17:10:00 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.15/lib/kafka/producer.rb:323:in `deliver_messages_with_retries'
  2016-11-08 17:10:00 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.15/lib/kafka/producer.rb:243:in `block in deliver_messages'
  2016-11-08 17:10:00 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.15/lib/kafka/instrumenter.rb:21:in `call'
  2016-11-08 17:10:00 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.15/lib/kafka/instrumenter.rb:21:in `instrument'
  2016-11-08 17:10:00 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.15/lib/kafka/producer.rb:236:in `deliver_messages'
  2016-11-08 17:10:00 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kafka-0.3.1/lib/fluent/plugin/out_kafka_buffered.rb:234:in `write'
  2016-11-08 17:10:00 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/buffer.rb:354:in `write_chunk'
  2016-11-08 17:10:00 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/buffer.rb:333:in `pop'
  2016-11-08 17:10:00 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/output.rb:338:in `try_flush'
  2016-11-08 17:10:00 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/output.rb:149:in `run'
2016-11-08 17:10:01 +0800 [warn]: Send exception occurred: Failed to assign partitions to 5 messages
2016-11-08 17:10:01 +0800 [info]: initialized kafka producer: kafka
2016-11-08 17:10:01 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2016-11-08 17:10:00 +0800 error_class="Kafka::DeliveryFailed" error="Failed to as
sign partitions to 5 messages" plugin_id="object:3f931afb8014"
  2016-11-08 17:10:01 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.15/lib/kafka/producer.rb:323:in `deliver_messages_with_retries'
  2016-11-08 17:10:01 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.15/lib/kafka/producer.rb:243:in `block in deliver_messages'
  2016-11-08 17:10:01 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.15/lib/kafka/instrumenter.rb:21:in `call'
  2016-11-08 17:10:01 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.15/lib/kafka/instrumenter.rb:21:in `instrument'
  2016-11-08 17:10:01 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-kafka-0.3.15/lib/kafka/producer.rb:236:in `deliver_messages'
  2016-11-08 17:10:01 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kafka-0.3.1/lib/fluent/plugin/out_kafka_buffered.rb:220:in `block in
 write'
  2016-11-08 17:10:01 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/buffer.rb:123:in `each'
  2016-11-08 17:10:01 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/buffer.rb:123:in `block in msgpack_each'
  2016-11-08 17:10:01 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/plugin/buf_file.rb:71:in `open'
  2016-11-08 17:10:01 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/buffer.rb:120:in `msgpack_each'
  2016-11-08 17:10:01 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kafka-0.3.1/lib/fluent/plugin/out_kafka_buffered.rb:200:in `write'
  2016-11-08 17:10:01 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/buffer.rb:354:in `write_chunk'
  2016-11-08 17:10:01 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/buffer.rb:333:in `pop'
  2016-11-08 17:10:01 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/output.rb:338:in `try_flush'
  2016-11-08 17:10:01 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/output.rb:149:in `run'
```

**Comment by ahsandar** [comment]
restarted my `kafka` cluster and now having same issue for the initial topic that was working fine, some help in order to understand what this error signifies would be much appreciated

**Comment by ahsandar** [comment]
even if I empty the buffer(by deleting all the files) and restart `fluentd` still see same message pop up again
`temporarily failed to flush the buffer. next_retry=2016-11-09 14:53:33 +0800 error_class="Kafka::DeliveryFailed" error="Failed to assign partitions to 3 messages" plugin_id="object:3f7f82569e60"`

**Comment by ahsandar** [comment]
Something I find interesting is that if an exception is raised `shutdown_producers` is called and all producers are to be shut, and then on `refresh_client(false)` is called , so from the logs the `object:XXXXXXXX` doesn't changes which means same producer object is used , which is why same exception is repeated over and over as prodeucer most likely doesn't refreshes the `metadata` and gets stuck in the loop, any view on that

```
2016-11-08 15:29:01 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2016-11-08 15:29:03 +0800 error_class="Kafka::DeliveryFailed" error="Failed to assign partitions to 1 messages" plugin_id="object:3f9bef9ce8dc"
  2016-11-08 15:29:01 +0800 [warn]: suppressed same stacktrace
2016-11-08 15:29:01 +0800 [warn]: Send exception occurred: Failed to assign partitions to 5 messages
2016-11-08 15:29:01 +0800 [info]: initialized kafka producer: kafka
2016-11-08 15:29:01 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2016-11-08 15:28:59 +0800 error_class="Kafka::DeliveryFailed" error="Failed to assign partitions to 5 messages" plugin_id="object:3f9bef9ad8e4"
  2016-11-08 15:29:01 +0800 [warn]: suppressed same stacktrace
2016-11-08 15:29:01 +0800 [warn]: Send exception occurred: Failed to assign partitions to 2 messages
2016-11-08 15:29:01 +0800 [info]: initialized kafka producer: kafka
2016-11-08 15:29:01 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2016-11-08 15:29:04 +0800 error_class="Kafka::DeliveryFailed" error="Failed to assign partitions to 2 messages" plugin_id="object:3f9bef9a07c0"
  2016-11-08 15:29:01 +0800 [warn]: suppressed same stacktrace
2016-11-08 15:29:03 +0800 [warn]: Send exception occurred: Failed to assign partitions to 5 messages
2016-11-08 15:29:03 +0800 [info]: initialized kafka producer: kafka
2016-11-08 15:29:03 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2016-11-08 15:29:03 +0800 error_class="Kafka::DeliveryFailed" error="Failed to assign partitions to 5 messages" plugin_id="object:3f9bef9ad8e4"
  2016-11-08 15:29:03 +0800 [warn]: suppressed same stacktrace
2016-11-08 15:29:05 +0800 [warn]: Send exception occurred: Failed to assign partitions to 1 messages
2016-11-08 15:29:05 +0800 [info]: initialized kafka producer: kafka
2016-11-08 15:29:05 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2016-11-08 15:29:12 +0800 error_class="Kafka::DeliveryFailed" error="Failed to assign partitions to 1 messages" plugin_id="object:3f9bef9ce8dc"
  2016-11-08 15:29:05 +0800 [warn]: suppressed same stacktrace
2016-11-08 15:29:05 +0800 [warn]: Send exception occurred: Failed to assign partitions to 2 messages
2016-11-08 15:29:05 +0800 [info]: initialized kafka producer: kafka
2016-11-08 15:29:05 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2016-11-08 15:29:12 +0800 error_class="Kafka::DeliveryFailed" error="Failed to assign partitions to 2 messages" plugin_id="object:3f9bef9a07c0"
  2016-11-08 15:29:05 +0800 [warn]: suppressed same stacktrace
2016-11-08 15:29:05 +0800 [warn]: Send exception occurred: Failed to assign partitions to 5 messages
2016-11-08 15:29:05 +0800 [info]: initialized kafka producer: kafka
2016-11-08 15:29:05 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2016-11-08 15:29:11 +0800 error_class="Kafka::DeliveryFailed" error="Failed to assign partitions to 5 messages" plugin_id="object:3f9bef9ad8e4"
  2016-11-08 15:29:05 +0800 [warn]: suppressed same stacktrace
2016-11-08 15:29:13 +0800 [warn]: Send exception occurred: Failed to assign partitions to 5 messages
2016-11-08 15:29:13 +0800 [info]: initialized kafka producer: kafka
2016-11-08 15:29:13 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2016-11-08 15:29:28 +0800 error_class="Kafka::DeliveryFailed" error="Failed to assign partitions to 5 messages" plugin_id="object:3f9bef9ad8e4"
  2016-11-08 15:29:13 +0800 [warn]: suppressed same stacktrace
2016-11-08 15:29:13 +0800 [warn]: Send exception occurred: Failed to assign partitions to 1 messages
2016-11-08 15:29:13 +0800 [info]: initialized kafka producer: kafka
2016-11-08 15:29:13 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2016-11-08 15:29:28 +0800 error_class="Kafka::DeliveryFailed" error="Failed to assign partitions to 1 messages" plugin_id="object:3f9bef9ce8dc"
  2016-11-08 15:29:13 +0800 [warn]: suppressed same stacktrace
```

**Comment by repeatedly** [comment]
> so from the logs the object:XXXXXXXX doesn't changes which means same producer object is used

This refers `plugin_id="object:3f9bef9ad8e4"`, right?
This id is plugin object id, not producer object.
So same plugin_id is no problem in this case.

**Comment by ahsandar** [comment]
then how come it gets the same object id for plugin every time for different topic, and repeats the same error even after clearing the buffer, from what i understand metadata refresh is required everytime this situation rises as partitions are assigned randomly, any way to do it in the plugin, i have submitted a PR on the gem `ruby-kafka`, if that doesn't gets merged do you have any plans to counter this issue ?

**Comment by ahsandar** [comment]
I am hoping this will resolve the issue https://github.com/zendesk/ruby-kafka/pull/294#issuecomment-264140300, i have this happens when a broker falls out of the quorm o goes down and the leader on the topic changes but fluentd doesn't updated the metadata to resolve this , everytime this happens it should update the metadata and start sending message to the new leader and once the broker is brought back up and leader election is performed the metadata will refresh again following the cycle,  may be you can help test this PR

**Comment by ahsandar** [comment]
@dtboctor  could you help test the PR in `ruby-kafka`?

**Comment by ahsandar** [comment]
@repeatedly can we get version bump for `ruby-kafka` to 0.3.16.beta2 just got the PR (https://github.com/zendesk/ruby-kafka/pull/294) merged to hopefully resolve this issue

**Comment by repeatedly** [comment]
Released 0.4.2.rc1 for testing.

**Comment by ahsandar** [comment]
@repeatedly thanks , @dtboctor can you also update at your end for testing the new release

**Comment by ahsandar** [comment]
updated the gem seems to be working ok, without any issue, will continue to update, specifically about when `Failed to assign partitions` issue is encountered and how it performs then.

**Comment by dtboctor** [comment]
I can test this out, but I can't reproduce the original error anymore

**Comment by ahsandar** [comment]
closing for now , as the ruby-kafka tag meant for this is being used and haven't seen it happen now

**Comment by ahsandar** [comment]
thanks @repeatedly and @dtboctor

**Comment by ahsandar** [comment]
happy to report that the fix works 
![metadata-refresh](https://cloud.githubusercontent.com/assets/2472371/22133308/805764b6-defa-11e6-84a1-31db92cc601d.png)
