### ISSUE TITLE
kafka consumer group can't work 

### ISSUE THREAD

**Issue by jaywayjayway** [fluent/fluent-plugin-kafka#99]
HI,I use  input kafka plugin with consumer group. But it doesn't work .

kafka  input plugin  conf:
```
<source>
  @type kafka_group
  brokers es1.quakecloud:9092,es2.quakecloud.cc:9092
  topics   test
  consumer_group access-group
  format  json
  add_prefix access
</source>
```
I check  out in Kafka  ， But can't  find  the  consumer group 
```
[root@es2 td-agent]# kafka-consumer-groups.sh  --list  --zookeeper  localhost:2181
console-consumer-78528
console-consumer-78813
```
What can I do  for it ?

**Comment by repeatedly** [comment]
Do you use kafka v0.9 or later?

**Comment by jaywayjayway** [comment]
@repeatedly  HI, my kafka is  `kafka_2.11-0.9.0.1`

**Comment by repeatedly** [comment]
Hmm... I tested in_kafka_group with local `kafka_2.11-0.9.0.1` and it worked.

```
% RUBYLIB=~/dev/fluentd/fluentd/lib:~/dev/fluentd/fluent-plugin-kafka/lib ~/dev/fluentd/fluentd/bin/fluentd -c kafka_group.conf 
2016-11-16 15:04:21 +0900 [info]: reading config file path="kafka_group.conf"
2016-11-16 15:04:21 +0900 [info]: starting fluentd-0.14.9
2016-11-16 15:04:21 +0900 [info]: spawn command to main: /Users/repeatedly/.rbenv/versions/2.3.1/bin/ruby -Eascii-8bit:ascii-8bit /Users/repeatedly/dev/fluentd/fluentd/bin/fluentd -c kafka_group.conf --under-supervisor
2016-11-16 15:04:21 +0900 [info]: reading config file path="kafka_group.conf"
2016-11-16 15:04:21 +0900 [info]: starting fluentd-0.14.9 without supervision
[snip]
2016-11-16 15:04:21 +0900 [info]: adding source type="kafka_group"
2016-11-16 15:04:21 +0900 [info]: Will watch for topics test at brokers localhost:9092 and 'access-group' group
2016-11-16 15:04:21 +0900 [info]: using configuration file: <ROOT>
  <source>
    @type kafka_group
    topics "test"
    consumer_group "access-group"
    format "json"
    add_prefix "access"
  </source>
</ROOT>
```

```
% bin/kafka-consumer-groups.sh --list --new-consumer --bootstrap-server localhost:9092
access-group
```

**Comment by jaywayjayway** [comment]
Hmm.... I found it 
```
[root@es2 ~]# kafka-consumer-groups.sh   --new-consumer     --list  --bootstrap-server localhost:9092
access-group
security-group
```
but I  can't  list  anything about the  consumer group. it tole me this :
```
[root@es2 ~]# kafka-consumer-groups.sh --new-consumer --bootstrap-server localhost:9092 --describe --group access-group
GROUP, TOPIC, PARTITION, CURRENT OFFSET, LOG END OFFSET, LAG, OWNER
Error while executing consumer group command Error reading field 'responses': Error reading field 'partition_responses': Error reading field 'metadata': java.lang.NegativeArraySizeException
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'responses': Error reading field 'partition_responses': Error reading field 'metadata': java.lang.NegativeArraySizeException
	at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:71)
	at org.apache.kafka.clients.NetworkClient.handleCompletedReceives(NetworkClient.java:439)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:265)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.clientPoll(ConsumerNetworkClient.java:320)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:213)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:193)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:163)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.fetchCommittedOffsets(ConsumerCoordinator.java:294)
	at org.apache.kafka.clients.consumer.KafkaConsumer.committed(KafkaConsumer.java:1142)
	at kafka.admin.ConsumerGroupCommand$KafkaConsumerGroupService$$anonfun$describeGroup$2$$anonfun$7.apply(ConsumerGroupCommand.scala:323)
	at kafka.admin.ConsumerGroupCommand$KafkaConsumerGroupService$$anonfun$describeGroup$2$$anonfun$7.apply(ConsumerGroupCommand.scala:322)
	at scala.collection.immutable.List.flatMap(List.scala:327)
	at kafka.admin.ConsumerGroupCommand$KafkaConsumerGroupService$$anonfun$describeGroup$2.apply(ConsumerGroupCommand.scala:322)
	at kafka.admin.ConsumerGroupCommand$KafkaConsumerGroupService$$anonfun$describeGroup$2.apply(ConsumerGroupCommand.scala:320)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.admin.ConsumerGroupCommand$KafkaConsumerGroupService.describeGroup(ConsumerGroupCommand.scala:320)
	at kafka.admin.ConsumerGroupCommand$ConsumerGroupService$class.describe(ConsumerGroupCommand.scala:84)
	at kafka.admin.ConsumerGroupCommand$KafkaConsumerGroupService.describe(ConsumerGroupCommand.scala:302)
	at kafka.admin.ConsumerGroupCommand$.main(ConsumerGroupCommand.scala:63)
	at kafka.admin.ConsumerGroupCommand.main(ConsumerGroupCommand.scala)
```

**Comment by repeatedly** [comment]
Hmm... I'm not sure this is a plugin issue or not.
If the problem is plugin side, I will investigate it.
